-- 018_daywordplay_words_seed.sql
-- Word bank seed data for Day Word Play

INSERT INTO daywordplay_words (word, part_of_speech, definition, pronunciation, etymology) VALUES
('benignity', 'noun', 'The quality of being kind, gentle, and generous to others.', 'bɪˈnɪɡnɪti', 'From Latin benignitas, from benignus (kind, gentle).'),
('ephemeral', 'adjective', 'Lasting for a very short time; transitory.', 'ɪˈfɛmərəl', 'From Greek ephemeros (lasting only a day), from epi (on) + hemera (day).'),
('mellifluous', 'adjective', 'Having a sweet or musical, pleasant sound; flowing with honey.', 'mɛˈlɪfluəs', 'From Latin mellifluus, from mel (honey) + fluere (to flow).'),
('sonder', 'noun', 'The realization that each passerby has a life as vivid and complex as one''s own.', 'ˈsɒndər', 'Coined by John Koenig for The Dictionary of Obscure Sorrows.'),
('petrichor', 'noun', 'A pleasant smell that frequently accompanies the first rain after a long period of warm, dry weather.', 'ˈpɛtrɪkɔː', 'From Greek petra (stone) + ichor (the fluid that flows in the veins of gods).'),
('serendipity', 'noun', 'The occurrence of events by chance in a happy or beneficial way.', 'ˌsɛrənˈdɪpɪti', 'Coined by Horace Walpole, from the Persian fairy tale The Three Princes of Serendip.'),
('perspicacious', 'adjective', 'Having a ready insight into things; shrewd and discerning.', 'ˌpɜːspɪˈkeɪʃəs', 'From Latin perspicax (sharp-sighted), from perspicere (to see through).'),
('sanguine', 'adjective', 'Optimistic or positive, especially in a difficult situation.', 'ˈsæŋɡwɪn', 'From Latin sanguineus (of blood), as blood was thought to cause optimism.'),
('eloquence', 'noun', 'Fluent or persuasive speaking or writing.', 'ˈɛləkwəns', 'From Latin eloquentia, from eloqui (to speak out).'),
('hiraeth', 'noun', 'A homesickness for a home to which you cannot return; a deep longing for something absent.', 'ˈhɪəraiθ', 'Welsh word with no direct English translation, deeply embedded in Welsh culture.'),
('ineffable', 'adjective', 'Too great or extreme to be expressed or described in words.', 'ɪˈnɛfəbəl', 'From Latin ineffabilis, from in (not) + effabilis (utterable).'),
('luminous', 'adjective', 'Full of or shedding light; bright or shining; clearly expressed and easily understood.', 'ˈluːmɪnəs', 'From Latin luminosus, from lumen (light).'),
('soliloquy', 'noun', 'An act of speaking one''s thoughts aloud when by oneself or regardless of any hearers.', 'səˈlɪləkwi', 'From Latin soliloquium, coined by St. Augustine from solus (alone) + loqui (to speak).'),
('zenith', 'noun', 'The time at which something is most powerful or successful; the highest point.', 'ˈziːnɪθ', 'From Arabic samt al-ras (direction of the head), later corrupted to zenit in Latin.'),
('labyrinthine', 'adjective', 'Of, relating to, or resembling a labyrinth; intricate and confusing.', 'ˌlæbəˈrɪnθɪn', 'From Greek labyrinthos, the legendary maze built by Daedalus.'),
('quixotic', 'adjective', 'Exceedingly idealistic; unrealistic and impractical.', 'kwɪkˈsɒtɪk', 'From Don Quixote, the idealistic hero of Cervantes'' novel.'),
('vestigial', 'adjective', 'Forming a very small remnant of something that was once much larger or more noticeable.', 'vɛˈstɪdʒɪəl', 'From Latin vestigium (footstep, trace).'),
('cacophony', 'noun', 'A harsh, discordant mixture of sounds.', 'kəˈkɒfəni', 'From Greek kakophonia, from kakos (bad) + phone (sound).'),
('ephemeron', 'noun', 'A thing that exists or is used or enjoyed for only a short time.', 'ɪˈfɛmərɒn', 'From Greek ephemeron, neuter of ephemeros (lasting only a day).'),
('liminal', 'adjective', 'Relating to a transitional or initial stage of a process; occupying a position at a threshold.', 'ˈlɪmɪnəl', 'From Latin limen (threshold).'),
('penumbra', 'noun', 'The partially shaded outer region of a shadow; a peripheral or indeterminate area.', 'pɪˈnʌmbrə', 'From Latin paene (almost) + umbra (shadow).'),
('susurrus', 'noun', 'Whispering, murmuring, or rustling sounds.', 'sʊˈsʌrəs', 'From Latin susurrus (whisper, hum).'),
('wanderlust', 'noun', 'A strong desire to travel and explore the world.', 'ˈwɒndəlʌst', 'From German Wanderlust, from wandern (to wander) + Lust (desire).'),
('nadir', 'noun', 'The lowest or most unsuccessful point in a situation; the point directly below the observer.', 'ˈneɪdɪə', 'From Arabic nazir (opposite to the zenith).'),
('halcyon', 'adjective', 'Denoting a period of time in the past that was idyllically happy and peaceful.', 'ˈhælsiən', 'From Greek halcyon (kingfisher), believed to calm the sea for nesting.'),
('loquacious', 'adjective', 'Tending to talk a great deal; talkative.', 'ləʊˈkweɪʃəs', 'From Latin loquax, from loqui (to talk).'),
('ephemeral', 'adjective', 'Lasting for a very short time; transitory.', 'ɪˈfɛmərəl', 'From Greek ephemeros (lasting only a day).'),
('arcane', 'adjective', 'Understood by few; mysterious or secret.', 'ɑːˈkeɪn', 'From Latin arcanus (secret), from arcere (to shut in).'),
('beguile', 'verb', 'To charm or enchant someone in a deceptive way; to help time pass pleasantly.', 'bɪˈɡaɪl', 'From Middle English bigylen, from be- (thoroughly) + guile (deceit).'),
('cogent', 'adjective', 'Clear, logical, and convincing in reasoning or argument.', 'ˈkəʊdʒənt', 'From Latin cogentem, from cogere (to compel), from co- + agere (to drive).'),
('diaphanous', 'adjective', 'Light, delicate, and translucent; so thin as to be almost transparent.', 'daɪˈæfənəs', 'From Greek diaphanes, from dia (through) + phainein (to show).'),
('ebullient', 'adjective', 'Cheerful and full of energy; overflowing with enthusiasm or excitement.', 'ɪˈbʊlɪənt', 'From Latin ebullire (to bubble up), from e- + bullire (to boil).'),
('fugacious', 'adjective', 'Tending to disappear; fleeting.', 'fjʊˈɡeɪʃəs', 'From Latin fugax, from fugere (to flee).'),
('gossamer', 'noun', 'A fine, filmy substance; something light, delicate, or insubstantial.', 'ˈɡɒsəmə', 'From Middle English gossomer (goose summer), threads of cobwebs floating in autumn air.'),
('harbinger', 'noun', 'A person or thing that announces or signals the approach of another.', 'ˈhɑːbɪndʒə', 'From Middle English herbergeour, from Old French herbergier (to provide shelter).'),
('incandescent', 'adjective', 'Emitting light as a result of being heated; full of strong emotion; brilliant.', 'ˌɪnkænˈdɛsənt', 'From Latin incandescere (to glow), from in + candescere (to become white-hot).'),
('jejune', 'adjective', 'Naive, simplistic, and superficial; lacking interest or significance.', 'dʒɪˈdʒuːn', 'From Latin jejunus (fasting, barren), originally meaning empty of food.'),
('kaleidoscopic', 'adjective', 'Having complex patterns of colors; frequently changing.', 'kəˌlaɪdəˈskɒpɪk', 'From Greek kalos (beautiful) + eidos (form) + skopein (to look at).'),
('laconic', 'adjective', 'Using very few words; brief and concise.', 'ləˈkɒnɪk', 'From Greek Lakonikos (of Laconia/Sparta), whose inhabitants were famed for brevity.'),
('melancholy', 'noun', 'A feeling of pensive sadness, typically with no obvious cause.', 'ˈmɛlənkɒli', 'From Greek melankholia, from melas (black) + khole (bile), as black bile caused sadness.'),
('nocturnal', 'adjective', 'Done, occurring, or active at night.', 'nɒkˈtɜːnəl', 'From Latin nocturnalis, from nox/noctis (night).'),
('ossify', 'verb', 'To turn into bone or bony tissue; to cease developing; to become rigid or fixed.', 'ˈɒsɪfaɪ', 'From Latin os/ossis (bone) + -fy (to make).'),
('panacea', 'noun', 'A solution or remedy for all difficulties or diseases.', 'ˌpænəˈsiːə', 'From Greek panakeia (all-healing), from pan (all) + akos (remedy).'),
('quintessential', 'adjective', 'Representing the most perfect or typical example of a quality or class.', 'ˌkwɪntɪˈsɛnʃəl', 'From Medieval Latin quinta essentia (fifth essence), the purest form of a thing.'),
('recondite', 'adjective', 'Not known by many people; abstruse; dealing with obscure subject matter.', 'ˈrɛkəndaɪt', 'From Latin reconditus (hidden away), from re- + condere (to put together).'),
('sempiternal', 'adjective', 'Eternal and unchanging; everlasting.', 'ˌsɛmpɪˈtɜːnəl', 'From Late Latin sempiternalis, from semper (always) + aeternus (eternal).'),
('tenacious', 'adjective', 'Tending to keep a firm hold of something; not easily stopped or discouraged.', 'tɪˈneɪʃəs', 'From Latin tenax, from tenere (to hold).'),
('umbra', 'noun', 'The fully shaded inner region of a shadow; the shadow of the moon during an eclipse.', 'ˈʌmbrə', 'From Latin umbra (shade, shadow).'),
('verdant', 'adjective', 'Green with grass or other rich vegetation; of the bright green color of lush grass.', 'ˈvɜːdənt', 'From Old French verdoiant, from verdir (to become green), from Latin viridis.'),
('wistful', 'adjective', 'Having or showing a feeling of vague or regretful longing.', 'ˈwɪstfʊl', 'Probably from obsolete wistly (intently), blended with wishful.'),
('xenophilia', 'noun', 'A love of foreign peoples, cultures, or customs.', 'ˌzɛnəˈfɪlɪə', 'From Greek xenos (stranger) + philia (love, fondness).'),
('yore', 'noun', 'The distant past (archaic, used in the phrase "of yore").', 'jɔː', 'From Old English geara (formerly), related to gear (year).'),
('zealous', 'adjective', 'Having or showing great energy or enthusiasm in pursuit of a cause.', 'ˈzɛləs', 'From Medieval Latin zelosus, from Late Greek zelos (zeal).'),
('acrimony', 'noun', 'Bitterness or ill feeling, especially in speech or manner.', 'ˈækrɪməni', 'From Latin acrimonia (sharpness), from acer (sharp, bitter).'),
('bucolic', 'adjective', 'Relating to the pleasant aspects of the countryside and rural life; pastoral.', 'bjuːˈkɒlɪk', 'From Greek boukolikos, from boukolos (cowherd), from bous (ox) + kolein (to tend).'),
('clement', 'adjective', 'Mild and pleasant; merciful and lenient.', 'ˈklɛmənt', 'From Latin clemens (mild, gentle).'),
('dilettante', 'noun', 'A person who cultivates an area of interest, such as the arts, without real commitment or knowledge.', 'ˌdɪlɪˈtænti', 'From Italian dilettante (one who delights in), from dilettare (to delight).'),
('effulgent', 'adjective', 'Radiant; shining brightly.', 'ɪˈfʌldʒənt', 'From Latin effulgere (to shine out), from ex- + fulgere (to shine).'),
('fulgent', 'adjective', 'Shining brilliantly; radiant.', 'ˈfʌldʒənt', 'From Latin fulgens, from fulgere (to shine).'),
('garrulous', 'adjective', 'Excessively talkative, especially on trivial matters.', 'ˈɡærʊləs', 'From Latin garrulus, from garrire (to chatter).'),
('hubris', 'noun', 'Excessive pride or self-confidence; arrogance that leads to downfall.', 'ˈhjuːbrɪs', 'From Greek hybris (insolence, excessive pride).'),
('inchoate', 'adjective', 'Just begun and not fully formed or developed; rudimentary.', 'ɪnˈkəʊɪt', 'From Latin inchoatus, from inchoare (to begin).'),
('juxtapose', 'verb', 'To place or deal with close together for contrasting effect.', 'ˌdʒʌkstəˈpəʊz', 'From French juxtaposer, from Latin juxta (next to) + poser (to place).'),
('kismet', 'noun', 'Destiny; fate.', 'ˈkɪzmɛt', 'From Ottoman Turkish qismet, from Arabic qisma (portion, lot).'),
('languid', 'adjective', 'Displaying or having a disinclination for physical exertion or effort; slow.', 'ˈlæŋɡwɪd', 'From Latin languidus, from languere (to be faint).'),
('magnanimous', 'adjective', 'Very generous or forgiving, especially toward a rival or less powerful person.', 'mæɡˈnænɪməs', 'From Latin magnanimus, from magnus (great) + animus (soul).'),
('nonchalant', 'adjective', 'Feeling or appearing casually calm and relaxed; not displaying anxiety.', 'ˈnɒnʃələnt', 'From French nonchalant (not being warm), from non- + chaloir (to be concerned).'),
('obstinate', 'adjective', 'Stubbornly refusing to change one''s opinion or chosen course of action.', 'ˈɒbstɪnət', 'From Latin obstinatus (resolved), from obstinare (to persist in).'),
('palimpsest', 'noun', 'Something altered but still bearing visible traces of an earlier form.', 'ˈpælɪmpsɛst', 'From Greek palimpsestos, from palin (again) + psen (to scrape).'),
('querulous', 'adjective', 'Complaining in a petulant or whining manner; habitually complaining.', 'ˈkwɛrʊləs', 'From Late Latin querulosus, from Latin querulus (complaining), from queri (to complain).'),
('redolent', 'adjective', 'Strongly reminiscent or suggestive of; having a strong pleasant smell.', 'ˈrɛdələnt', 'From Latin redolere (to emit a scent), from re- + olere (to smell).'),
('solace', 'noun', 'Comfort or consolation in a time of distress or sadness.', 'ˈsɒlɪs', 'From Latin solacium, from solari (to console).'),
('tacit', 'adjective', 'Understood or implied without being stated.', 'ˈtæsɪt', 'From Latin tacitus (silent), from tacere (to be silent).'),
('ubiquitous', 'adjective', 'Present, appearing, or found everywhere.', 'juːˈbɪkwɪtəs', 'From Latin ubique (everywhere), from ubi (where) + -que (and).'),
('vernacular', 'noun', 'The language or dialect spoken by the ordinary people in a particular country or region.', 'vəˈnækjʊlə', 'From Latin vernaculus (domestic, indigenous), from verna (home-born slave).'),
('wabi-sabi', 'noun', 'A Japanese aesthetic concept based on finding beauty in imperfection and transience.', 'ˈwɑːbi ˈsɑːbi', 'From Japanese wabi (rustic simplicity) + sabi (the beauty of age and wear).'),
('xeric', 'adjective', 'Relating to or requiring only a small amount of moisture.', 'ˈzɪərɪk', 'From Greek xeros (dry).'),
('yugen', 'noun', 'A profound awareness of the universe that triggers emotional responses too deep and mysterious for words.', 'ˈjuːɡɛn', 'From Japanese yugen (dim, deep, mysterious).'),
('zeal', 'noun', 'Great energy or enthusiasm in pursuit of a cause or an objective.', 'ziːl', 'From Late Latin zelus (zeal), from Greek zelos (fervor).'),
('aesthetic', 'adjective', 'Concerned with beauty or the appreciation of beauty.', 'iːsˈθɛtɪk', 'From Greek aisthetikos (perceptible to the senses), from aisthanesthai (to perceive).'),
('blithe', 'adjective', 'Showing a casual and cheerful indifference considered to be callous or improper.', 'blaɪð', 'From Old English blithe (joyous, gentle), related to Dutch blij (glad).'),
('concinnity', 'noun', 'Studied elegance of literary or artistic style; harmonious arrangement.', 'kənˈsɪnɪti', 'From Latin concinnitas (elegance), from concinnus (skillfully put together).'),
('dalliance', 'noun', 'A casual romantic or sexual relationship; dawdling or trifling with time.', 'ˈdælɪəns', 'From Old French daliance, from dalier (to chat, flirt).'),
('elegy', 'noun', 'A poem of serious reflection, typically a lament for the dead.', 'ˈɛlɪdʒi', 'From Greek elegeia, from elegos (mournful poem).'),
('falcate', 'adjective', 'Curved like a sickle; hooked.', 'ˈfælkeɪt', 'From Latin falcatus, from falx/falcis (sickle).'),
('genuflect', 'verb', 'To lower one''s body briefly by bending one knee to the ground; to show deference.', 'ˈdʒɛnjʊflɛkt', 'From Latin genuflectere, from genu (knee) + flectere (to bend).'),
('hyaline', 'adjective', 'Glassy; translucent; glass-like in appearance.', 'ˈhaɪəlɪn', 'From Greek hyalinos, from hyalos (glass or crystal).'),
('iridescent', 'adjective', 'Showing luminous colors that seem to change when seen from different angles.', 'ˌɪrɪˈdɛsənt', 'From Latin iris/iridis (rainbow) + -escent (becoming).'),
('jocund', 'adjective', 'Cheerful and lighthearted.', 'ˈdʒɒkənd', 'From Latin jocundus (pleasant, agreeable), from juvare (to please).'),
('keening', 'noun', 'A wailing sound expressing grief.', 'ˈkiːnɪŋ', 'From Irish caoine (lamentation), from caoinim (I weep).'),
('lissome', 'adjective', 'Thin, supple, and graceful.', 'ˈlɪsəm', 'Variant of lithesome, from lithe + -some.'),
('mnemonic', 'adjective', 'Aiding or designed to aid the memory.', 'nɪˈmɒnɪk', 'From Greek mnemonikos, from mnemon (mindful), from mnasthai (to remember).')
ON CONFLICT DO NOTHING;
