-- ─────────────────────────────────────────────────────────────────────────────
-- plantplanner — enriched catalog seed (iteration 1).
-- Reseeds plantplanner_plants after 004's drop+create with ~40 plants spanning
-- North American natives, edibles, and ornamentals/herbs. Each row populates the
-- 6 new knowledge columns (bloom_months, native, usda_zones, pollinator_attracts,
-- water_need, care_summary) plus the existing fields.
-- render_key values reuse existing keys in plantplanner_renders (untouched by 004).
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO public.plantplanner_plants
  (name, category, height_inches, spread_inches, sunlight, bloom_season, bloom_months, native, usda_zones, pollinator_attracts, water_need, care_summary, description, render_key, sort_order) VALUES

-- ── North American natives (15) ──────────────────────────────────────────────
('Echinacea (Purple Coneflower)', 'flower', 36, 18, 'full_sun', '{summer,fall}', '{6,7,8,9}', true, '[3,9]'::int4range, '{bees,butterflies}', 'low', 'Drought-tolerant once established; leave seed heads for goldfinches.', 'Native purple daisy with a prominent cone center. Long bloom season and a magnet for pollinators.', 'daisy_purple', 1),
('Black-Eyed Susan', 'flower', 30, 18, 'full_sun', '{summer,fall}', '{6,7,8,9,10}', true, '[3,9]'::int4range, '{bees,butterflies}', 'low', 'Drought-tolerant prairie native; deadhead for longer bloom.', 'Cheerful golden-yellow daisy with a dark cone. Reliable native perennial that self-seeds modestly.', 'daisy_yellow', 2),
('Butterfly Weed', 'flower', 24, 18, 'full_sun', '{summer}', '{6,7,8}', true, '[3,9]'::int4range, '{bees,butterflies}', 'low', 'Loves dry, lean soil; do not transplant once tap root sets.', 'Vivid orange milkweed and a critical monarch host plant. Deep tap root makes it drought-proof.', 'flower_nasturtium', 3),
('Bee Balm', 'flower', 36, 24, 'full_sun', '{summer}', '{6,7,8}', true, '[4,9]'::int4range, '{bees,butterflies,hummingbirds}', 'medium', 'Thin clumps for airflow to prevent powdery mildew.', 'Shaggy red mophead flowers atop minty foliage. Hummingbirds love it.', 'flower_geranium', 4),
('Blazing Star (Liatris)', 'flower', 36, 12, 'full_sun', '{summer}', '{7,8,9}', true, '[3,9]'::int4range, '{bees,butterflies}', 'low', 'Tolerates poor soil; corms multiply slowly over years.', 'Vertical purple bottle-brush spikes that bloom top-down. Classic prairie native.', 'flower_snapdragon', 5),
('Goldenrod', 'flower', 48, 24, 'full_sun', '{fall}', '{8,9,10}', true, '[3,9]'::int4range, '{bees,butterflies,beneficial_insects}', 'low', 'Cut back hard in early summer for shorter, bushier plants.', 'Golden plumes that fuel migrating monarchs and native bees in late season. Not the cause of hay fever.', 'daisy_yellow', 6),
('Wild Columbine', 'flower', 24, 12, 'partial', '{spring}', '{4,5,6}', true, '[3,8]'::int4range, '{hummingbirds,bees}', 'medium', 'Self-seeds gently in dappled shade; short-lived perennial.', 'Nodding red-and-yellow lanterns with delicate spurs. One of the earliest hummingbird flowers.', 'flower_impatiens', 7),
('Cardinal Flower', 'flower', 36, 12, 'partial', '{summer,fall}', '{7,8,9}', true, '[3,9]'::int4range, '{hummingbirds,butterflies}', 'high', 'Keep soil consistently moist; mulch crowns lightly in winter.', 'Brilliant scarlet spikes that hummingbirds visit obsessively. Loves wet feet.', 'flower_snapdragon', 8),
('Foxglove Beardtongue (Penstemon)', 'flower', 36, 18, 'full_sun', '{spring,summer}', '{5,6,7}', true, '[3,8]'::int4range, '{bees,hummingbirds}', 'low', 'Avoid wet winter soil; well-drained ground is essential.', 'White tubular flowers on tall spikes above wine-tinted foliage. Tough native perennial.', 'flower_snapdragon', 9),
('Joe Pye Weed', 'flower', 72, 36, 'full_sun', '{summer,fall}', '{7,8,9}', true, '[3,9]'::int4range, '{bees,butterflies}', 'high', 'Likes moist soil; pinch in May for shorter, bushier plants.', 'Towering native with mauve-pink dome flowers. A late-summer butterfly buffet.', 'daisy_purple', 10),
('New England Aster', 'flower', 48, 24, 'full_sun', '{fall}', '{9,10}', true, '[3,8]'::int4range, '{bees,butterflies}', 'medium', 'Pinch back in early summer to control height and floppiness.', 'Clouds of purple daisies feed migrating monarchs and late-season bees.', 'daisy_purple', 11),
('False Indigo (Baptisia)', 'flower', 48, 36, 'full_sun', '{spring,summer}', '{5,6}', true, '[3,9]'::int4range, '{bees}', 'low', 'Slow to establish; leave undisturbed once planted.', 'Indigo lupine-like spikes followed by inflated black seedpods. Long-lived and shrub-sized.', 'flower_petunia', 12),
('Coral Bells (Heuchera)', 'flower', 18, 18, 'partial', '{spring,summer}', '{5,6,7}', true, '[4,9]'::int4range, '{hummingbirds,bees}', 'medium', 'Divide every 3–4 years; mulch crowns to prevent heaving.', 'Mounds of scalloped, often-burgundy foliage with airy flower wands. A shade-garden workhorse.', 'hosta', 13),
('Garden Phlox', 'flower', 36, 24, 'full_sun', '{summer}', '{7,8,9}', true, '[4,8]'::int4range, '{butterflies,hummingbirds,moths}', 'medium', 'Thin stems for airflow to reduce powdery mildew.', 'Fragrant pink-to-magenta flower clusters atop tall, sturdy stems. A cottage-garden classic.', 'flower_zinnia', 14),
('Lance-Leaf Coreopsis', 'flower', 24, 18, 'full_sun', '{spring,summer}', '{5,6,7,8}', true, '[4,9]'::int4range, '{bees,butterflies}', 'low', 'Deadhead to extend bloom; cut back hard mid-summer to refresh.', 'Cheerful yellow daisies on wiry stems. Drought-tolerant and long-blooming.', 'daisy_yellow', 15),

-- ── Edibles (10) ─────────────────────────────────────────────────────────────
('Tomato', 'vegetable', 48, 24, 'full_sun', '{summer}', '{6,7,8,9}', false, '[3,11]'::int4range, '{bees}', 'medium', 'Stake or cage; water deeply and consistently to prevent blossom-end rot.', 'Classic garden staple. Needs staking and regular feeding.', 'tomato', 16),
('Pepper', 'vegetable', 30, 18, 'full_sun', '{summer}', '{6,7,8,9}', false, '[4,11]'::int4range, '{bees}', 'medium', 'Heat-loving; mulch to keep roots warm and evenly moist.', 'Sweet or hot varieties. Heat loving and slow to start in cool springs.', 'pepper', 17),
('Lettuce', 'vegetable', 10, 12, 'partial', '{spring,fall}', '{}', false, '[3,11]'::int4range, '{}', 'medium', 'Plant in cool weather; water consistently to prevent bitterness.', 'Cool-season leafy green. Quick harvest; succession-plant every 2–3 weeks.', 'leafy_light', 18),
('Carrot', 'vegetable', 12, 3, 'full_sun', '{spring,fall}', '{}', false, '[3,10]'::int4range, '{}', 'medium', 'Loosen soil deeply; thin seedlings ruthlessly for straight roots.', 'Root vegetable. Needs loose, deep soil and patience.', 'carrot', 19),
('Basil', 'herb', 18, 12, 'full_sun', '{summer}', '{7,8}', false, '[4,11]'::int4range, '{bees}', 'medium', 'Pinch flower buds to extend leaf harvest; never plant before last frost.', 'Essential summer herb. Pinch flowers to extend harvest.', 'herb_basil', 20),
('Strawberry', 'fruit', 8, 12, 'full_sun', '{spring,summer}', '{4,5,6}', false, '[3,10]'::int4range, '{bees}', 'medium', 'Mulch with straw; remove first-year flowers on June-bearers for stronger plants.', 'Ground cover fruit. Plant as crowns; runners form new plants.', 'strawberry', 21),
('Blueberry', 'fruit', 48, 36, 'full_sun', '{spring,summer}', '{4,5}', false, '[3,9]'::int4range, '{bees}', 'medium', 'Acidify soil with pine needles; plant two cultivars for cross-pollination.', 'Acidic soil required (pH 4.5–5.5). Multi-year producer.', 'berry_blue', 22),
('Kale', 'vegetable', 24, 18, 'partial', '{spring,fall,winter}', '{}', false, '[3,9]'::int4range, '{}', 'medium', 'Pick outer leaves first; flavor sweetens after a frost.', 'Hardy green. Sweetens after frost and overwinters in mild climates.', 'leafy_curly', 23),
('Bush Bean', 'vegetable', 20, 8, 'full_sun', '{summer}', '{6,7}', false, '[3,10]'::int4range, '{bees}', 'medium', 'Direct-sow after last frost; pick frequently to keep plants producing.', 'Compact. No trellis needed; succession-plant every 2 weeks.', 'bush_bean', 24),
('Zucchini', 'vegetable', 24, 36, 'full_sun', '{summer}', '{6,7,8}', false, '[3,10]'::int4range, '{bees}', 'medium', 'Harvest small (6–8 in) and often; one plant feeds a family.', 'Prolific producer. Needs space and steady moisture.', 'vine_zucchini', 25),

-- ── Ornamentals & herbs (15) ─────────────────────────────────────────────────
('Lavender', 'herb', 24, 18, 'full_sun', '{summer}', '{6,7,8}', false, '[5,9]'::int4range, '{bees,butterflies}', 'low', 'Demands sharp drainage; prune lightly after bloom, never into old wood.', 'Fragrant Mediterranean perennial. Drought-tolerant once established.', 'lavender', 26),
('Rosemary', 'herb', 36, 24, 'full_sun', '{spring,summer}', '{4,5,6}', false, '[7,10]'::int4range, '{bees}', 'low', 'Treat as an annual or container plant in cold climates.', 'Perennial shrub with piney aroma. Drought tolerant.', 'woody_rosemary', 27),
('Thyme', 'herb', 8, 12, 'full_sun', '{spring,summer}', '{5,6,7}', false, '[4,9]'::int4range, '{bees}', 'low', 'Shear after bloom to keep mounds tight; tolerates poor soil.', 'Low-growing perennial. Excellent ground cover between pavers.', 'low_woody_thyme', 28),
('Sage', 'herb', 24, 18, 'full_sun', '{spring,summer}', '{5,6}', false, '[4,10]'::int4range, '{bees,butterflies}', 'low', 'Replace woody plants every 4–5 years for best leaf flavor.', 'Woody perennial herb with silvery leaves. Edible and ornamental.', 'woody_sage', 29),
('Mint', 'herb', 18, 24, 'partial', '{summer}', '{7,8}', false, '[3,9]'::int4range, '{bees,butterflies,beneficial_insects}', 'high', 'Aggressive spreader — plant in containers or sunken pots only.', 'Vigorous perennial herb. Best confined to containers.', 'herb_mint', 30),
('Hosta', 'flower', 24, 36, 'shade', '{summer}', '{7,8}', false, '[3,9]'::int4range, '{hummingbirds}', 'medium', 'Slugs love hostas; bait early or use copper barriers.', 'Shade-loving foliage plant. Hundreds of leaf variations available.', 'hosta', 31),
('Daylily', 'flower', 30, 24, 'full_sun', '{summer}', '{6,7,8}', false, '[3,10]'::int4range, '{bees,butterflies,hummingbirds}', 'low', 'Nearly indestructible; divide clumps every 4–5 years.', 'Each bloom lasts a single day, but plants flower for weeks. Tough as nails.', 'flower_dahlia', 32),
('Hydrangea', 'flower', 60, 60, 'partial', '{summer,fall}', '{6,7,8,9}', false, '[4,9]'::int4range, '{bees,butterflies}', 'high', 'Soil pH controls flower color in some varieties; never let it wilt.', 'Big mophead or lacecap blooms. Flower color shifts with soil pH for some varieties.', 'flower_zinnia', 33),
('Tulip', 'flower', 18, 6, 'full_sun', '{spring}', '{4,5}', false, '[3,8]'::int4range, '{bees}', 'low', 'Plant bulbs 6 in deep in fall; treat as annuals in warm climates.', 'Spring-flowering bulb. Plant in fall for next-year color.', 'flower_zinnia', 34),
('Daffodil', 'flower', 16, 6, 'full_sun', '{spring}', '{3,4,5}', false, '[3,9]'::int4range, '{bees}', 'low', 'Let foliage yellow naturally after bloom to feed next year''s bulbs.', 'Cheerful trumpet-shaped spring bulb. Deer- and rodent-proof.', 'flower_marigold', 35),
('Peony', 'flower', 36, 36, 'full_sun', '{spring,summer}', '{5,6}', false, '[3,8]'::int4range, '{bees,butterflies,beneficial_insects}', 'medium', 'Plant eyes only 1–2 in deep; deeper plantings refuse to bloom.', 'Long-lived perennial with massive fragrant blooms. Outlives its gardener.', 'flower_dahlia', 36),
('Salvia (Nemorosa)', 'flower', 24, 18, 'full_sun', '{spring,summer}', '{5,6,7,8}', false, '[3,8]'::int4range, '{bees,butterflies,hummingbirds}', 'low', 'Cut back hard after first bloom for a strong rebloom.', 'Spiky violet-blue wands above tidy mounds. Pollinator favorite that reblooms readily.', 'flower_snapdragon', 37),
('Catmint (Nepeta)', 'flower', 18, 24, 'full_sun', '{spring,summer,fall}', '{5,6,7,8,9}', false, '[3,8]'::int4range, '{bees,butterflies}', 'low', 'Shear by half after first flush for a tidy second flush.', 'Soft lavender-blue clouds atop aromatic gray-green foliage. Long bloom season.', 'flower_petunia', 38),
('Yarrow (Achillea)', 'flower', 30, 18, 'full_sun', '{summer}', '{6,7,8}', false, '[3,9]'::int4range, '{butterflies,beneficial_insects}', 'low', 'Tolerates poor, dry soil; divide every 2–3 years to keep vigor.', 'Flat-topped flower clusters above ferny foliage. Loved by beneficial insects.', 'flower_marigold', 39),
('Marigold', 'flower', 12, 10, 'full_sun', '{summer,fall}', '{6,7,8,9,10}', false, '[2,11]'::int4range, '{bees,butterflies,beneficial_insects}', 'low', 'Deadhead for continuous bloom; reseeds where happy.', 'Pest-deterrent companion plant. Easy annual that blooms until hard frost.', 'flower_marigold', 40)

ON CONFLICT DO NOTHING;
