#!/bin/bash
# Generates config.js from deploy-time environment variables.
# For local dev, config.js is generated by local_dev/setup-local.py
# (gitignored, never checked in).
set -e

cat > config.js << EOF
// config.js — generated at build time from environment variables
window.APP_CONFIG = {
  apiBase: "${API_BASE:-https://vibelab-production-2119.up.railway.app}",
  project: "boardgame-buddy",
  supabaseUrl: "${SUPABASE_URL}",
  supabaseAnonKey: "${SUPABASE_ANON_KEY}",
  // GCP Identity Platform / Firebase Auth. Set from BGB_FIREBASE_* repo
  // variables, none of which are secrets: apiKey identifies the project and
  // authorizes nothing, and the other three are public identifiers.
  //
  // A BLANK apiKey still means "Firebase not configured", and domain/auth.js
  // still falls back to Supabase Auth on that reading. That is the rollback
  // path, not a leftover: unsetting these four variables and re-running the
  // deploy puts sign-in back on Supabase without reverting a commit.
  // storageBucket and messagingSenderId are deliberately absent: photos go to
  // R2, and push uses this project's own VAPID keypair, not FCM.
  firebase: {
    apiKey: "${FIREBASE_API_KEY}",
    authDomain: "${FIREBASE_AUTH_DOMAIN:-auth.bgbuddy.app}",
    projectId: "${FIREBASE_PROJECT_ID}",
    appId: "${FIREBASE_APP_ID}"
  }
};
EOF

echo "config.js generated."
