// import.js — Import screen: BGG search, file upload, pending review, download skill.
//
// The file upload uses the authenticated user's Supabase JWT.
// All uploads — including admins — are queued in boardgamebuddy_pending_guides for review.

let importPendingBundle = null;
let pendingGuidesCache = [];
let bundleEditCtx = null; // { bundle, rerender: fn } — shared by upload and review contexts

function renderImport() {
  const container = document.getElementById("import-content");

  container.innerHTML = `
    <div class="flex items-center gap-2 mb-3">
      <button class="btn btn-ghost btn-sm btn-square" onclick="showView('browse')" title="Back to Browse">
        <i data-lucide="arrow-left" class="w-4 h-4"></i>
      </button>
      <h2 class="text-xl font-bold font-display flex items-center gap-2">
        <i data-lucide="download" class="w-5 h-5"></i> Import Games
      </h2>
    </div>
    <p class="text-sm text-base-content/60 mb-4">Add new games to BoardgameBuddy from BGG or from a generated guide bundle.</p>

    <!-- 1. Import from BoardGameGeek -->
    <div class="card bg-base-200 mb-3">
      <div class="card-body p-4">
        <h3 class="font-semibold flex items-center gap-2">
          <i data-lucide="globe" class="w-4 h-4"></i> Import from BoardGameGeek
        </h3>
        <p class="text-xs text-base-content/60">Search BGG and add games with their metadata.</p>
        <div class="flex gap-2 mt-2">
          <input type="text" id="bgg-search-input" class="input input-bordered input-sm flex-1" placeholder="Search BGG..." />
          <button class="btn btn-sm btn-primary" onclick="searchBGG()">Search</button>
        </div>
        <div id="bgg-results" class="mt-2"></div>
      </div>
    </div>

    <!-- 2. Import from file -->
    <div class="card bg-base-200 mb-3">
      <div class="card-body p-4">
        <h3 class="font-semibold flex items-center gap-2">
          <i data-lucide="upload" class="w-4 h-4"></i> Import from file
        </h3>
        <p class="text-xs text-base-content/60">
          Upload a GuideBundle JSON generated by the Guide Builder AI prompt.
          All uploads go through admin review before going live.
        </p>

        <input type="file" id="import-guide-file" accept="application/json,.json"
               class="file-input file-input-bordered file-input-sm w-full mt-2" />

        <div id="import-guide-preview" class="mt-2"></div>

        <div class="flex gap-2 mt-2">
          <button id="import-guide-submit" class="btn btn-primary btn-sm" disabled>
            <i data-lucide="upload" class="w-4 h-4"></i>
            Submit for review
          </button>
        </div>
      </div>
    </div>

    <!-- 3. Review pending additions (admin only) -->
    ${currentUser?.is_admin ? `
      <div class="card bg-base-200 mb-3">
        <div class="card-body p-4">
          <h3 class="font-semibold flex items-center gap-2">
            <i data-lucide="shield-check" class="w-4 h-4"></i> Review pending additions
          </h3>
          <p class="text-xs text-base-content/60">Approve or reject guide bundles submitted by any user.</p>
          <button class="btn btn-outline btn-sm mt-2" onclick="showView('pending-guides'); renderPendingGuides();">
            <i data-lucide="inbox" class="w-4 h-4"></i> Open review queue
          </button>
        </div>
      </div>
    ` : ""}

    <!-- 4. Download Guide Builder instructions -->
    <div class="card bg-base-200 mb-3">
      <div class="card-body p-4">
        <h3 class="font-semibold flex items-center gap-2">
          <i data-lucide="file-down" class="w-4 h-4"></i> Download Guide Builder instructions
        </h3>
        <p class="text-xs text-base-content/60">
          Get the AI prompt that turns a rulebook into a BoardgameBuddy guide bundle.
          Feed the downloaded <code class="text-xs">.md</code> into your own AI with a game name, then upload the resulting JSON above.
        </p>
        <button class="btn btn-outline btn-sm mt-2" onclick="downloadGuideBuilderInstructions()">
          <i data-lucide="file-down" class="w-4 h-4"></i> Download .md
        </button>
      </div>
    </div>
  `;
  if (window.lucide) window.lucide.createIcons();

  importPendingBundle = null;
  bundleEditCtx = null;
  document.getElementById("import-guide-file").addEventListener("change", handleImportFileSelect);
  document.getElementById("import-guide-submit").addEventListener("click", handleImportSubmit);
}

async function handleImportFileSelect(e) {
  const file = e.target.files?.[0];
  const preview = document.getElementById("import-guide-preview");
  const submit = document.getElementById("import-guide-submit");
  if (!file) {
    importPendingBundle = null;
    bundleEditCtx = null;
    preview.innerHTML = "";
    submit.disabled = true;
    return;
  }
  try {
    const text = await file.text();
    const bundle = JSON.parse(text);
    if (!bundle.game?.bgg_id || !Array.isArray(bundle.chunks) || !bundle.chunks.length) {
      throw new Error("Missing required fields: game.bgg_id and chunks[]");
    }
    importPendingBundle = bundle;
    bundleEditCtx = {
      bundle: importPendingBundle,
      rerender: () => {
        preview.innerHTML = renderBundlePreview(importPendingBundle, true);
        if (window.lucide) window.lucide.createIcons();
        submit.disabled = !importPendingBundle.chunks.length;
      },
    };
    preview.innerHTML = renderBundlePreview(bundle, true);
    submit.disabled = false;
  } catch (err) {
    importPendingBundle = null;
    bundleEditCtx = null;
    preview.innerHTML = `<div class="alert alert-error text-sm"><i data-lucide="alert-circle" class="w-4 h-4"></i> ${escapeHtml(err.message)}</div>`;
    submit.disabled = true;
  }
  if (window.lucide) window.lucide.createIcons();
}

function renderBundlePreview(bundle, editable = false) {
  const missing = bundle.source?.missing || [];
  const chunks = (bundle.chunks || []).slice(0, 25);
  const chunkRows = chunks.map((c, i) => `
    <tr>
      <td class="text-xs">
        <span class="badge badge-sm badge-ghost">${escapeHtml(c.chunk_type || "?")}</span>
        ${c.expansion_name ? `<span class="badge badge-sm badge-secondary mt-0.5">expansion</span>` : ""}
      </td>
      <td class="text-sm leading-tight">
        ${escapeHtml(c.title || "(no title)")}
        ${c.expansion_name ? `<br><span class="text-xs opacity-60">${escapeHtml(c.expansion_name)}</span>` : ""}
      </td>
      <td class="text-xs text-base-content/60">${((c.content || "") + "").length} chars</td>
      ${editable ? `
      <td class="text-right">
        <button class="btn btn-ghost btn-xs" onclick="openChunkEditForm(${i})" title="Edit chunk">
          <i data-lucide="pencil" class="w-3 h-3"></i>
        </button>
        <button class="btn btn-ghost btn-xs text-error" onclick="deleteBundleChunk(${i})" title="Delete chunk">
          <i data-lucide="trash-2" class="w-3 h-3"></i>
        </button>
      </td>` : ""}
    </tr>
  `).join("");

  const emptyRow = editable && !chunks.length
    ? `<tr><td colspan="4" class="text-center text-xs text-base-content/50 py-3">All chunks removed — add at least one before importing.</td></tr>`
    : "";

  return `
    <div class="card bg-base-300 p-3 mt-2">
      <div class="flex items-center justify-between mb-2">
        <div>
          <div class="font-bold">${escapeHtml(bundle.game?.name || "Unknown")}</div>
          <div class="text-xs text-base-content/60">BGG #${escapeHtml(String(bundle.game?.bgg_id || ""))} · ${chunks.length} chunk${chunks.length === 1 ? "" : "s"}</div>
        </div>
        ${missing.length ? `<span class="badge badge-warning badge-sm">missing: ${missing.map(escapeHtml).join(", ")}</span>` : ""}
      </div>
      <div class="overflow-x-auto">
        <table class="table table-xs">
          <thead><tr><th>Type</th><th>Title</th><th>Size</th>${editable ? "<th></th>" : ""}</tr></thead>
          <tbody>${chunkRows}${emptyRow}</tbody>
        </table>
      </div>
    </div>
  `;
}

async function handleImportSubmit() {
  if (!importPendingBundle) return;
  const submit = document.getElementById("import-guide-submit");
  submit.disabled = true;
  submit.classList.add("loading");
  try {
    const result = await apiFetch("/guides/submit", {
      method: "POST",
      body: importPendingBundle,
    });
    showToast(result.message || "Submitted for review.", "success");
    importPendingBundle = null;
    bundleEditCtx = null;
    document.getElementById("import-guide-file").value = "";
    document.getElementById("import-guide-preview").innerHTML = "";
  } catch (err) {
    showToast("Upload failed: " + err.message, "error");
  } finally {
    submit.classList.remove("loading");
    submit.disabled = false;
  }
}

async function downloadGuideBuilderInstructions() {
  // The canonical skill file lives at .claude/commands/guide-from-rulebook.md in
  // the repo. Vercel serves static files from the project's web/ directory, so
  // copy the file into web/ at deploy time (see build.sh / GH Actions). We fetch
  // it here as plain text and trigger a download.
  try {
    const res = await fetch("/guide-from-rulebook.md");
    if (!res.ok) throw new Error("Instructions file not found (expected /guide-from-rulebook.md)");
    const text = await res.text();
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "guide-from-rulebook.md";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  } catch (err) {
    showToast("Download failed: " + err.message, "error");
  }
}

// ── Chunk edit / delete (shared by upload preview and admin review modal) ────

function deleteBundleChunk(index) {
  if (!bundleEditCtx) return;
  bundleEditCtx.bundle.chunks.splice(index, 1);
  bundleEditCtx.rerender();
}

async function openChunkEditForm(index) {
  if (!bundleEditCtx) return;
  const chunk = bundleEditCtx.bundle.chunks[index];
  if (!chunk) return;

  await openChunkEditorModal({
    existing: chunk,
    onSave: (data) => {
      Object.assign(bundleEditCtx.bundle.chunks[index], data);
      bundleEditCtx.rerender();
      showToast("Chunk updated", "success");
    },
  });
}

// ── Admin: pending review queue ──────────────────────────────────────────────

async function renderPendingGuides() {
  const container = document.getElementById("pending-guides-content");
  container.innerHTML = `
    <div class="flex items-center gap-2 mb-3">
      <button class="btn btn-ghost btn-sm btn-square" onclick="showView('import'); renderImport();" title="Back to Import">
        <i data-lucide="arrow-left" class="w-4 h-4"></i>
      </button>
      <h2 class="text-xl font-bold flex items-center gap-2">
        <i data-lucide="inbox" class="w-5 h-5"></i> Pending guide submissions
      </h2>
    </div>
    <div id="pending-guides-list"><div class="flex justify-center py-8"><span class="loading loading-spinner loading-md"></span></div></div>
  `;
  if (window.lucide) window.lucide.createIcons();

  try {
    pendingGuidesCache = await apiFetch("/guides/pending");
  } catch (err) {
    document.getElementById("pending-guides-list").innerHTML =
      `<div class="alert alert-error text-sm">${escapeHtml(err.message)}</div>`;
    return;
  }
  renderPendingGuidesList();
}

function renderPendingGuidesList() {
  const list = document.getElementById("pending-guides-list");
  if (!pendingGuidesCache.length) {
    list.innerHTML = `
      <div class="text-center py-12 text-base-content/50">
        <i data-lucide="inbox" class="w-12 h-12 mb-3 opacity-50"></i>
        <p>No submissions awaiting review.</p>
      </div>`;
    if (window.lucide) window.lucide.createIcons();
    return;
  }

  list.innerHTML = `
    <div class="space-y-2">
      ${pendingGuidesCache.map((p, i) => `
        <div class="card bg-base-200 animate-fadeUp" style="--i:${i}">
          <div class="card-body p-3">
            <div class="flex items-start justify-between gap-2">
              <div class="min-w-0">
                <h3 class="font-semibold text-sm">${escapeHtml(p.game_name)}</h3>
                <p class="text-xs text-base-content/60">
                  ${p.bgg_id ? `BGG #${p.bgg_id} · ` : ""}${p.chunk_count} chunk(s) ·
                  by ${escapeHtml(p.uploader_name || "unknown")} ·
                  ${formatDate(p.created_at)}
                </p>
              </div>
              <div class="flex gap-1 flex-shrink-0">
                <button class="btn btn-xs btn-ghost" onclick="viewPendingGuide('${p.id}')" title="View & edit">
                  <i data-lucide="eye" class="w-3 h-3"></i>
                </button>
                <button class="btn btn-xs btn-success" onclick="approvePendingGuide('${p.id}')" title="Approve as-is">
                  <i data-lucide="check" class="w-3 h-3"></i>
                </button>
                <button class="btn btn-xs btn-error btn-outline" onclick="rejectPendingGuide('${p.id}')" title="Reject">
                  <i data-lucide="x" class="w-3 h-3"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      `).join("")}
    </div>
  `;
  if (window.lucide) window.lucide.createIcons();
}

async function viewPendingGuide(id) {
  try {
    const detail = await apiFetch(`/guides/pending/${id}`);
    const reviewedBundle = JSON.parse(JSON.stringify(detail.bundle));

    const modal = document.createElement("div");
    modal.className = "fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4";
    modal.onclick = (e) => { if (e.target === modal) { modal.remove(); bundleEditCtx = null; } };

    function renderModalBody() {
      const hasChunks = reviewedBundle.chunks?.length > 0;
      return `
        <div class="card bg-base-100 max-w-lg w-full max-h-[85vh] overflow-y-auto">
          <div class="card-body p-4">
            <div class="flex items-center justify-between mb-2">
              <h3 class="font-bold">${escapeHtml(detail.game_name)}</h3>
              <button class="btn btn-ghost btn-sm btn-square" onclick="this.closest('.fixed').remove(); bundleEditCtx = null;">
                <i data-lucide="x" class="w-4 h-4"></i>
              </button>
            </div>
            ${renderBundlePreview(reviewedBundle, true)}
            <div class="flex gap-2 justify-end mt-3">
              <button class="btn btn-ghost btn-sm" onclick="this.closest('.fixed').remove(); bundleEditCtx = null;">
                Close
              </button>
              <button class="btn btn-error btn-outline btn-sm" onclick="rejectPendingGuide('${id}'); this.closest('.fixed').remove(); bundleEditCtx = null;">
                <i data-lucide="x" class="w-4 h-4"></i> Reject
              </button>
              <button class="btn btn-success btn-sm" ${hasChunks ? "" : "disabled"}
                onclick="approvePendingGuide('${id}', reviewedBundleFor_${id.replace(/-/g, "_")}); this.closest('.fixed').remove(); bundleEditCtx = null;">
                <i data-lucide="check" class="w-4 h-4"></i> Approve${hasChunks && reviewedBundle.chunks.length !== detail.bundle.chunks?.length ? ` (${reviewedBundle.chunks.length} chunks)` : ""}
              </button>
            </div>
          </div>
        </div>
      `;
    }

    // Expose the reviewedBundle so the inline onclick can reach it
    const safeId = id.replace(/-/g, "_");
    window[`reviewedBundleFor_${safeId}`] = reviewedBundle;

    bundleEditCtx = {
      bundle: reviewedBundle,
      rerender: () => {
        modal.innerHTML = renderModalBody();
        if (window.lucide) window.lucide.createIcons();
      },
    };

    modal.innerHTML = renderModalBody();
    document.body.appendChild(modal);
    if (window.lucide) window.lucide.createIcons();
  } catch (err) {
    showToast(err.message, "error");
  }
}

async function approvePendingGuide(id, overrideBundle = null) {
  if (!confirm("Approve and import this submission?")) return;
  try {
    const body = overrideBundle ? { override_bundle: overrideBundle } : {};
    const r = await apiFetch(`/guides/pending/${id}/approve`, { method: "POST", body });
    showToast(`Imported ${r.chunks_inserted} chunk(s).`, "success");
    pendingGuidesCache = pendingGuidesCache.filter(p => p.id !== id);
    renderPendingGuidesList();
    // Clean up window ref
    const safeId = id.replace(/-/g, "_");
    delete window[`reviewedBundleFor_${safeId}`];
  } catch (err) {
    showToast("Approve failed: " + err.message, "error");
  }
}

async function rejectPendingGuide(id) {
  const notes = prompt("Optional reason for rejection:") ?? null;
  try {
    await apiFetch(`/guides/pending/${id}/reject`, { method: "POST", body: { notes } });
    showToast("Submission rejected.", "info");
    pendingGuidesCache = pendingGuidesCache.filter(p => p.id !== id);
    renderPendingGuidesList();
  } catch (err) {
    showToast("Reject failed: " + err.message, "error");
  }
}
