// import.js — Import screen: BGG search, file upload, pending review, download skill.
//
// The file upload uses the authenticated user's Supabase JWT.
// All uploads — including admins — are queued in boardgamebuddy_pending_guides for review.

let importPendingBundle = null;
let importGameContext = null; // BggGameMetaResponse for the bundle's game, populated after file select
let pendingGuidesCache = [];
let bundleEditCtx = null; // { bundle, rerender: fn } — shared by upload and review contexts

function renderImport() {
  const container = document.getElementById("import-content");

  container.innerHTML = `
    <div class="flex items-center gap-2 mb-3">
      <button class="btn btn-ghost btn-sm btn-square" onclick="showView('browse')" title="Back to Browse">
        <i data-lucide="arrow-left" class="w-4 h-4"></i>
      </button>
      <h2 class="text-xl font-bold font-display flex items-center gap-2">
        <i data-lucide="download" class="w-5 h-5"></i> Import Games
      </h2>
    </div>
    <p class="text-sm text-base-content/60 mb-4">Add new games to BoardgameBuddy from BGG or from a generated guide bundle.</p>

    <!-- 1. Import from BoardGameGeek -->
    <div class="card bg-base-200 mb-3">
      <div class="card-body p-4">
        <h3 class="font-semibold flex items-center gap-2">
          <i data-lucide="globe" class="w-4 h-4"></i> Import from BoardGameGeek
        </h3>
        <p class="text-xs text-base-content/60">Search BGG and add games with their metadata.</p>
        <div class="flex gap-2 mt-2">
          <input type="text" id="bgg-search-input" class="input input-bordered input-sm flex-1" placeholder="Search BGG..." />
          <button class="btn btn-sm btn-primary" onclick="searchBGG()">Search</button>
        </div>
        <div id="bgg-results" class="mt-2"></div>
      </div>
    </div>

    <!-- 2. Import from file -->
    <div class="card bg-base-200 mb-3">
      <div class="card-body p-4">
        <h3 class="font-semibold flex items-center gap-2">
          <i data-lucide="upload" class="w-4 h-4"></i> Import from file
        </h3>
        <p class="text-xs text-base-content/60">
          Upload a GuideBundle JSON generated by the Guide Builder AI prompt.
          All uploads go through admin review before going live.
        </p>

        <input type="file" id="import-guide-file" accept="application/json,.json"
               class="file-input file-input-bordered file-input-sm w-full mt-2" />

        <div id="import-guide-preview" class="mt-2"></div>

        <div class="flex gap-2 mt-2">
          <button id="import-guide-submit" class="btn btn-primary btn-sm" disabled>
            <i data-lucide="upload" class="w-4 h-4"></i>
            Submit for review
          </button>
        </div>
      </div>
    </div>

    <!-- 3. Review pending additions (admin only) -->
    ${currentUser?.is_admin ? `
      <div class="card bg-base-200 mb-3">
        <div class="card-body p-4">
          <h3 class="font-semibold flex items-center gap-2">
            <i data-lucide="shield-check" class="w-4 h-4"></i> Review pending additions
          </h3>
          <p class="text-xs text-base-content/60">Approve or reject guide bundles submitted by any user.</p>
          <button class="btn btn-outline btn-sm mt-2" onclick="showView('pending-guides'); renderPendingGuides();">
            <i data-lucide="inbox" class="w-4 h-4"></i> Open review queue
          </button>
        </div>
      </div>
      <div class="card bg-base-200 mb-3">
        <div class="card-body p-4">
          <h3 class="font-semibold flex items-center gap-2">
            <i data-lucide="image-off" class="w-4 h-4"></i> Refresh missing images
          </h3>
          <p class="text-xs text-base-content/60">
            List games imported without BGG box art / thumbnail. Each refresh hits
            the BGG API — note the daily request limit.
          </p>
          <button class="btn btn-outline btn-sm mt-2"
                  onclick="showView('missing-images'); renderMissingImages();">
            <i data-lucide="image-off" class="w-4 h-4"></i> Open missing-images list
          </button>
        </div>
      </div>
    ` : ""}

    <!-- 4. Download Guide Builder instructions -->
    <div class="card bg-base-200 mb-3">
      <div class="card-body p-4">
        <h3 class="font-semibold flex items-center gap-2">
          <i data-lucide="file-down" class="w-4 h-4"></i> Download Guide Builder instructions
        </h3>
        <p class="text-xs text-base-content/60">
          Get the AI prompt that turns a rulebook into a BoardgameBuddy guide bundle.
          Feed the downloaded <code class="text-xs">.md</code> into your own AI with a game name, then upload the resulting JSON above.
        </p>
        <button class="btn btn-outline btn-sm mt-2" onclick="downloadGuideBuilderInstructions()">
          <i data-lucide="file-down" class="w-4 h-4"></i> Download .md
        </button>
      </div>
    </div>
  `;
  if (window.lucide) window.lucide.createIcons();

  importPendingBundle = null;
  importGameContext = null;
  bundleEditCtx = null;
  document.getElementById("import-guide-file").addEventListener("change", handleImportFileSelect);
  document.getElementById("import-guide-submit").addEventListener("click", handleImportSubmit);
}

// Render a header card distinguishing new-game-creation from chunk-add-to-existing.
// `meta` is a BggGameMetaResponse (already_in_db + bgg fields).
function renderGameContextHeader(meta) {
  if (!meta) return "";
  const name = escapeHtml(meta.name || "Unknown");
  if (meta.already_in_db) {
    return `
      <div class="alert alert-info text-sm py-2 mt-2">
        <i data-lucide="library" class="w-4 h-4"></i>
        <div>
          <span class="font-semibold">Adding chunks to existing game:</span>
          ${name}
        </div>
      </div>
    `;
  }
  const players = (meta.min_players || meta.max_players)
    ? `${meta.min_players ?? "?"}–${meta.max_players ?? "?"} players`
    : "";
  const time = meta.playing_time ? `${meta.playing_time} min` : "";
  const year = meta.year_published ? `(${meta.year_published})` : "";
  const meta_line = [players, time].filter(Boolean).join(" · ");
  const desc = (meta.description || "").replace(/&#10;/g, " ").trim();
  const descShort = desc.length > 240 ? desc.slice(0, 240) + "…" : desc;
  return `
    <div class="alert alert-warning text-sm py-2 mt-2">
      <i data-lucide="sparkles" class="w-4 h-4"></i>
      <div><span class="font-semibold">Creating new game</span> from this bundle.</div>
    </div>
    <div class="card bg-base-300 mt-2">
      <div class="card-body p-3 flex-row gap-3">
        ${meta.thumbnail_url ? `
          <img src="${escapeHtml(meta.thumbnail_url)}" alt=""
               class="w-20 h-20 rounded object-cover flex-shrink-0" />
        ` : `
          <div class="w-20 h-20 rounded bg-base-200 flex items-center justify-center flex-shrink-0">
            <i data-lucide="image" class="w-6 h-6 opacity-40"></i>
          </div>
        `}
        <div class="min-w-0">
          <div class="font-bold">${name} <span class="text-xs text-base-content/60">${year}</span></div>
          ${meta_line ? `<div class="text-xs text-base-content/60 mt-0.5">${meta_line}</div>` : ""}
          ${descShort ? `<div class="text-xs text-base-content/70 mt-1 line-clamp-3">${escapeHtml(descShort)}</div>` : ""}
        </div>
      </div>
    </div>
  `;
}

async function handleImportFileSelect(e) {
  const file = e.target.files?.[0];
  const preview = document.getElementById("import-guide-preview");
  const submit = document.getElementById("import-guide-submit");
  if (!file) {
    importPendingBundle = null;
    importGameContext = null;
    bundleEditCtx = null;
    preview.innerHTML = "";
    submit.disabled = true;
    return;
  }
  try {
    const text = await file.text();
    const bundle = JSON.parse(text);
    if (!bundle.game?.bgg_id || !Array.isArray(bundle.chunks) || !bundle.chunks.length) {
      throw new Error("Missing required fields: game.bgg_id and chunks[]");
    }
    importPendingBundle = bundle;
    importGameContext = null;
    const renderAll = () => {
      const ctxHeader = renderGameContextHeader(importGameContext);
      preview.innerHTML = ctxHeader + renderBundlePreview(importPendingBundle, true);
      if (window.lucide) window.lucide.createIcons();
      submit.disabled = !importPendingBundle.chunks.length;
    };
    bundleEditCtx = { bundle: importPendingBundle, rerender: renderAll };
    renderAll();
    submit.disabled = false;
    // Fetch BGG/DB context in the background — don't block the preview.
    apiFetch(`/games/bgg-preview/${bundle.game.bgg_id}`)
      .then((meta) => {
        importGameContext = meta;
        renderAll();
      })
      .catch((err) => {
        // Soft-fail: BGG quota or network — preview still works without the header.
        console.warn("BGG preview lookup failed:", err);
      });
  } catch (err) {
    importPendingBundle = null;
    importGameContext = null;
    bundleEditCtx = null;
    preview.innerHTML = `<div class="alert alert-error text-sm"><i data-lucide="alert-circle" class="w-4 h-4"></i> ${escapeHtml(err.message)}</div>`;
    submit.disabled = true;
  }
  if (window.lucide) window.lucide.createIcons();
}

function groupBundleChunksByType(chunks) {
  const seen = new Map();
  const groups = [];
  chunks.forEach((c, i) => {
    const key = c.chunk_type || "?";
    if (!seen.has(key)) {
      seen.set(key, groups.length);
      groups.push({ label: key, items: [] });
    }
    groups[seen.get(key)].items.push({ chunk: c, index: i });
  });
  return groups;
}

function renderBundlePreview(bundle, editable = false) {
  const missing = bundle.source?.missing || [];
  const chunks = (bundle.chunks || []).slice(0, 25);
  const cols = editable ? 3 : 2;

  const groups = groupBundleChunksByType(chunks);
  const chunkRows = groups.map(g => {
    const headerRow = `<tr><td colspan="${cols}" class="text-xs font-semibold text-base-content/50 uppercase tracking-wide pt-2 pb-0.5">${escapeHtml(g.label)}</td></tr>`;
    const dataRows = g.items.map(({ chunk: c, index: i }) => `
        <tr>
          <td class="text-sm leading-tight">${escapeHtml(c.title || "(no title)")}</td>
          <td class="text-xs text-base-content/60">${((c.content || "") + "").length} chars</td>
          ${editable ? `
          <td class="text-right">
            <button class="btn btn-ghost btn-xs" onclick="openChunkEditForm(${i})" title="Edit chunk">
              <i data-lucide="pencil" class="w-3 h-3"></i>
            </button>
            <button class="btn btn-ghost btn-xs text-error" onclick="deleteBundleChunk(${i})" title="Delete chunk">
              <i data-lucide="trash-2" class="w-3 h-3"></i>
            </button>
          </td>` : ""}
        </tr>`).join("");
    return headerRow + dataRows;
  }).join("");

  const emptyRow = editable && !chunks.length
    ? `<tr><td colspan="${cols}" class="text-center text-xs text-base-content/50 py-3">All chunks removed — add at least one before importing.</td></tr>`
    : "";

  return `
    <div class="card bg-base-300 p-3 mt-2">
      <div class="flex items-center justify-between mb-2">
        <div>
          <div class="font-bold">${escapeHtml(bundle.game?.name || "Unknown")}</div>
          <div class="text-xs text-base-content/60">BGG #${escapeHtml(String(bundle.game?.bgg_id || ""))} · ${chunks.length} chunk${chunks.length === 1 ? "" : "s"}</div>
        </div>
        ${missing.length ? `<span class="badge badge-warning badge-sm">missing: ${missing.map(escapeHtml).join(", ")}</span>` : ""}
      </div>
      <div class="overflow-x-auto">
        <table class="table table-xs">
          <thead><tr><th>Title</th><th>Size</th>${editable ? "<th></th>" : ""}</tr></thead>
          <tbody>${chunkRows}${emptyRow}</tbody>
        </table>
      </div>
    </div>
  `;
}

async function handleImportSubmit() {
  if (!importPendingBundle) return;
  const submit = document.getElementById("import-guide-submit");
  submit.disabled = true;
  submit.classList.add("loading");
  try {
    const result = await apiFetch("/guides/submit", {
      method: "POST",
      body: importPendingBundle,
    });
    showToast(result.message || "Submitted for review.", "success");
    importPendingBundle = null;
    importGameContext = null;
    bundleEditCtx = null;
    document.getElementById("import-guide-file").value = "";
    document.getElementById("import-guide-preview").innerHTML = "";
  } catch (err) {
    showToast("Upload failed: " + err.message, "error");
  } finally {
    submit.classList.remove("loading");
    submit.disabled = false;
  }
}

async function downloadGuideBuilderInstructions() {
  // The canonical skill file lives at .claude/commands/guide-from-rulebook.md in
  // the repo. Vercel serves static files from the project's web/ directory, so
  // copy the file into web/ at deploy time (see build.sh / GH Actions). We fetch
  // it here as plain text and trigger a download.
  try {
    const res = await fetch("/guide-from-rulebook.md");
    if (!res.ok) throw new Error("Instructions file not found (expected /guide-from-rulebook.md)");
    const text = await res.text();
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "guide-from-rulebook.md";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  } catch (err) {
    showToast("Download failed: " + err.message, "error");
  }
}

// ── Chunk edit / delete (shared by upload preview and admin review modal) ────

function deleteBundleChunk(index) {
  if (!bundleEditCtx) return;
  bundleEditCtx.bundle.chunks.splice(index, 1);
  bundleEditCtx.rerender();
}

async function openChunkEditForm(index) {
  if (!bundleEditCtx) return;
  const chunk = bundleEditCtx.bundle.chunks[index];
  if (!chunk) return;

  await openChunkEditorModal({
    existing: chunk,
    onSave: (data) => {
      Object.assign(bundleEditCtx.bundle.chunks[index], data);
      bundleEditCtx.rerender();
      showToast("Chunk updated", "success");
    },
  });
}

// ── Admin: pending review queue ──────────────────────────────────────────────

async function renderPendingGuides() {
  const container = document.getElementById("pending-guides-content");
  container.innerHTML = `
    <div class="flex items-center gap-2 mb-3">
      <button class="btn btn-ghost btn-sm btn-square" onclick="showView('import'); renderImport();" title="Back to Import">
        <i data-lucide="arrow-left" class="w-4 h-4"></i>
      </button>
      <h2 class="text-xl font-bold flex items-center gap-2">
        <i data-lucide="inbox" class="w-5 h-5"></i> Pending guide submissions
      </h2>
    </div>
    <div id="pending-guides-list"><div class="flex justify-center py-8"><span class="loading loading-spinner loading-md"></span></div></div>
  `;
  if (window.lucide) window.lucide.createIcons();

  try {
    pendingGuidesCache = await apiFetch("/guides/pending");
  } catch (err) {
    document.getElementById("pending-guides-list").innerHTML =
      `<div class="alert alert-error text-sm">${escapeHtml(err.message)}</div>`;
    return;
  }
  renderPendingGuidesList();
}

function renderPendingGuidesList() {
  const list = document.getElementById("pending-guides-list");
  if (!pendingGuidesCache.length) {
    list.innerHTML = `
      <div class="text-center py-12 text-base-content/50">
        <i data-lucide="inbox" class="w-12 h-12 mb-3 opacity-50"></i>
        <p>No submissions awaiting review.</p>
      </div>`;
    if (window.lucide) window.lucide.createIcons();
    return;
  }

  list.innerHTML = `
    <div class="space-y-2">
      ${pendingGuidesCache.map((p, i) => `
        <div class="card bg-base-200 animate-fadeUp" style="--i:${i}">
          <div class="card-body p-3">
            <div class="flex items-start justify-between gap-2">
              <div class="min-w-0">
                <div class="flex items-center gap-2 flex-wrap">
                  <h3 class="font-semibold text-sm">${escapeHtml(p.game_name)}</h3>
                  ${p.is_new_game
                    ? `<span class="badge badge-warning badge-sm">New game</span>`
                    : `<span class="badge badge-info badge-sm">Existing game</span>`}
                </div>
                <p class="text-xs text-base-content/60 mt-0.5">
                  ${p.bgg_id ? `BGG #${p.bgg_id} · ` : ""}${p.chunk_count} chunk(s) ·
                  by ${escapeHtml(p.uploader_name || "unknown")} ·
                  ${formatDate(p.created_at)}
                </p>
              </div>
              <div class="flex gap-1 flex-shrink-0">
                <button class="btn btn-xs btn-ghost" onclick="viewPendingGuide('${p.id}')" title="View & edit">
                  <i data-lucide="eye" class="w-3 h-3"></i>
                </button>
                <button class="btn btn-xs btn-error btn-outline" onclick="rejectPendingGuide('${p.id}')" title="Reject">
                  <i data-lucide="x" class="w-3 h-3"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      `).join("")}
    </div>
  `;
  if (window.lucide) window.lucide.createIcons();
}

// Local state for the open review modal — cleared when modal closes.
let pendingReviewState = null;
// { id, detail, defaultIds: Set<string>, bggMeta: BggGameMetaResponse|null, modalEl }

async function viewPendingGuide(id) {
  try {
    const detail = await apiFetch(`/guides/pending/${id}`);

    const modal = document.createElement("div");
    modal.className = "fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4";
    modal.onclick = (e) => { if (e.target === modal) closePendingReview(); };

    pendingReviewState = {
      id,
      detail,
      defaultIds: new Set(),
      bggMeta: null,
      modalEl: modal,
    };

    renderPendingReviewModal();
    document.body.appendChild(modal);

    if (detail.bgg_id) {
      apiFetch(`/games/bgg-preview/${detail.bgg_id}`)
        .then((meta) => {
          if (pendingReviewState && pendingReviewState.id === id) {
            pendingReviewState.bggMeta = meta;
            renderPendingReviewModal();
          }
        })
        .catch((err) => console.warn("BGG preview failed:", err));
    }
  } catch (err) {
    showToast(err.message, "error");
  }
}

function closePendingReview() {
  if (pendingReviewState?.modalEl) pendingReviewState.modalEl.remove();
  pendingReviewState = null;
}

function togglePendingChunkDefault(chunkId) {
  if (!pendingReviewState) return;
  const set = pendingReviewState.defaultIds;
  if (set.has(chunkId)) set.delete(chunkId);
  else set.add(chunkId);
  renderPendingReviewModal();
}

function togglePendingSelectAll() {
  if (!pendingReviewState) return;
  const chunks = pendingReviewState.detail.chunks || [];
  const allSelected = chunks.length > 0 && chunks.every((c) => pendingReviewState.defaultIds.has(c.id));
  if (allSelected) pendingReviewState.defaultIds.clear();
  else chunks.forEach((c) => pendingReviewState.defaultIds.add(c.id));
  renderPendingReviewModal();
}

function renderPendingReviewModal() {
  if (!pendingReviewState) return;
  const { detail, defaultIds, bggMeta, modalEl } = pendingReviewState;
  const chunks = detail.chunks || [];
  const allSelected = chunks.length > 0 && chunks.every((c) => defaultIds.has(c.id));

  const groups = new Map();
  chunks.forEach((c) => {
    const key = c.chunk_type_label || c.chunk_type || "?";
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(c);
  });

  const chunkRows = Array.from(groups.entries()).map(([label, items]) => `
    <tr><td colspan="4" class="text-xs font-semibold text-base-content/50 uppercase tracking-wide pt-2 pb-0.5">
      ${escapeHtml(label)}
    </td></tr>
    ${items.map((c) => `
      <tr>
        <td class="w-6">
          <input type="checkbox" class="checkbox checkbox-xs"
                 ${defaultIds.has(c.id) ? "checked" : ""}
                 onchange="togglePendingChunkDefault('${c.id}')"
                 title="Add to default guide" />
        </td>
        <td class="text-sm leading-tight">${escapeHtml(c.title || "(no title)")}</td>
        <td class="text-xs text-base-content/60">${(c.content || "").length} chars</td>
        <td class="text-right">
          <button class="btn btn-ghost btn-xs" onclick="editPendingChunk('${c.id}')" title="Edit chunk">
            <i data-lucide="pencil" class="w-3 h-3"></i>
          </button>
          <button class="btn btn-ghost btn-xs text-error" onclick="deletePendingChunk('${c.id}')" title="Delete chunk">
            <i data-lucide="trash-2" class="w-3 h-3"></i>
          </button>
        </td>
      </tr>
    `).join("")}
  `).join("");

  const isNewGame = detail.is_new_game;
  const headerCard = bggMeta
    ? renderGameContextHeader(bggMeta)
    : `<div class="alert ${isNewGame ? "alert-warning" : "alert-info"} text-sm py-2 mt-2">
        <i data-lucide="${isNewGame ? "sparkles" : "library"}" class="w-4 h-4"></i>
        <div>
          <span class="font-semibold">${isNewGame ? "Creating new game:" : "Adding chunks to existing game:"}</span>
          ${escapeHtml(detail.game_name)}
        </div>
      </div>`;

  modalEl.innerHTML = `
    <div class="card bg-base-100 max-w-lg w-full max-h-[85vh] overflow-y-auto">
      <div class="card-body p-4">
        <div class="flex items-center justify-between mb-2">
          <div>
            <h3 class="font-bold">${escapeHtml(detail.game_name)}</h3>
            <p class="text-xs text-base-content/60">
              by ${escapeHtml(detail.uploader_name || "unknown")} · ${formatDate(detail.created_at)}
            </p>
          </div>
          <button class="btn btn-ghost btn-sm btn-square" onclick="closePendingReview()">
            <i data-lucide="x" class="w-4 h-4"></i>
          </button>
        </div>
        ${headerCard}
        <div class="flex items-center justify-between mt-3 mb-1">
          <span class="text-xs font-semibold text-base-content/70">
            ${chunks.length} chunk(s) · ${defaultIds.size} marked as default
          </span>
          <button class="btn btn-ghost btn-xs" onclick="togglePendingSelectAll()" ${chunks.length ? "" : "disabled"}>
            <i data-lucide="${allSelected ? "square" : "check-square"}" class="w-3 h-3"></i>
            ${allSelected ? "Clear all" : "Select all as default"}
          </button>
        </div>
        <div class="overflow-x-auto">
          <table class="table table-xs">
            <thead><tr><th></th><th>Title</th><th>Size</th><th></th></tr></thead>
            <tbody>${chunkRows || `<tr><td colspan="4" class="text-center text-xs text-base-content/50 py-3">No chunks left.</td></tr>`}</tbody>
          </table>
        </div>
        <div class="flex gap-2 justify-end mt-3">
          <button class="btn btn-ghost btn-sm" onclick="closePendingReview()">Close</button>
          <button class="btn btn-error btn-outline btn-sm" onclick="rejectPendingGuide('${detail.id}'); closePendingReview();">
            <i data-lucide="x" class="w-4 h-4"></i> Reject
          </button>
          <button class="btn btn-success btn-sm" ${chunks.length ? "" : "disabled"}
            onclick="approvePendingGuide('${detail.id}')">
            <i data-lucide="check" class="w-4 h-4"></i>
            Approve${defaultIds.size ? ` (${defaultIds.size} default)` : ""}
          </button>
        </div>
      </div>
    </div>
  `;
  if (window.lucide) window.lucide.createIcons();
}

async function editPendingChunk(chunkId) {
  if (!pendingReviewState) return;
  const chunk = pendingReviewState.detail.chunks.find((c) => c.id === chunkId);
  if (!chunk) return;
  await openChunkEditorModal({
    existing: chunk,
    onSave: async (data) => {
      try {
        const updated = await apiFetch(`/chunks/${chunkId}`, {
          method: "PATCH",
          body: data,
        });
        const idx = pendingReviewState.detail.chunks.findIndex((c) => c.id === chunkId);
        if (idx >= 0) pendingReviewState.detail.chunks[idx] = updated;
        renderPendingReviewModal();
        showToast("Chunk updated", "success");
      } catch (err) {
        showToast("Update failed: " + err.message, "error");
      }
    },
  });
}

async function deletePendingChunk(chunkId) {
  if (!pendingReviewState) return;
  if (!confirm("Delete this chunk?")) return;
  try {
    await apiFetch(`/chunks/${chunkId}`, { method: "DELETE" });
    pendingReviewState.detail.chunks = pendingReviewState.detail.chunks.filter((c) => c.id !== chunkId);
    pendingReviewState.defaultIds.delete(chunkId);
    renderPendingReviewModal();
  } catch (err) {
    showToast("Delete failed: " + err.message, "error");
  }
}

async function approvePendingGuide(id) {
  const state = pendingReviewState && pendingReviewState.id === id ? pendingReviewState : null;
  const defaultChunkIds = state ? Array.from(state.defaultIds) : [];
  const chunkCount = state ? (state.detail.chunks?.length || 0) : null;
  const summary = chunkCount !== null
    ? `Approve ${chunkCount} chunk(s)? ${defaultChunkIds.length} will be added to the default guide.`
    : "Approve and import this submission?";
  if (!confirm(summary)) return;
  try {
    const r = await apiFetch(`/guides/pending/${id}/approve`, {
      method: "POST",
      body: { default_chunk_ids: defaultChunkIds },
    });
    showToast(`Approved ${r.chunks_inserted} chunk(s).`, "success");
    pendingGuidesCache = pendingGuidesCache.filter((p) => p.id !== id);
    renderPendingGuidesList();
    closePendingReview();
  } catch (err) {
    showToast("Approve failed: " + err.message, "error");
  }
}

async function rejectPendingGuide(id) {
  const notes = prompt("Optional reason for rejection:") ?? null;
  try {
    await apiFetch(`/guides/pending/${id}/reject`, { method: "POST", body: { notes } });
    showToast("Submission rejected.", "info");
    pendingGuidesCache = pendingGuidesCache.filter(p => p.id !== id);
    renderPendingGuidesList();
  } catch (err) {
    showToast("Reject failed: " + err.message, "error");
  }
}

// ── Admin: refresh missing images ────────────────────────────────────────────

let missingImagesCache = [];
let missingImagesBusy = false;

async function renderMissingImages() {
  const container = document.getElementById("missing-images-content");
  container.innerHTML = `
    <div class="flex items-center gap-2 mb-3">
      <button class="btn btn-ghost btn-sm btn-square" onclick="showView('import'); renderImport();" title="Back to Import">
        <i data-lucide="arrow-left" class="w-4 h-4"></i>
      </button>
      <h2 class="text-xl font-bold flex items-center gap-2">
        <i data-lucide="image-off" class="w-5 h-5"></i> Missing images
      </h2>
    </div>
    <p class="text-xs text-base-content/60 mb-3">
      Each refresh hits the BoardGameGeek API. BGG enforces a daily request quota — refresh in moderation.
    </p>
    <div id="missing-images-list">
      <div class="flex justify-center py-8"><span class="loading loading-spinner loading-md"></span></div>
    </div>
  `;
  if (window.lucide) window.lucide.createIcons();

  try {
    missingImagesCache = await apiFetch("/games/admin/missing-images");
  } catch (err) {
    document.getElementById("missing-images-list").innerHTML =
      `<div class="alert alert-error text-sm">${escapeHtml(err.message)}</div>`;
    return;
  }
  renderMissingImagesList();
}

function renderMissingImagesList() {
  const list = document.getElementById("missing-images-list");
  if (!missingImagesCache.length) {
    list.innerHTML = `
      <div class="text-center py-12 text-base-content/50">
        <i data-lucide="check-circle-2" class="w-12 h-12 mb-3 opacity-50"></i>
        <p>All games have box art and thumbnails.</p>
      </div>`;
    if (window.lucide) window.lucide.createIcons();
    return;
  }

  list.innerHTML = `
    <div class="flex items-center justify-between mb-3">
      <span class="text-sm text-base-content/70">
        ${missingImagesCache.length} game${missingImagesCache.length === 1 ? "" : "s"} need refresh
      </span>
      <button class="btn btn-primary btn-sm" id="refresh-all-btn"
              onclick="refreshAllMissingImages()" ${missingImagesBusy ? "disabled" : ""}>
        <i data-lucide="refresh-cw" class="w-4 h-4"></i>
        Refresh all (sequential)
      </button>
    </div>
    <div id="refresh-progress" class="text-xs text-base-content/60 mb-2 ${missingImagesBusy ? "" : "hidden"}"></div>
    <div class="space-y-2">
      ${missingImagesCache.map((g, i) => `
        <div class="card bg-base-200 animate-fadeUp" style="--i:${i}" data-game-row="${g.id}">
          <div class="card-body p-3 flex-row items-center gap-3">
            <div class="w-12 h-12 rounded bg-base-300 flex items-center justify-center flex-shrink-0">
              ${g.thumbnail_url
                ? `<img src="${bggImg(g.thumbnail_url)}" alt="" class="w-full h-full object-cover rounded" />`
                : `<i data-lucide="image-off" class="w-5 h-5 opacity-40"></i>`}
            </div>
            <div class="min-w-0 flex-1">
              <h3 class="font-semibold text-sm truncate">${escapeHtml(g.name)}</h3>
              <p class="text-xs text-base-content/60">
                ${g.bgg_id ? `BGG #${g.bgg_id}` : "no bgg_id"}
                ${!g.image_url ? " · missing image" : ""}
                ${!g.thumbnail_url ? " · missing thumbnail" : ""}
              </p>
            </div>
            <button class="btn btn-xs btn-outline" onclick="refreshOneGameImages('${g.id}')"
                    ${g.bgg_id ? "" : "disabled"} ${missingImagesBusy ? "disabled" : ""}>
              <i data-lucide="refresh-cw" class="w-3 h-3"></i> Refresh
            </button>
          </div>
        </div>
      `).join("")}
    </div>
  `;
  if (window.lucide) window.lucide.createIcons();
}

async function refreshOneGameImages(gameId) {
  try {
    const refreshed = await apiFetch(`/games/admin/${gameId}/refresh-images`, { method: "POST" });
    if (refreshed.image_url && refreshed.thumbnail_url) {
      missingImagesCache = missingImagesCache.filter(g => g.id !== gameId);
      showToast(`${refreshed.name} refreshed.`, "success");
    } else {
      const idx = missingImagesCache.findIndex(g => g.id === gameId);
      if (idx >= 0) missingImagesCache[idx] = refreshed;
      showToast(`${refreshed.name}: still missing one URL.`, "info");
    }
    renderMissingImagesList();
  } catch (err) {
    showToast("Refresh failed: " + err.message, "error");
  }
}

async function refreshAllMissingImages() {
  if (missingImagesBusy) return;
  if (!confirm(`Refresh ${missingImagesCache.length} game(s) sequentially? This will use BGG API quota.`)) return;
  missingImagesBusy = true;
  renderMissingImagesList();
  const progress = document.getElementById("refresh-progress");
  let done = 0, failed = 0;
  const total = missingImagesCache.length;
  // Snapshot of ids at start — refreshOneGameImages mutates the cache.
  const ids = missingImagesCache.filter(g => g.bgg_id).map(g => g.id);
  for (const id of ids) {
    if (progress) progress.textContent = `Refreshing ${done + 1} / ${total}…`;
    try {
      const refreshed = await apiFetch(`/games/admin/${id}/refresh-images`, { method: "POST" });
      if (refreshed.image_url && refreshed.thumbnail_url) {
        missingImagesCache = missingImagesCache.filter(g => g.id !== id);
      } else {
        const idx = missingImagesCache.findIndex(g => g.id === id);
        if (idx >= 0) missingImagesCache[idx] = refreshed;
      }
    } catch {
      failed += 1;
    }
    done += 1;
  }
  missingImagesBusy = false;
  showToast(`Refreshed ${done - failed}/${total}${failed ? ` (${failed} failed)` : ""}.`, failed ? "warning" : "success");
  renderMissingImagesList();
}
