-- ─────────────────────────────────────────────────────────────────────────────
-- BoardgameBuddy — current schema snapshot
-- Last updated: the 2026-09-01 migration collapse. Generated by loading
--               db/migrations/boardgamebuddy/001_baseline.sql into an empty
--               database and reading the result back, so it is exact rather
--               than maintained by hand — which is how the previous snapshot
--               drifted (it stopped reflecting migrations 047-059).
-- FOR REFERENCE ONLY — apply changes via db/migrations/
--
-- To regenerate after a new migration: apply 001 plus every later migration to
-- a scratch database and re-dump, rather than editing this file by hand.
--
-- Note: boardgamebuddy_buddies is strictly free-text ghost-player nicknames.
-- Mutual friendship lives in boardgamebuddy_buddy_edges, and play_players
-- references real profiles directly (player_user_id / player_display_name).
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Games catalog ─────────────────────────────────────────────────────────────
-- Every game the app knows, base games and expansions in one table.
-- is_expansion flags the row and base_game_bgg_id points at the parent as a
-- soft reference, not an FK, so an expansion can be imported before its base
-- game exists. play_mode is derived from BGG mechanics at import time and
-- decides whether the session UI shows per-player scores, one shared
-- win/lose toggle, or a team picker.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_games (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  bgg_id INTEGER,
  name TEXT NOT NULL,
  year_published INTEGER,
  min_players INTEGER,
  max_players INTEGER,
  playing_time INTEGER,
  description TEXT,
  image_url TEXT,
  thumbnail_url TEXT,
  categories TEXT[] DEFAULT '{}'::text[],
  mechanics TEXT[] DEFAULT '{}'::text[],
  theme_color TEXT,
  is_expansion BOOLEAN DEFAULT false NOT NULL,
  base_game_bgg_id INTEGER,
  expansion_color TEXT,
  rulebook_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  play_mode TEXT DEFAULT 'competitive'::text NOT NULL,
  CONSTRAINT boardgamebuddy_games_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_games_bgg_id_key UNIQUE (bgg_id),
  CONSTRAINT boardgamebuddy_games_play_mode_check CHECK ((play_mode = ANY (ARRAY['competitive'::text, 'coop'::text, 'team'::text])))
);
ALTER TABLE public.boardgamebuddy_games ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_games_base_bgg ON public.boardgamebuddy_games USING btree (base_game_bgg_id) WHERE (is_expansion = true);
CREATE INDEX IF NOT EXISTS idx_bgb_games_browse ON public.boardgamebuddy_games USING btree (created_at DESC, id DESC) WHERE (is_expansion = false);
CREATE INDEX IF NOT EXISTS idx_bgb_games_browse_alpha ON public.boardgamebuddy_games USING btree (name, id DESC) WHERE (is_expansion = false);
CREATE INDEX IF NOT EXISTS idx_bgb_games_name_trgm ON public.boardgamebuddy_games USING gin (name extensions.gin_trgm_ops);
GRANT SELECT ON public.boardgamebuddy_games TO boardgamebuddy_role;


-- ── Profiles ──────────────────────────────────────────────────────────────────
-- One row per account, keyed to auth.users so a deleted auth user cascades.
-- The two bgg_last_*_started_at stamps are what the sync and push status RPCs
-- count progress from; needs_setup drives the first-run onboarding deck.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_profiles (
  id UUID NOT NULL,
  display_name TEXT NOT NULL,
  is_admin BOOLEAN DEFAULT false NOT NULL,
  bgg_username TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  bgg_password_enc TEXT,
  bgg_session_id TEXT,
  bgg_session_expires_at TIMESTAMPTZ,
  bgg_session_user_cookie TEXT,
  bgg_session_pass_cookie TEXT,
  bgg_last_login_at TIMESTAMPTZ,
  username TEXT NOT NULL,
  bgg_last_sync_started_at TIMESTAMPTZ,
  avatar JSONB,
  needs_setup BOOLEAN DEFAULT true NOT NULL,
  app_installed_at TIMESTAMPTZ,
  bgg_last_push_started_at TIMESTAMPTZ,
  bgg_last_check_started_at TIMESTAMPTZ,
  link_notifications_seen_at TIMESTAMPTZ,
  CONSTRAINT boardgamebuddy_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT bgb_profiles_username_format CHECK ((username ~ '^[a-z0-9_]{3,30}$'::text))
);
ALTER TABLE public.boardgamebuddy_profiles ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS bgb_profiles_username_uk ON public.boardgamebuddy_profiles USING btree (username);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_profiles_bgg_username ON public.boardgamebuddy_profiles USING btree (bgg_username) WHERE (bgg_username IS NOT NULL);
GRANT SELECT ON public.boardgamebuddy_profiles TO boardgamebuddy_role;


-- ── Chapter types ─────────────────────────────────────────────────────────────
-- Fixed vocabulary for guide chapters. Seeded in 002_seed.sql.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_chapter_types (
  id TEXT NOT NULL,
  label TEXT NOT NULL,
  icon TEXT,
  display_order INTEGER DEFAULT 0,
  CONSTRAINT boardgamebuddy_chunk_types_pkey PRIMARY KEY (id)
);
ALTER TABLE public.boardgamebuddy_chapter_types ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.boardgamebuddy_chapter_types TO boardgamebuddy_role;


-- ── Achievement groups ────────────────────────────────────────────────────────
-- The sections the achievements screen renders. Seeded in 002_seed.sql.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_achievement_groups (
  id TEXT NOT NULL,
  label TEXT NOT NULL,
  blurb TEXT NOT NULL,
  display_order INTEGER NOT NULL,
  CONSTRAINT boardgamebuddy_achievement_groups_pkey PRIMARY KEY (id)
);
ALTER TABLE public.boardgamebuddy_achievement_groups ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.boardgamebuddy_achievement_groups TO boardgamebuddy_role;


-- ── Achievement catalog ───────────────────────────────────────────────────────
-- metric names a counter bgb_sync_achievements computes, threshold the value
-- that unlocks the row — so a new achievement over an existing metric is a
-- seed change, not a code change. Seeded in 002_seed.sql.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_achievements (
  id TEXT NOT NULL,
  group_id TEXT NOT NULL,
  name TEXT NOT NULL,
  tagline TEXT NOT NULL,
  requirement TEXT NOT NULL,
  metric TEXT NOT NULL,
  threshold INTEGER NOT NULL,
  icon TEXT NOT NULL,
  display_order INTEGER NOT NULL,
  CONSTRAINT boardgamebuddy_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_achievements_group_id_fkey FOREIGN KEY (group_id) REFERENCES boardgamebuddy_achievement_groups(id),
  CONSTRAINT bgb_achievements_metric_chk CHECK ((metric = ANY (ARRAY['plays_logged'::text, 'wins'::text, 'biggest_table'::text, 'two_player_games'::text, 'buddies'::text, 'guide_chapters'::text, 'chapters_borrowed'::text, 'plays_with_notes'::text, 'bgg_linked'::text, 'app_installed'::text, 'countries'::text, 'continents'::text]))),
  CONSTRAINT boardgamebuddy_achievements_threshold_check CHECK ((threshold > 0))
);
ALTER TABLE public.boardgamebuddy_achievements ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_achievements_order ON public.boardgamebuddy_achievements USING btree (display_order);
GRANT SELECT ON public.boardgamebuddy_achievements TO boardgamebuddy_role;


-- ── Country → continent lookup ────────────────────────────────────────────────
-- Backs the location achievements. Seeded in 002_seed.sql.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_countries (
  code TEXT NOT NULL,
  continent TEXT NOT NULL,
  CONSTRAINT boardgamebuddy_countries_pkey PRIMARY KEY (code),
  CONSTRAINT boardgamebuddy_countries_code_check CHECK ((code ~ '^[A-Z]{2}$'::text)),
  CONSTRAINT boardgamebuddy_countries_continent_check CHECK ((continent = ANY (ARRAY['AF'::text, 'AN'::text, 'AS'::text, 'EU'::text, 'NA'::text, 'OC'::text, 'SA'::text])))
);
ALTER TABLE public.boardgamebuddy_countries ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.boardgamebuddy_countries TO boardgamebuddy_role;


-- ── Guide chapters ────────────────────────────────────────────────────────────
-- User-authored rules chapters. Called 'chunks' until archive/018 renamed
-- the three chapter tables; that migration also deleted every seeded chapter,
-- so this table starts empty on a fresh database.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_guide_chapters (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  game_id UUID NOT NULL,
  chapter_type TEXT NOT NULL,
  title TEXT NOT NULL,
  created_by UUID,
  layout TEXT DEFAULT 'text'::text NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT boardgamebuddy_guide_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_guide_chunks_chunk_type_fkey FOREIGN KEY (chapter_type) REFERENCES boardgamebuddy_chapter_types(id),
  CONSTRAINT boardgamebuddy_guide_chunks_created_by_fkey FOREIGN KEY (created_by) REFERENCES boardgamebuddy_profiles(id) ON DELETE SET NULL,
  CONSTRAINT boardgamebuddy_guide_chunks_game_id_fkey FOREIGN KEY (game_id) REFERENCES boardgamebuddy_games(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_guide_chunks_layout_check CHECK ((layout = 'text'::text))
);
ALTER TABLE public.boardgamebuddy_guide_chapters ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_chapters_game_type ON public.boardgamebuddy_guide_chapters USING btree (game_id, chapter_type);
GRANT SELECT ON public.boardgamebuddy_guide_chapters TO boardgamebuddy_role;


-- ── Chapter reports ───────────────────────────────────────────────────────────
-- Moderation queue: a reader flagging someone else's chapter.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_chapter_reports (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  chapter_id UUID NOT NULL,
  reporter_id UUID NOT NULL,
  reason TEXT,
  status TEXT DEFAULT 'open'::text NOT NULL,
  resolved_by UUID,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT boardgamebuddy_chapter_reports_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_chapter_reports_chapter_id_reporter_id_key UNIQUE (chapter_id, reporter_id),
  CONSTRAINT boardgamebuddy_chapter_reports_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES boardgamebuddy_guide_chapters(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_chapter_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_chapter_reports_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES boardgamebuddy_profiles(id) ON DELETE SET NULL,
  CONSTRAINT boardgamebuddy_chapter_reports_status_check CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text])))
);
ALTER TABLE public.boardgamebuddy_chapter_reports ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_chapter_reports_status ON public.boardgamebuddy_chapter_reports USING btree (status, created_at);
GRANT SELECT ON public.boardgamebuddy_chapter_reports TO boardgamebuddy_role;


-- ── Per-user chapter selections ───────────────────────────────────────────────
-- Which chapters a user keeps, hides or reorders for a given game.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_user_chapters (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  user_id UUID NOT NULL,
  game_id UUID NOT NULL,
  chapter_id UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT boardgamebuddy_guide_selections_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_guide_selections_user_id_chunk_id_key UNIQUE (user_id, chapter_id),
  CONSTRAINT boardgamebuddy_guide_selections_chunk_id_fkey FOREIGN KEY (chapter_id) REFERENCES boardgamebuddy_guide_chapters(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_guide_selections_game_id_fkey FOREIGN KEY (game_id) REFERENCES boardgamebuddy_games(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_guide_selections_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE
);
ALTER TABLE public.boardgamebuddy_user_chapters ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_user_chapters_chapter ON public.boardgamebuddy_user_chapters USING btree (chapter_id);
CREATE INDEX IF NOT EXISTS idx_bgb_user_chapters_user_game ON public.boardgamebuddy_user_chapters USING btree (user_id, game_id);
GRANT SELECT ON public.boardgamebuddy_user_chapters TO boardgamebuddy_role;


-- ── Collections ───────────────────────────────────────────────────────────────
-- The shelf: one row per user per game, with the shelf status. 'played' is a
-- legacy status the app no longer writes — the Played shelf is derived from
-- boardgamebuddy_plays. The CHECK still admits it so old rows stay valid.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_collections (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  user_id UUID NOT NULL,
  game_id UUID NOT NULL,
  status TEXT NOT NULL,
  added_at TIMESTAMPTZ DEFAULT now(),
  bgg_private_comment TEXT,
  bgg_acquired_from TEXT,
  bgg_acquisition_date DATE,
  bgg_purchase_price NUMERIC(10,2),
  bgg_purchase_currency TEXT,
  bgg_inventory_location TEXT,
  bgg_quantity INTEGER,
  game_name TEXT NOT NULL,
  game_thumbnail_url TEXT,
  game_year_published INTEGER,
  game_min_players SMALLINT,
  game_max_players SMALLINT,
  game_playing_time SMALLINT,
  game_is_expansion BOOLEAN,
  game_base_game_bgg_id INTEGER,
  game_expansion_color TEXT,
  game_play_mode TEXT,
  game_bgg_id INTEGER,
  game_theme_color TEXT,
  played_before_at TIMESTAMPTZ,
  CONSTRAINT boardgamebuddy_collections_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_collections_user_id_game_id_key UNIQUE (user_id, game_id),
  CONSTRAINT boardgamebuddy_collections_game_id_fkey FOREIGN KEY (game_id) REFERENCES boardgamebuddy_games(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_collections_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_collections_status_check CHECK ((status = ANY (ARRAY['owned'::text, 'wishlist'::text, 'prev_owned'::text])))
);
ALTER TABLE public.boardgamebuddy_collections ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_collections_game_user ON public.boardgamebuddy_collections USING btree (game_id, user_id);
CREATE INDEX IF NOT EXISTS idx_bgb_collections_user_status ON public.boardgamebuddy_collections USING btree (user_id, status, added_at DESC);
CREATE INDEX IF NOT EXISTS idx_bgb_collections_user_status_name ON public.boardgamebuddy_collections USING btree (user_id, status, game_name);
GRANT SELECT ON public.boardgamebuddy_collections TO boardgamebuddy_role;


-- ── Owned expansions ──────────────────────────────────────────────────────────
-- Expansions a user owns, kept apart from collections so the shelf counts
-- base games and expansions separately.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_user_expansions (
  user_id UUID NOT NULL,
  expansion_game_id UUID NOT NULL,
  CONSTRAINT boardgamebuddy_user_expansions_pkey PRIMARY KEY (user_id, expansion_game_id),
  CONSTRAINT boardgamebuddy_user_expansions_expansion_game_id_fkey FOREIGN KEY (expansion_game_id) REFERENCES boardgamebuddy_games(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_user_expansions_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE
);
ALTER TABLE public.boardgamebuddy_user_expansions ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.boardgamebuddy_user_expansions TO boardgamebuddy_role;


-- ── Ghost buddies ─────────────────────────────────────────────────────────────
-- Free-text player nicknames only — someone you played with who has no
-- account. Real mutual friendship lives in boardgamebuddy_buddy_edges.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_buddies (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  owner_id UUID NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT boardgamebuddy_buddies_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_buddies_owner_id_name_key UNIQUE (owner_id, name),
  CONSTRAINT boardgamebuddy_buddies_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE
);
ALTER TABLE public.boardgamebuddy_buddies ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.boardgamebuddy_buddies TO boardgamebuddy_role;


-- ── Buddy edges ───────────────────────────────────────────────────────────────
-- Directed rows; a mutual friendship is two of them. status carries the
-- request lifecycle, and a request you have merely SENT already counts as a
-- first-hop link for the suggestion RPCs (archive/072).
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_buddy_edges (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  user_a UUID NOT NULL,
  user_b UUID NOT NULL,
  status TEXT NOT NULL,
  requested_by UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  accepted_at TIMESTAMPTZ,
  CONSTRAINT boardgamebuddy_buddy_edges_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_buddy_edges_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_buddy_edges_user_a_fkey FOREIGN KEY (user_a) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_buddy_edges_user_b_fkey FOREIGN KEY (user_b) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT bgb_buddy_edges_canonical CHECK ((user_a < user_b)),
  CONSTRAINT boardgamebuddy_buddy_edges_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'blocked'::text])))
);
ALTER TABLE public.boardgamebuddy_buddy_edges ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_buddy_edges_pair ON public.boardgamebuddy_buddy_edges USING btree (user_a, user_b);
CREATE INDEX IF NOT EXISTS idx_bgb_buddy_edges_user_a ON public.boardgamebuddy_buddy_edges USING btree (user_a, status);
CREATE INDEX IF NOT EXISTS idx_bgb_buddy_edges_user_b ON public.boardgamebuddy_buddy_edges USING btree (user_b, status);
GRANT SELECT ON public.boardgamebuddy_buddy_edges TO boardgamebuddy_role;


-- ── Ghost claims ──────────────────────────────────────────────────────────────
-- "That ghost player is me" — a claimant asking the ghost's owner to merge
-- those rows onto their account.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_ghost_claims (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  owner_id UUID NOT NULL,
  ghost_name_key TEXT NOT NULL,
  ghost_display_name TEXT NOT NULL,
  claimant_id UUID NOT NULL,
  status TEXT NOT NULL,
  rows_merged INTEGER,
  reject_count INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  resolved_at TIMESTAMPTZ,
  CONSTRAINT boardgamebuddy_ghost_claims_pkey PRIMARY KEY (id),
  CONSTRAINT uq_bgb_ghost_claims_triple UNIQUE (owner_id, ghost_name_key, claimant_id),
  CONSTRAINT boardgamebuddy_ghost_claims_claimant_id_fkey FOREIGN KEY (claimant_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_ghost_claims_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT bgb_ghost_claims_key_normalized CHECK (((ghost_name_key = lower(btrim(ghost_name_key))) AND (ghost_name_key <> ''::text))),
  CONSTRAINT bgb_ghost_claims_not_self CHECK ((owner_id <> claimant_id)),
  CONSTRAINT boardgamebuddy_ghost_claims_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'dismissed'::text, 'superseded'::text])))
);
ALTER TABLE public.boardgamebuddy_ghost_claims ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_ghost_claims_claimant ON public.boardgamebuddy_ghost_claims USING btree (claimant_id, status);
CREATE INDEX IF NOT EXISTS idx_bgb_ghost_claims_owner_pending ON public.boardgamebuddy_ghost_claims USING btree (owner_id) WHERE (status = 'pending'::text);
GRANT SELECT ON public.boardgamebuddy_ghost_claims TO boardgamebuddy_role;


-- ── Plays ─────────────────────────────────────────────────────────────────────
-- One logged play. Game name/thumbnail are denormalized onto the row so the
-- feed doesn't join the catalog. client_key makes a retried log idempotent;
-- country_code feeds the location achievements.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_plays (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  user_id UUID NOT NULL,
  game_id UUID NOT NULL,
  played_at DATE DEFAULT CURRENT_DATE NOT NULL,
  notes TEXT,
  bgg_play_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT now(),
  photo_url TEXT,
  play_mode TEXT DEFAULT 'competitive'::text NOT NULL,
  game_name TEXT NOT NULL,
  game_thumbnail_url TEXT,
  client_key UUID,
  country_code TEXT,
  import_group_id UUID,
  import_batch_id UUID,
  imported_at TIMESTAMPTZ,
  CONSTRAINT boardgamebuddy_plays_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_plays_game_id_fkey FOREIGN KEY (game_id) REFERENCES boardgamebuddy_games(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_plays_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT bgb_plays_country_code_chk CHECK (((country_code IS NULL) OR (country_code ~ '^[A-Z]{2}$'::text))),
  CONSTRAINT boardgamebuddy_plays_play_mode_check CHECK ((play_mode = ANY (ARRAY['competitive'::text, 'coop'::text, 'team'::text])))
);
ALTER TABLE public.boardgamebuddy_plays ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_plays_client_key ON public.boardgamebuddy_plays USING btree (user_id, client_key) WHERE (client_key IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bgb_plays_country_game ON public.boardgamebuddy_plays USING btree (country_code, game_id) WHERE (country_code IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bgb_plays_game_played ON public.boardgamebuddy_plays USING btree (game_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_bgb_plays_import_batch ON public.boardgamebuddy_plays USING btree (user_id, import_batch_id) WHERE (import_batch_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bgb_plays_import_group ON public.boardgamebuddy_plays USING btree (import_group_id, id) WHERE (import_group_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bgb_plays_played_at ON public.boardgamebuddy_plays USING btree (played_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_plays_user_bgg_play ON public.boardgamebuddy_plays USING btree (user_id, bgg_play_id) WHERE (bgg_play_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bgb_plays_user_played ON public.boardgamebuddy_plays USING btree (user_id, played_at DESC, created_at DESC);
GRANT SELECT ON public.boardgamebuddy_plays TO boardgamebuddy_role;


-- ── Play participants ─────────────────────────────────────────────────────────
-- Who was at the table. References profiles directly for real accounts and
-- falls back to player_display_name for ghosts, so a play can record someone
-- who has no account.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_play_players (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  play_id UUID NOT NULL,
  is_winner BOOLEAN DEFAULT false,
  score INTEGER,
  player_user_id UUID,
  player_display_name TEXT,
  round_scores JSONB,
  CONSTRAINT boardgamebuddy_play_players_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_play_players_play_id_fkey FOREIGN KEY (play_id) REFERENCES boardgamebuddy_plays(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_play_players_player_user_id_fkey FOREIGN KEY (player_user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE SET NULL,
  CONSTRAINT bgb_play_players_identity_chk CHECK (((player_user_id IS NOT NULL) OR (player_display_name IS NOT NULL)))
);
ALTER TABLE public.boardgamebuddy_play_players ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_play_players_display_name_trgm ON public.boardgamebuddy_play_players USING gin (player_display_name extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_bgb_play_players_play ON public.boardgamebuddy_play_players USING btree (play_id);
CREATE INDEX IF NOT EXISTS idx_bgb_play_players_user_play ON public.boardgamebuddy_play_players USING btree (player_user_id, play_id) WHERE (player_user_id IS NOT NULL);
GRANT SELECT ON public.boardgamebuddy_play_players TO boardgamebuddy_role;


-- ── Expansions used in a play ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_play_expansions (
  play_id UUID NOT NULL,
  expansion_game_id UUID NOT NULL,
  CONSTRAINT boardgamebuddy_play_expansions_pkey PRIMARY KEY (play_id, expansion_game_id),
  CONSTRAINT boardgamebuddy_play_expansions_expansion_game_id_fkey FOREIGN KEY (expansion_game_id) REFERENCES boardgamebuddy_games(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_play_expansions_play_id_fkey FOREIGN KEY (play_id) REFERENCES boardgamebuddy_plays(id) ON DELETE CASCADE
);
ALTER TABLE public.boardgamebuddy_play_expansions ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.boardgamebuddy_play_expansions TO boardgamebuddy_role;


-- ── Live sessions ─────────────────────────────────────────────────────────────
-- An at-the-table session in progress. phase walks gather → play → score;
-- play_id is set once the session finalizes into a logged play. Published to
-- Supabase Realtime (below) so every device at the table follows along.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_play_sessions (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  code TEXT NOT NULL,
  host_user_id UUID NOT NULL,
  game_id UUID,
  status TEXT DEFAULT 'open'::text NOT NULL,
  finalized_play_id UUID,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  expires_at TIMESTAMPTZ DEFAULT (now() + '02:00:00'::interval) NOT NULL,
  finalized_at TIMESTAMPTZ,
  phase TEXT DEFAULT 'gather'::text NOT NULL,
  CONSTRAINT boardgamebuddy_play_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_play_sessions_finalized_play_id_fkey FOREIGN KEY (finalized_play_id) REFERENCES boardgamebuddy_plays(id) ON DELETE SET NULL,
  CONSTRAINT boardgamebuddy_play_sessions_game_id_fkey FOREIGN KEY (game_id) REFERENCES boardgamebuddy_games(id) ON DELETE SET NULL,
  CONSTRAINT boardgamebuddy_play_sessions_host_user_id_fkey FOREIGN KEY (host_user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_play_sessions_phase_check CHECK ((phase = ANY (ARRAY['gather'::text, 'play'::text, 'settle'::text, 'finalized'::text, 'abandoned'::text]))),
  CONSTRAINT boardgamebuddy_play_sessions_status_check CHECK ((status = ANY (ARRAY['open'::text, 'finalized'::text, 'abandoned'::text])))
);
ALTER TABLE public.boardgamebuddy_play_sessions ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_play_sessions_expires ON public.boardgamebuddy_play_sessions USING btree (expires_at) WHERE (status = 'open'::text);
CREATE INDEX IF NOT EXISTS idx_bgb_play_sessions_host ON public.boardgamebuddy_play_sessions USING btree (host_user_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_play_sessions_open_code ON public.boardgamebuddy_play_sessions USING btree (code) WHERE (status = 'open'::text);
GRANT SELECT ON public.boardgamebuddy_play_sessions TO boardgamebuddy_role;
GRANT SELECT ON public.boardgamebuddy_play_sessions TO authenticated;


-- ── Session participants ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_play_session_participants (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  session_id UUID NOT NULL,
  user_id UUID,
  display_name TEXT NOT NULL,
  joined_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  position SMALLINT,
  CONSTRAINT boardgamebuddy_play_session_participants_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_play_session_participants_session_id_fkey FOREIGN KEY (session_id) REFERENCES boardgamebuddy_play_sessions(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_play_session_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE
);
ALTER TABLE public.boardgamebuddy_play_session_participants ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_play_session_guest_unique ON public.boardgamebuddy_play_session_participants USING btree (session_id, lower(display_name)) WHERE (user_id IS NULL);
CREATE INDEX IF NOT EXISTS idx_bgb_play_session_participants_session ON public.boardgamebuddy_play_session_participants USING btree (session_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_play_session_user_unique ON public.boardgamebuddy_play_session_participants USING btree (session_id, user_id) WHERE (user_id IS NOT NULL);
GRANT SELECT ON public.boardgamebuddy_play_session_participants TO boardgamebuddy_role;


-- ── Live scores ───────────────────────────────────────────────────────────────
-- Per-round scores during a session. The one table the web client touches
-- directly through supabase-js rather than the backend, which is why it
-- carries both RLS policies and Data API grants: only the host writes, and
-- only while the session is in the 'play' phase.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_play_session_scores (
  session_id UUID NOT NULL,
  round_index SMALLINT NOT NULL,
  score INTEGER,
  participant_id UUID NOT NULL,
  CONSTRAINT boardgamebuddy_play_session_scores_pkey PRIMARY KEY (session_id, participant_id, round_index),
  CONSTRAINT boardgamebuddy_play_session_scores_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES boardgamebuddy_play_session_participants(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_play_session_scores_session_id_fkey FOREIGN KEY (session_id) REFERENCES boardgamebuddy_play_sessions(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_play_session_scores_round_index_check CHECK (((round_index >= 0) AND (round_index < 64)))
);
ALTER TABLE public.boardgamebuddy_play_session_scores ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_play_session_scores_session ON public.boardgamebuddy_play_session_scores USING btree (session_id, round_index);
GRANT SELECT ON public.boardgamebuddy_play_session_scores TO boardgamebuddy_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.boardgamebuddy_play_session_scores TO authenticated;


-- ── Unlocked achievements ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_user_achievements (
  user_id UUID NOT NULL,
  achievement_id TEXT NOT NULL,
  unlocked_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT boardgamebuddy_user_achievements_pkey PRIMARY KEY (user_id, achievement_id),
  CONSTRAINT boardgamebuddy_user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES boardgamebuddy_achievements(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE
);
ALTER TABLE public.boardgamebuddy_user_achievements ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.boardgamebuddy_user_achievements TO boardgamebuddy_role;


-- ── BGG import queue ──────────────────────────────────────────────────────────
-- One row per game waiting to be imported from a BoardGameGeek collection.
-- kind='catalog' materializes the game row alone, without shelving it.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_bgg_pending_imports (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  user_id UUID NOT NULL,
  bgg_id INTEGER NOT NULL,
  kind TEXT NOT NULL,
  payload JSONB NOT NULL,
  status TEXT DEFAULT 'pending'::text NOT NULL,
  error_message TEXT,
  attempts INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  completed_at TIMESTAMPTZ,
  CONSTRAINT boardgamebuddy_bgg_pending_imports_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_bgg_pending_imports_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT boardgamebuddy_bgg_pending_imports_kind_check CHECK ((kind = ANY (ARRAY['collection'::text, 'play'::text, 'catalog'::text]))),
  CONSTRAINT boardgamebuddy_bgg_pending_imports_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'done'::text, 'error'::text])))
);
ALTER TABLE public.boardgamebuddy_bgg_pending_imports ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_bgb_bgg_pending_unique ON public.boardgamebuddy_bgg_pending_imports USING btree (user_id, bgg_id, kind);
CREATE INDEX IF NOT EXISTS idx_bgb_bgg_pending_user_status ON public.boardgamebuddy_bgg_pending_imports USING btree (user_id, status) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_bgb_pending_imports_user_created ON public.boardgamebuddy_bgg_pending_imports USING btree (user_id, created_at);
GRANT SELECT ON public.boardgamebuddy_bgg_pending_imports TO boardgamebuddy_role;


-- ── BGG push queue ────────────────────────────────────────────────────────────
-- The outbound half: one row per planned change to the user's BGG
-- collection, drained by a background task. State lives here rather than in
-- memory so a restart mid-push resumes instead of replaying.
CREATE TABLE IF NOT EXISTS public.boardgamebuddy_bgg_push_queue (
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  user_id UUID NOT NULL,
  bgg_id INTEGER NOT NULL,
  game_name TEXT NOT NULL,
  bgg_collid BIGINT,
  change TEXT NOT NULL,
  target_status TEXT,
  payload JSONB NOT NULL,
  status TEXT DEFAULT 'pending'::text NOT NULL,
  attempts INTEGER DEFAULT 0 NOT NULL,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  completed_at TIMESTAMPTZ,
  CONSTRAINT boardgamebuddy_bgg_push_queue_pkey PRIMARY KEY (id),
  CONSTRAINT boardgamebuddy_bgg_push_queue_user_id_bgg_id_key UNIQUE (user_id, bgg_id),
  CONSTRAINT boardgamebuddy_bgg_push_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES boardgamebuddy_profiles(id) ON DELETE CASCADE,
  CONSTRAINT bgb_push_change_status CHECK ((((change = ANY (ARRAY['add'::text, 'update'::text])) AND (target_status IS NOT NULL)) OR ((change = 'clear'::text) AND (target_status IS NULL)))),
  CONSTRAINT boardgamebuddy_bgg_push_queue_change_check CHECK ((change = ANY (ARRAY['add'::text, 'update'::text, 'clear'::text]))),
  CONSTRAINT boardgamebuddy_bgg_push_queue_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'done'::text, 'error'::text]))),
  CONSTRAINT boardgamebuddy_bgg_push_queue_target_status_check CHECK ((target_status = ANY (ARRAY['owned'::text, 'wishlist'::text, 'prev_owned'::text])))
);
ALTER TABLE public.boardgamebuddy_bgg_push_queue ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_bgb_push_queue_user_created ON public.boardgamebuddy_bgg_push_queue USING btree (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_bgb_push_queue_user_pending ON public.boardgamebuddy_bgg_push_queue USING btree (user_id, status) WHERE (status = 'pending'::text);
GRANT SELECT ON public.boardgamebuddy_bgg_push_queue TO boardgamebuddy_role;


-- ── Column documentation ─────────────────────────────────────────────────────
-- Carried over from the archive. These live in the database itself, so they
-- reach anyone reading the schema through psql \d+ or a GUI client, not just
-- readers of this file.

COMMENT ON SCHEMA public IS 'standard public schema';
COMMENT ON COLUMN public.boardgamebuddy_collections.played_before_at IS 'Set when the owner hand-marks an owned game as played before they joined BoardgameBuddy. Feeds the Shelf of Shame block of bgb_user_stats_detail and nothing else — it is not a play and must never be counted as one.';
COMMENT ON TABLE public.boardgamebuddy_countries IS 'ISO 3166-1 alpha-2 → continent, for the location achievements (migration 068). The code set is exactly the one web/domain/geo-data.js can produce, so no country the app can detect or offer is missing a continent.';
COMMENT ON COLUMN public.boardgamebuddy_play_players.round_scores IS 'Per-round score breakdown as a JSON array of nullable ints, e.g. [5, 8, null, 12]. NULL when no rounds were tracked (<= 1 round). The `score` column still holds the final total for backward compatibility and quick aggregation.';
COMMENT ON COLUMN public.boardgamebuddy_play_session_participants."position" IS 'Host-assigned column order, 0-based. NULL = never ordered; see bgb_session_bundle''s (position NULLS LAST, joined_at) sort.';
COMMENT ON COLUMN public.boardgamebuddy_plays.client_key IS 'Client-generated idempotency key for offline-queued plays. NULL for live writes.';
COMMENT ON COLUMN public.boardgamebuddy_plays.country_code IS 'ISO 3166-1 alpha-2 country where the play happened, uppercase. Resolved by the client from the device timezone (or picked by the host in Settle Up); NULL when unknown, and NULL on every row predating migration 065. Feeds a future popularity-by-country view and nothing today.';
COMMENT ON COLUMN public.boardgamebuddy_profiles.avatar IS 'Customizable badge config: {icon, iconColor, bgColor}. icon is "initials" or an icon key from the client library. NULL = use BGB default (brown badge + gold initials).';
COMMENT ON COLUMN public.boardgamebuddy_profiles.needs_setup IS 'TRUE for brand-new accounts that have not yet completed the "Create your profile" modal. Cleared by the first successful POST /profile.';
COMMENT ON COLUMN public.boardgamebuddy_profiles.app_installed_at IS 'First time this account was seen running as an installed PWA (migration 062). Drives the "Pocket Buddy" achievement; nothing else reads it.';

-- ── Row level security policies ──────────────────────────────────────────────
-- The only two tables the web client reads through supabase-js instead of the
-- backend, so these policies are the actual authorization for live sessions.
-- Everything else in this file relies on RLS-with-no-policy to deny direct
-- access outright.

-- You can see a session you host or are a participant in.
CREATE POLICY bgb_play_sessions_select ON public.boardgamebuddy_play_sessions
  FOR SELECT TO authenticated USING (
    host_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.boardgamebuddy_play_session_participants p
      WHERE p.session_id = boardgamebuddy_play_sessions.id
        AND p.user_id = auth.uid()
    )
  );

-- Everyone at the table reads live scores…
CREATE POLICY bgb_session_scores_select ON public.boardgamebuddy_play_session_scores
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.boardgamebuddy_play_sessions s
      WHERE s.id = boardgamebuddy_play_session_scores.session_id
        AND (
          s.host_user_id = auth.uid()
          OR EXISTS (
            SELECT 1 FROM public.boardgamebuddy_play_session_participants p
            WHERE p.session_id = s.id AND p.user_id = auth.uid()
          )
        )
    )
  );

-- …but only the host writes them, and only while the session is being played.
-- Both halves of the check are load-bearing: without the phase test a host
-- could rewrite scores after finalizing (archive/053).
CREATE POLICY bgb_session_scores_write ON public.boardgamebuddy_play_session_scores
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.boardgamebuddy_play_sessions s
      WHERE s.id = boardgamebuddy_play_session_scores.session_id
        AND s.phase = 'play'
        AND s.host_user_id = auth.uid()
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.boardgamebuddy_play_sessions s
      WHERE s.id = boardgamebuddy_play_session_scores.session_id
        AND s.phase = 'play'
        AND s.host_user_id = auth.uid()
    )
  );


-- ── Supabase Realtime ────────────────────────────────────────────────────────
-- Publishing these two tables is what makes every device at the table follow
-- the session live. On a non-Supabase database there is no supabase_realtime
-- publication and this block is a no-op.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
        AND tablename = 'boardgamebuddy_play_sessions'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.boardgamebuddy_play_sessions;
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
        AND tablename = 'boardgamebuddy_play_session_scores'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.boardgamebuddy_play_session_scores;
    END IF;
  END IF;
END $$;
