#!/usr/bin/env python3
"""Print a SQL query that reports which migrations this database is missing.

Migrations here are applied BY HAND (see README.md) while the code that depends
on them deploys automatically on merge, so a deploy can lead its schema. The
resulting drift does not announce itself: the backend calls an RPC that isn't
there yet, or gets back the previous version's column set, and the handler
fails somewhere well downstream of the real cause. In the browser that used to
arrive as an opaque "Failed to fetch" — which boardgame-buddy reads as being
OFFLINE. Hours were lost to a phone at full signal insisting it had no
connection, because a forgotten migration and a dead network look identical
from the client.

This answers "did I forget to run one?" in one paste:

    python3 db/check_drift.py            # every app
    python3 db/check_drift.py boardgamebuddy

Copy the output into the Supabase SQL editor. Every row it returns is an object
some migration creates that the database does not have; the migration naming
the most rows is the one to run. NO ROWS means the schema is current.

Generated from the migrations rather than hand-kept, so it cannot go stale: add
a migration and the next run already checks it.

Read-only — it selects from the catalog and changes nothing.
"""
import os
import re
import sys

MIGRATIONS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "migrations")

# Objects a migration creates that are cheap and unambiguous to look for in the
# catalog afterwards. Indexes, policies, grants, triggers and constraints are
# deliberately NOT checked: they are renamed and replaced often enough that
# absence is weak evidence, and a false alarm here would train the reader to
# ignore the whole report.
FUNCTION_RE = re.compile(r"CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+(?:public\.)?([a-zA-Z0-9_]+)", re.I)
TABLE_RE = re.compile(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?([a-zA-Z0-9_]+)", re.I)
COLUMN_RE = re.compile(
    r"ALTER\s+TABLE\s+(?:IF\s+EXISTS\s+)?(?:public\.)?([a-zA-Z0-9_]+)\s+"
    r"ADD\s+COLUMN\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-zA-Z0-9_]+)",
    re.I,
)


def collect(app_filter=None):
    """Every checkable object, mapped to the LAST migration that creates it.

    Last rather than first because a CREATE OR REPLACE FUNCTION in a later
    migration is the version the code now expects — and an unapplied replace is
    the more common drift by far. Its absence can't be detected from the
    catalog (the old function is still there under the same name), so those
    rows won't show up here; what this catches is the outright-missing object.
    """
    found = {}
    for root, dirs, files in os.walk(MIGRATIONS):
        dirs[:] = [d for d in dirs if d != "archive"]
        app = os.path.basename(root)
        if app_filter and app != app_filter:
            continue
        for name in sorted(files):
            if not name.endswith(".sql"):
                continue
            label = f"{app}/{name}"
            sql = open(os.path.join(root, name), encoding="utf-8").read()
            for m in FUNCTION_RE.finditer(sql):
                found[("function", m.group(1))] = label
            for m in TABLE_RE.finditer(sql):
                found[("table", m.group(1))] = label
            for m in COLUMN_RE.finditer(sql):
                found[("column", f"{m.group(1)}.{m.group(2)}")] = label
    return found


def main():
    app_filter = sys.argv[1] if len(sys.argv) > 1 else None
    found = collect(app_filter)
    if not found:
        target = app_filter or "db/migrations"
        sys.exit(f"No migrations found for {target!r}.")

    rows = ",\n".join(
        "  ('{}', '{}', '{}')".format(kind, obj.replace("'", "''"), label.replace("'", "''"))
        for (kind, obj), label in sorted(found.items(), key=lambda kv: (kv[1], kv[0]))
    )
    scope = app_filter or "all apps"
    print(f"""-- Migration drift check — {scope} ({len(found)} objects)
-- Generated by db/check_drift.py. Read-only.
-- Every row returned is missing from this database. No rows = schema is current.
with expected(kind, obj, migration) as (values
{rows}
),
present(kind, obj) as (
  select 'function', p.proname::text
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
  union all
  select 'table', c.relname::text
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind in ('r', 'p')
  union all
  select 'column', (table_name || '.' || column_name)::text
    from information_schema.columns
   where table_schema = 'public'
)
select e.migration as run_this_migration, e.kind, e.obj as missing_object
  from expected e
 where not exists (
         select 1 from present p where p.kind = e.kind and p.obj = e.obj
       )
 order by e.migration, e.kind, e.obj;""")


if __name__ == "__main__":
    main()
