/**
 * generate_seed_sql.js
 * Reads the SauceBoss data files and writes db/migrations/003_sauceboss_seed.sql
 *
 * Usage (from vibelab root):
 *   node projects/sauceboss/scripts/generate_seed_sql.js
 *
 * Requires the original sauces.js + carbs.js data to still be at:
 *   projects/sauceboss/app/src/data/carbs.js
 *   projects/sauceboss/app/src/data/sauces.js
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const vibelabRoot = resolve(__dirname, '../../..');

// Dynamically import the data files (they use ES module exports)
const carbsPath = resolve(__dirname, '../app/src/data/carbs.js');
const saucesPath = resolve(__dirname, '../app/src/data/sauces.js');

const { CARBS } = await import(pathToFileURL(carbsPath));
const { SAUCES } = await import(pathToFileURL(saucesPath));

function esc(str) {
  return str.replace(/'/g, "''");
}

const lines = [
  '-- ─────────────────────────────────────────────────────────────────────────────',
  '-- 003_sauceboss_seed.sql',
  '-- Auto-generated by projects/sauceboss/scripts/generate_seed_sql.js',
  '-- DO NOT EDIT BY HAND — re-run the script if data changes.',
  `-- Generated: ${new Date().toISOString()}`,
  '-- ─────────────────────────────────────────────────────────────────────────────',
  '',
  '-- Carbs',
];

for (const c of CARBS) {
  lines.push(
    `INSERT INTO sauceboss_carbs (id, name, emoji, description) VALUES ('${esc(c.id)}', '${esc(c.name)}', '${esc(c.emoji)}', '${esc(c.desc)}') ON CONFLICT (id) DO NOTHING;`
  );
}

lines.push('', '-- Sauces');
for (const s of SAUCES) {
  lines.push(
    `INSERT INTO sauceboss_sauces (id, name, cuisine, cuisine_emoji, color, description) VALUES ('${esc(s.id)}', '${esc(s.name)}', '${esc(s.cuisine)}', '${esc(s.cuisineEmoji)}', '${esc(s.color)}', '${esc(s.description)}') ON CONFLICT (id) DO NOTHING;`
  );
}

lines.push('', '-- Sauce ↔ Carb associations');
for (const s of SAUCES) {
  for (const carbId of s.compatibleCarbs) {
    lines.push(
      `INSERT INTO sauceboss_sauce_carbs (sauce_id, carb_id) VALUES ('${esc(s.id)}', '${esc(carbId)}') ON CONFLICT DO NOTHING;`
    );
  }
}

lines.push('', '-- Steps and ingredients');
// Steps need IDs. We use a temporary sequence approach with a CTE per sauce.
// Since we can't know auto-generated IDs upfront, we insert steps and look up IDs.
for (const s of SAUCES) {
  for (let order = 0; order < s.steps.length; order++) {
    const step = s.steps[order];
    lines.push(`WITH inserted_step AS (`);
    lines.push(`  INSERT INTO sauceboss_sauce_steps (sauce_id, step_order, title)`);
    lines.push(`  VALUES ('${esc(s.id)}', ${order}, '${esc(step.title)}')`);
    lines.push(`  ON CONFLICT DO NOTHING`);
    lines.push(`  RETURNING id`);
    lines.push(`)`);
    const ingValues = step.ingredients.map(
      ing => `((SELECT id FROM inserted_step), '${esc(ing.name)}', ${ing.amount}, '${esc(ing.unit)}')`
    ).join(',\n       ');
    lines.push(`INSERT INTO sauceboss_step_ingredients (step_id, name, amount, unit)`);
    lines.push(`SELECT v.step_id, v.name, v.amount, v.unit FROM (VALUES`);
    lines.push(`  ${ingValues}`);
    lines.push(`) AS v(step_id, name, amount, unit)`);
    lines.push(`WHERE v.step_id IS NOT NULL;`);
    lines.push('');
  }
}

const outputPath = resolve(vibelabRoot, 'db/migrations/003_sauceboss_seed.sql');
writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`✓ Wrote ${outputPath}`);
console.log(`  ${CARBS.length} carbs, ${SAUCES.length} sauces`);
