#!/usr/bin/env python3
"""
local_dev/setup-local.py — fan out credentials to every project.

Reads:  local_dev/.env
Writes:
  shared-backend/.env              (copy, so uvicorn's load_dotenv() works)
  projects/*/web/config.js         (gitignored; loaded by index.html)
  projects/*/app/.env              (gitignored; loaded by Expo at build time)

Run from the repo root:
  python local_dev/setup-local.py

See local_dev/README.md for the full local dev guide.
"""

import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
LOCAL_ENV = Path(__file__).parent / ".env"
BACKEND_ENV = REPO_ROOT / "shared-backend" / ".env"

# App-specific extras written into app/.env beyond the three common vars.
APP_EXTRAS: dict[str, dict[str, str]] = {
    "daywordplay": {
        "EXPO_PUBLIC_AUTH_CALLBACK_URL": "https://vibelab-daywordplay.vercel.app/auth-callback.html",
    },
}


def parse_env(path: Path) -> dict[str, str]:
    """Parse a .env file, ignoring comments and blank lines."""
    result: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        result[key.strip()] = value.strip()
    return result


def write_web_config(web_dir: Path, project: str, api_base: str, supabase_url: str, supabase_anon_key: str) -> None:
    out = web_dir / "config.js"
    out.write_text(
        "// config.js — generated by local_dev/setup-local.py (gitignored, not deployed)\n"
        "// Re-run 'python local_dev/setup-local.py' after changing local_dev/.env.\n"
        "// See local_dev/README.md for the local dev guide.\n"
        "window.APP_CONFIG = {\n"
        f'  apiBase:         "{api_base}",\n'
        f'  project:         "{project}",\n'
        f'  supabaseUrl:     "{supabase_url}",\n'
        f'  supabaseAnonKey: "{supabase_anon_key}",\n'
        "};\n",
        encoding="utf-8",
    )


def write_app_env(app_dir: Path, project: str, api_base: str, supabase_url: str, supabase_anon_key: str) -> None:
    lines = [
        "# .env — generated by local_dev/setup-local.py (gitignored)",
        "# Re-run 'python local_dev/setup-local.py' after changing local_dev/.env.",
        "# See local_dev/README.md for the local dev guide.",
        "",
        f"EXPO_PUBLIC_API_URL={api_base}",
        f"EXPO_PUBLIC_SUPABASE_URL={supabase_url}",
        f"EXPO_PUBLIC_SUPABASE_ANON_KEY={supabase_anon_key}",
    ]
    extras = APP_EXTRAS.get(project, {})
    if extras:
        lines.append("")
        for key, value in extras.items():
            lines.append(f"{key}={value}")

    out = app_dir / ".env"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if not LOCAL_ENV.exists():
        print(f"Error: {LOCAL_ENV} not found.")
        print("  cp local_dev/.env.example local_dev/.env")
        print("  # Fill in SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_ANON_KEY, then re-run.")
        sys.exit(1)

    env = parse_env(LOCAL_ENV)

    # Copy to shared-backend/ so uvicorn's load_dotenv() picks it up.
    shutil.copy2(LOCAL_ENV, BACKEND_ENV)
    print(f"  copied local_dev/.env → shared-backend/.env")

    api_base = env.get("API_BASE", "http://localhost:8000")
    supabase_url = env.get("SUPABASE_URL", "")
    supabase_anon_key = env.get("SUPABASE_ANON_KEY", "")

    missing = [k for k, v in [("SUPABASE_URL", supabase_url), ("SUPABASE_ANON_KEY", supabase_anon_key)] if not v or "your-" in v]
    if missing:
        print(f"Warning: {', '.join(missing)} not filled in local_dev/.env — output files will have blank values.")

    projects_dir = REPO_ROOT / "projects"
    if not projects_dir.is_dir():
        print(f"Error: {projects_dir} not found. Run from the repo root.")
        sys.exit(1)

    wrote_any = False
    for project_dir in sorted(projects_dir.iterdir()):
        if not project_dir.is_dir():
            continue
        project = project_dir.name

        web_dir = project_dir / "web"
        if web_dir.is_dir():
            write_web_config(web_dir, project, api_base, supabase_url, supabase_anon_key)
            print(f"  wrote  projects/{project}/web/config.js")
            wrote_any = True

        app_dir = project_dir / "app"
        if app_dir.is_dir():
            write_app_env(app_dir, project, api_base, supabase_url, supabase_anon_key)
            print(f"  wrote  projects/{project}/app/.env")
            wrote_any = True

    if not wrote_any:
        print("No project web/ or app/ directories found.")
        sys.exit(1)

    print()
    print("Done. Serve any project's web/ directory with:")
    print("  cd projects/<name>/web && python -m http.server 5500")
    print()
    print("Note: for physical devices, set EXPO_PUBLIC_API_URL to your LAN IP in projects/<name>/app/.env")


if __name__ == "__main__":
    main()
