-- ─────────────────────────────────────────────────────────────────────────────
-- BoardgameBuddy — RPC function inventory
-- Last updated: 2026-05-24 (033 bootstrap bundle for first-paint cache)
-- FOR REFERENCE ONLY — apply changes via db/migrations/
-- ─────────────────────────────────────────────────────────────────────────────

-- bgb_hot_games(window_days INT DEFAULT 7, lim INT DEFAULT 10)
--   → TABLE (game_id UUID, play_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/012_rpcs_feed_and_stats.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Top-N most-played games in the last N days for the Feed's
--               "Hot Games" card.

-- bgb_user_stats(uid UUID)
--   → TABLE (total_plays BIGINT, unique_games BIGINT, win_count BIGINT,
--            last_played_at DATE, hours_played NUMERIC, owned_games BIGINT,
--            owned_expansions BIGINT, favorite_game_id UUID,
--            favorite_game_name TEXT, favorite_play_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/015_user_stats_with_favorite.sql
--               (originally 012; widened to surface owned_games (base only),
--                owned_expansions, and favorite_game)
--   Called by:  shared-backend/routes/boardgame_buddy/services/stats_service.py
--   Purpose:    Per-user stats card on the Profile view (Played Games,
--               Owned Games, Wins, Favorite Game). owned_games excludes
--               expansions; owned_expansions is the secondary counter.

-- bgb_feed_plays(viewer UUID, before_played_at DATE DEFAULT NULL,
--                before_created_at TIMESTAMPTZ DEFAULT NULL, lim INT DEFAULT 20)
--   → TABLE (play_id UUID, play_user_id UUID, play_user_name TEXT,
--            play_user_avatar JSONB, game_id UUID, game_name TEXT,
--            game_image_url TEXT, game_thumbnail_url TEXT, played_at DATE,
--            created_at TIMESTAMPTZ, notes TEXT, photo_url TEXT,
--            play_mode TEXT, winner_display_name TEXT,
--            participant_count INT, participants JSONB)
--   Defined in: db/migrations/boardgamebuddy/014_feed_order_by_played_at.sql
--               (originally 012; signature changed to a composite cursor)
--   Last updated in: db/migrations/boardgamebuddy/032_feed_plays_buddy_participation.sql
--               (visibility predicate widened from "logger ∈ visible OR
--               viewer ∈ participants" to "any participant ∈ visible",
--               so plays where a buddy was tagged but the logger is not
--               a buddy of the viewer now surface in the feed.)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Visible plays for the Feed: any play where the viewer or
--               an accepted buddy participated (via boardgamebuddy_play_players),
--               plus a legacy safety branch for logger ∈ visible. Pre-joined
--               to game name/image, winner display, and a participant-aware
--               roster. Ordered by played_at DESC, created_at DESC. Cursor
--               is the last row's (played_at, created_at) for lexicographic
--               tuple comparison.

-- bgb_dormant_collection(uid UUID, days_since INT DEFAULT 60, lim INT DEFAULT 5)
--   → TABLE (game_id UUID, last_played_at DATE)
--   Defined in: db/migrations/boardgamebuddy/012_rpcs_feed_and_stats.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Owned games this user hasn't played in N days; powers the
--               "Featured from your collection" Feed card.

-- bgb_suggested_buddies(uid UUID, lim INT DEFAULT 10)
--   → TABLE (user_id UUID, mutual_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/012_rpcs_feed_and_stats.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Friends-of-friends candidates not yet connected, ranked by
--               mutual count. Powers the Feed's "Suggested buddies" card.

-- bgb_distinct_mechanics()
--   → TABLE (mechanic TEXT)
--   Defined in: db/migrations/boardgamebuddy/019_perf_indexes.sql
--   Called by:  shared-backend/routes/boardgame_buddy/game_routes.py
--   Purpose:    Sorted distinct mechanic strings across the games catalog.
--               Backs the /games/mechanics endpoint without a full table
--               scan + Python aggregation.

-- bgb_game_detail_bundle(game_uuid UUID, viewer UUID, plays_limit INT DEFAULT 5)
--   → JSONB
--   Defined in: db/migrations/boardgamebuddy/021_profile_and_game_detail_bundles.sql
--   Last updated in: db/migrations/boardgamebuddy/023_game_detail_bundle_viewer_status_played.sql
--               (viewer_status now falls through to 'played' when the viewer
--               has any visible play of the game with no collection row —
--               same fix Profile bundle's status_map got in migration 022)
--   Called by:  shared-backend/routes/boardgame_buddy/game_routes.py
--               (GET /games/{game_id}/bundle)
--   Purpose:    Single round-trip Game Detail payload: game row + base game
--               (when expansion) + viewer's collection status + last N
--               plays visible to viewer + expansions list with viewer's
--               toggle state. Reads denormalized plays.game_* fields (020)
--               so most rows don't join boardgamebuddy_games.

-- bgb_profile_bundle(viewer UUID, target UUID, col_per_page INT DEFAULT 12,
--                    plays_per_page INT DEFAULT 10)
--   → JSONB
--   Defined in: db/migrations/boardgamebuddy/021_profile_and_game_detail_bundles.sql
--   Last updated in: db/migrations/boardgamebuddy/029_profile_avatar_config.sql
--               (buddy + buddy-request blocks now emit `other_avatar` JSONB
--               instead of `other_avatar_url` TEXT, following the
--               avatar_url → avatar rename on boardgamebuddy_profiles)
--   Called by:  shared-backend/routes/boardgame_buddy/profile_routes.py
--               (GET /profile/bundle)
--   Purpose:    Single round-trip Profile Self / Profile Other payload.
--               Stats + owned/wishlist/played first pages + recent plays +
--               viewer's status_map + expansion_counts. Buddies + pending
--               requests are included only when viewer = target. Reuses
--               bgb_user_stats for the stats block.

-- bgb_bootstrap(viewer UUID, owned_plays_limit INT DEFAULT 5,
--               max_game_bundles INT DEFAULT 250)
--   → JSONB { bootstrap_version, generated_at, current_user, profile_bundle,
--             game_detail_bundles (object keyed by game_id), owned_count,
--             truncated }
--   Defined in: db/migrations/boardgamebuddy/033_bootstrap_bundle.sql
--   Called by:  shared-backend/routes/boardgame_buddy/bootstrap_routes.py
--               (GET /bootstrap)
--   Purpose:    First-paint client cache warm-up. Composes bgb_profile_bundle
--               for the viewer and bgb_game_detail_bundle for every owned
--               game into one JSONB. The FE writes everything into its
--               localStorage-backed cache so the entire app navigates
--               without further round trips until cached entries go stale.
--               bootstrap_version is bumped any time this payload's shape
--               changes — the FE wipes its cache on mismatch.
