-- ─────────────────────────────────────────────────────────────────────────────
-- BoardgameBuddy — RPC function inventory
-- Last updated: migration 044 (dead-object cleanup)
-- FOR REFERENCE ONLY — apply changes via db/migrations/
-- ─────────────────────────────────────────────────────────────────────────────

-- bgb_hot_games(window_days INT DEFAULT 7, lim INT DEFAULT 10)
--   → TABLE (game_id UUID, play_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/012_rpcs_feed_and_stats.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Top-N most-played games in the last N days for the Feed's
--               "Hot Games" card.

-- bgb_user_stats(uid UUID)
--   → TABLE (total_plays BIGINT, unique_games BIGINT, win_count BIGINT,
--            last_played_at DATE, hours_played NUMERIC, owned_games BIGINT,
--            owned_expansions BIGINT, favorite_game_id UUID,
--            favorite_game_name TEXT, favorite_play_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/015_user_stats_with_favorite.sql
--               (originally 012; widened to surface owned_games (base only),
--                owned_expansions, and favorite_game)
--   Called by:  shared-backend/routes/boardgame_buddy/services/stats_service.py
--   Purpose:    Per-user stats card on the Profile view (Played Games,
--               Owned Games, Wins, Favorite Game). owned_games excludes
--               expansions; owned_expansions is the secondary counter.

-- bgb_feed_plays(viewer UUID, before_played_at DATE DEFAULT NULL,
--                before_created_at TIMESTAMPTZ DEFAULT NULL, lim INT DEFAULT 20)
--   → TABLE (play_id UUID, play_user_id UUID, play_user_name TEXT,
--            play_user_avatar JSONB, game_id UUID, game_name TEXT,
--            game_image_url TEXT, game_thumbnail_url TEXT, played_at DATE,
--            created_at TIMESTAMPTZ, notes TEXT, photo_url TEXT,
--            play_mode TEXT, winner_display_name TEXT,
--            participant_count INT, participants JSONB)
--   Defined in: db/migrations/boardgamebuddy/014_feed_order_by_played_at.sql
--               (originally 012; signature changed to a composite cursor)
--   Last updated in: db/migrations/boardgamebuddy/043_feed_perf_and_bootstrap_split.sql
--               (perf only, no behavior change — verified identical rows and
--               row order across 390 viewer x limit x cursor cases. A `page`
--               CTE now applies the cursor and LIMIT first and a LATERAL
--               resolves each page row's roster; previously the winners/
--               participants CTEs group-aggregated the entire play_players
--               table on every call — Postgres can't push the join qual
--               through a GROUP BY subquery — so feed latency grew with total
--               plays across all users, not the viewer's. 105 ms -> 5 ms on a
--               30k-play fixture. Language changed sql -> plpgsql so `lim` can
--               be interpolated as a literal via RETURN QUERY EXECUTE: as a
--               bind parameter it destroyed the planner's row estimate for
--               `page` and made the rewrite 8x slower than the original.)
--               Behavior last changed in 032_feed_plays_buddy_participation.sql
--               (visibility predicate widened from "logger ∈ visible OR
--               viewer ∈ participants" to "any participant ∈ visible",
--               so plays where a buddy was tagged but the logger is not
--               a buddy of the viewer now surface in the feed.)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Visible plays for the Feed: any play where the viewer or
--               an accepted buddy participated (via boardgamebuddy_play_players),
--               plus a legacy safety branch for logger ∈ visible. Pre-joined
--               to game name/image, winner display, and a participant-aware
--               roster. Ordered by played_at DESC, created_at DESC. Cursor
--               is the last row's (played_at, created_at) for lexicographic
--               tuple comparison.

-- bgb_dormant_collection(uid UUID, days_since INT DEFAULT 60, lim INT DEFAULT 5)
--   → TABLE (game_id UUID, last_played_at DATE)
--   Defined in: db/migrations/boardgamebuddy/012_rpcs_feed_and_stats.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Owned games this user hasn't played in N days; powers the
--               "Featured from your collection" Feed card.

-- bgb_suggested_buddies(uid UUID, lim INT DEFAULT 10)
--   → TABLE (user_id UUID, mutual_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/012_rpcs_feed_and_stats.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Friends-of-friends candidates not yet connected, ranked by
--               mutual count. Powers the Feed's "Suggested buddies" card. (The standalone
--               GET /suggestions/buddies endpoint was removed as uncalled;
--               feed_service still calls this for the embedded rail.)

-- bgb_distinct_mechanics()
--   → TABLE (mechanic TEXT)
--   Defined in: db/migrations/boardgamebuddy/019_perf_indexes.sql
--   Called by:  (nothing — GET /games/mechanics, its only caller, was removed
--               as uncalled. Kept because the mechanics filter is a plausible
--               near-term feature and the function is free to keep.)
--   Purpose:    Sorted distinct mechanic strings across the games catalog,
--               without a full table scan + Python aggregation.

-- bgb_game_detail_bundle(game_uuid UUID, viewer UUID, plays_limit INT DEFAULT 5)
--   → JSONB
--   Defined in: db/migrations/boardgamebuddy/021_profile_and_game_detail_bundles.sql
--   Last updated in: db/migrations/boardgamebuddy/023_game_detail_bundle_viewer_status_played.sql
--               (viewer_status now falls through to 'played' when the viewer
--               has any visible play of the game with no collection row —
--               same fix Profile bundle's status_map got in migration 022)
--   Called by:  shared-backend/routes/boardgame_buddy/game_routes.py
--               (GET /games/{game_id}/bundle)
--   Purpose:    Single round-trip Game Detail payload: game row + base game
--               (when expansion) + viewer's collection status + last N
--               plays visible to viewer + expansions list with viewer's
--               toggle state. Reads denormalized plays.game_* fields (020)
--               so most rows don't join boardgamebuddy_games.

-- bgb_profile_bundle(viewer UUID, target UUID, col_per_page INT DEFAULT 12,
--                    plays_per_page INT DEFAULT 10)
--   → JSONB
--   Defined in: db/migrations/boardgamebuddy/021_profile_and_game_detail_bundles.sql
--   Last updated in: db/migrations/boardgamebuddy/029_profile_avatar_config.sql
--               (buddy + buddy-request blocks now emit `other_avatar` JSONB
--               instead of `other_avatar_url` TEXT, following the
--               avatar_url → avatar rename on boardgamebuddy_profiles)
--   Called by:  shared-backend/routes/boardgame_buddy/profile_routes.py
--               (GET /profile/bundle)
--   Purpose:    Single round-trip Profile Self / Profile Other payload.
--               Stats + owned/wishlist/played first pages + recent plays +
--               viewer's status_map + expansion_counts. Buddies + pending
--               requests are included only when viewer = target. Reuses
--               bgb_user_stats for the stats block.

-- bgb_bootstrap(viewer UUID, owned_plays_limit INT DEFAULT 5,
--               max_game_bundles INT DEFAULT 250)
--   → JSONB { bootstrap_version, generated_at, current_user, profile_bundle,
--             game_detail_bundles (object keyed by game_id), owned_count,
--             truncated }
--   Defined in: db/migrations/boardgamebuddy/033_bootstrap_bundle.sql
--   Last updated in: db/migrations/boardgamebuddy/043_feed_perf_and_bootstrap_split.sql
--               (bootstrap_version → 2; the game-bundle block is now skipped
--               when max_game_bundles <= 0, which is how the backend calls it)
--   Called by:  shared-backend/routes/boardgame_buddy/bootstrap_routes.py
--               (GET /bootstrap, with max_game_bundles = 0)
--   Purpose:    First-paint client cache warm-up. Composes bgb_profile_bundle
--               for the viewer into one JSONB. The FE writes everything into
--               its localStorage-backed cache so the entire app navigates
--               without further round trips until cached entries go stale.
--               game_detail_bundles is left empty on the live call path —
--               see bgb_game_bundles.

-- bgb_game_bundles(viewer UUID, owned_plays_limit INT DEFAULT 5,
--                  max_bundles INT DEFAULT 250)
--   → JSONB { game_detail_bundles (object keyed by game_id), owned_count,
--             truncated }
--   Defined in: db/migrations/boardgamebuddy/043_feed_perf_and_bootstrap_split.sql
--   Called by:  shared-backend/routes/boardgame_buddy/bootstrap_routes.py
--               (GET /bootstrap/game-bundles)
--   Purpose:    Deferred second stage of the boot warm-up — one
--               bgb_game_detail_bundle per owned base game so opening Game
--               Detail is instant. Split out of bgb_bootstrap because it is
--               an N+1 in SQL (up to max_bundles invocations, ~5 statements
--               each) and nothing on the first screen reads it; the FE pulls
--               it from an idle callback after the user has landed, and Game
--               Detail falls back to its own fetch on a miss.
--               bootstrap_version is bumped any time this payload's shape
--               changes — the FE wipes its cache on mismatch.

-- bgb_session_bundle(p_session_id UUID)
--   → JSONB shaped like models.SessionResponse { id, code, status, phase,
--     host_user_id, game_id, game, participants[], created_at, expires_at,
--     finalized_play_id } or {"error": "not_found"}
--   Defined in: db/migrations/boardgamebuddy/036_session_rpcs.sql
--   Last updated in: db/migrations/boardgamebuddy/037_joinable_sessions_rpc.sql
--               (game block delegated to bgb_game_summary; output unchanged)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (_build_response — the response builder for every session
--               endpoint; also invoked internally by the three RPCs below)
--   Purpose:    Single round-trip lobby payload: session row + participant
--               roster with profile avatars + optional GameSummary. Replaced
--               the 3-4 sequential PostgREST selects _build_response used
--               to fan out.

-- bgb_create_session(p_host UUID, p_host_display_name TEXT,
--                    p_game UUID DEFAULT NULL)
--   → JSONB (SessionResponse bundle) or {"error": "code_allocation_failed"}
--   Defined in: db/migrations/boardgamebuddy/036_session_rpcs.sql
--   Last updated in: db/migrations/boardgamebuddy/038_fix_session_code_entropy.sql
--               (code entropy from uuid_send(gen_random_uuid()) — 036's
--               gen_random_bytes failed on Supabase because pgcrypto lives
--               in the `extensions` schema, outside the function's
--               search_path = public)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (create_session — POST /sessions)
--   Purpose:    One-call lobby open: abandons the host's stale open sessions,
--               allocates a unique 5-char Crockford code (≤6 retries against
--               the partial unique index on (code) WHERE status='open'),
--               seats the host as participant #1. Code alphabet/length
--               mirror constants.py — keep in step.

-- bgb_get_session(p_code TEXT)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired"}
--   Defined in: db/migrations/boardgamebuddy/036_session_rpcs.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (get_session — GET /sessions/{code}, the 2s lobby poll)
--   Purpose:    Open/expiry-gated session fetch. Expired sessions are marked
--               status='abandoned' (status only, matching the old
--               _fetch_open_session) and reported as expired → 410.

-- bgb_join_session(p_code TEXT, p_user UUID DEFAULT NULL,
--                  p_user_display_name TEXT DEFAULT NULL,
--                  p_guest_display_name TEXT DEFAULT NULL)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired" |
--     "guest_name_required"}
--   Defined in: db/migrations/boardgamebuddy/036_session_rpcs.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (join_session — POST /sessions/{code}/join)
--   Purpose:    Idempotent one-call join. During Gather, adds authed callers
--               by user_id and guests by trimmed case-insensitive
--               display_name; after Gather the roster is untouched
--               (spectator). Same semantics the Python service had, minus
--               the 3-4 extra round trips.

-- bgb_game_summary(p_game_id UUID)
--   → JSONB shaped like models.GameSummary (bgg_url / expansion_count are
--     computed/defaulted Pydantic-side), or NULL for NULL/unknown ids
--   Defined in: db/migrations/boardgamebuddy/037_joinable_sessions_rpc.sql
--   Called by:  (SQL-internal only) bgb_session_bundle, bgb_joinable_sessions
--   Purpose:    Canonical GameSummary JSON builder so every session RPC
--               emits the same game shape. Keys mirror _helpers._GAME_SELECT.

-- bgb_joinable_sessions(p_viewer UUID)
--   → JSONB array of models.JoinableSession { id, code, host_user_id,
--     host_display_name, host_avatar, game, phase, participant_count,
--     is_participant, is_host_buddy, created_at }, newest first
--   Defined in: db/migrations/boardgamebuddy/037_joinable_sessions_rpc.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (list_joinable — GET /sessions/joinable, the Join chooser)
--   Purpose:    One-call Join chooser payload: open unexpired sessions in
--               phase gather/play/settle visible to the viewer (own hosted,
--               already-joined, or hosted by an accepted buddy). Replaced
--               the 5 sequential PostgREST selects list_joinable fanned out.

-- bgb_log_play(p_user UUID, p_payload JSONB)
--   → JSONB shaped like models.PlayResponse { id, game_id, game_name,
--     game_thumbnail, played_at, notes, players[], photo_url, expansions[],
--     created_at, play_mode, logged_by_id, logged_by_name, is_own }
--     or {"error": "game_not_found"}
--   p_payload mirrors models.PlayCreate (a PlayCreate.model_dump(mode="json")).
--   Defined in: db/migrations/boardgamebuddy/042_write_rpcs.sql
--               db/migrations/boardgamebuddy/044_cleanup.sql
--                 (stops writing plays.game_image_url / game_play_mode, which
--                  044 drops; stops writing the boardgamebuddy_buddies roster,
--                  whose only reader — GET /plays/filter-options — was removed;
--                  stops emitting the always-null buddy_id key on each player)
--   Called by:  shared-backend/routes/boardgame_buddy/play_routes.py
--               (log_play — POST /plays) and SQL-internally by
--               bgb_finalize_session
--   Purpose:    One-call play write: resolves the game, inserts the play with
--               its surviving denormalized game_* columns (migration 020),
--               bulk-writes play_players + play_expansions, and returns the
--               hydrated response. Replaced the 6 sequential PostgREST calls
--               log_play fanned out — including a read-back of the expansion
--               rows it had just inserted.

-- bgb_finalize_session(p_host UUID, p_code TEXT, p_payload JSONB)
--   → JSONB (PlayResponse, via bgb_log_play) or {"error": "not_found" |
--     "expired" | "forbidden" | "game_not_found"}
--   Defined in: db/migrations/boardgamebuddy/042_write_rpcs.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (finalize_session — POST /sessions/{code}/finalize)
--   Purpose:    One-call wrap-up: open/expiry/host gates, overlays joiners'
--               live per-round totals onto the host's player list (matched by
--               user_id; guests keep their host-typed scores), calls
--               bgb_log_play, marks the session finalized. Replaced a 10
--               round-trip Python chain — the host's Save used to block on
--               all of it. A failed write (game_not_found) leaves the session
--               open so the host can retry.

-- bgb_plays_page(p_target UUID, p_page INT DEFAULT 1, p_per_page INT DEFAULT 20,
--                p_game UUID DEFAULT NULL, p_buddy UUID DEFAULT NULL,
--                p_search TEXT DEFAULT NULL, p_own_only BOOLEAN DEFAULT false)
--   → JSONB { plays: [models.PlayResponse-shaped...], total }
--   Defined in: db/migrations/boardgamebuddy/039_perf_rpcs_and_indexes.sql
--   Called by:  shared-backend/routes/boardgame_buddy/play_routes.py
--               (list_plays — GET /plays). The second caller, GET
--               /games/{id}/plays, was removed as uncalled; that data now
--               rides on /games/{id}/bundle.
--   Purpose:    One-call History page. Visibility = plays the target logged
--               plus plays where they appear as a participant. Filters
--               (game / buddy participant / free-text over game_name +
--               player_display_name), sort, LIMIT/OFFSET, and player +
--               expansion aggregation all in SQL. Replaced an 8-11 round
--               trip Python path that fetched every visible play tuple.
--               Reads denormalized plays.game_* columns (020).

-- bgb_play_stats(p_viewer UUID, p_game_ids UUID[] DEFAULT NULL)
--   → JSONB [ { game_id, play_count, last_played_at } ... ]
--   Defined in: db/migrations/boardgamebuddy/039_perf_rpcs_and_indexes.sql
--   Called by:  shared-backend/routes/boardgame_buddy/collection_routes.py
--               (_play_stats — GET /collection). GET /collection/shelf was
--               removed as uncalled; /collection/grid counts logged-only plays
--               through _own_play_stats instead, which is a narrower rule.
--   Purpose:    Per-game play_count / last_played_at via SQL GROUP BY over
--               the viewer's visible plays (own + participant). Replaced
--               _plays_visible_to_user + _index_plays, which shipped every
--               play row to Python to count — unbounded post-BGG-sync.

-- bgb_bgg_sync_status(p_user UUID)
--   → JSONB { bgg_username, has_credentials, pending_count, errored_count,
--             last_completed_at, session_started_at, session_total,
--             session_done, session_errored, session_game_names[] }
--   Defined in: db/migrations/boardgamebuddy/039_perf_rpcs_and_indexes.sql
--   Called by:  shared-backend/routes/boardgame_buddy/bgg_link_routes.py
--               (get_sync_status — GET /bgg/sync/status, FE poll target)
--   Purpose:    One-call import-progress poll (was up to 7 round trips per
--               poll). Session roll-up per distinct bgg_id mirrors the old
--               Python precedence (pending > error > done); names are the
--               20 most recently completed. has_credentials mirrors
--               bgg_client.has_stored_credentials so auth_state derives
--               without shipping the encrypted secret.

-- boardgamebuddy_search_games(p_viewer UUID, p_query TEXT, p_limit INT DEFAULT 20,
--                             p_include_expansions BOOLEAN DEFAULT false)
--   → TABLE (id UUID, bgg_id INT, name TEXT, year_published INT, min_players INT,
--            max_players INT, playing_time INT, thumbnail_url TEXT, image_url TEXT,
--            theme_color TEXT, is_expansion BOOLEAN, base_game_bgg_id INT,
--            expansion_color TEXT, rulebook_url TEXT, play_mode TEXT,
--            collection_status TEXT, in_collection BOOLEAN)
--   Defined in: db/migrations/boardgamebuddy/040_search_rpc.sql
--               db/migrations/boardgamebuddy/041_search_exclude_expansions.sql
--                 (adds p_include_expansions; drops + recreates the 3-arg form)
--   Called by:  shared-backend/routes/boardgame_buddy/services/search_service.py
--               (_rpc_hits — GET /search, the per-keystroke GameFinder)
--   Purpose:    One index-backed query for the unified game picker. Catalog
--               ILIKE '%q%' served by the pg_trgm GIN index (idx_bgb_games_name_trgm,
--               migration 039); LEFT JOIN onto the viewer's collection marks
--               in_collection + collection_status; collection-first ordering
--               (in_collection DESC, name) in SQL. Columns mirror _helpers._GAME_SELECT
--               plus the two collection extras. Replaced the two-query PostgREST
--               path whose collection match filtered an embedded !inner-joined
--               games.name column that the trigram index couldn't reliably serve.
--               search_service falls back to that path if this RPC is absent.
--               p_include_expansions defaults to false: expansions aren't
--               pickable as a session's main game and live in the base game's
--               expansion section instead.
