-- ─────────────────────────────────────────────────────────────────────────────
-- BoardgameBuddy — RPC function inventory
-- Last updated: 004_import_plays_rpc.sql (bgb_import_plays). The other 48
--               functions come from the 2026-09-01 collapse and live
--               in db/migrations/boardgamebuddy/003_rpcs.sql; each entry below
--               also names the archived migration its surviving definition
--               came from, since that file is where the reasoning is.
--               Reconciled against a database built from the collapsed
--               migrations: the 48 documented there are exactly the 48 that
--               existed at the collapse, with no stale or missing entries.
-- FOR REFERENCE ONLY — apply changes via db/migrations/
-- ─────────────────────────────────────────────────────────────────────────────

-- bgb_hot_games(window_days INT DEFAULT 7, lim INT DEFAULT 10)
--   → TABLE (game_id UUID, play_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/012_rpcs_feed_and_stats.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Top-N most-played games in the last N days for the Feed's
--               "Hot Games" card.

-- bgb_user_stats(uid UUID)
--   → TABLE (total_plays BIGINT, unique_games BIGINT, win_count BIGINT,
--            last_played_at DATE, hours_played NUMERIC, owned_games BIGINT,
--            owned_expansions BIGINT, favorite_game_id UUID,
--            favorite_game_name TEXT, favorite_play_count BIGINT)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/015_user_stats_with_favorite.sql)
--               (originally 012; widened to surface owned_games (base only),
--                owned_expansions, and favorite_game)
--   Called by:  shared-backend/routes/boardgame_buddy/services/stats_service.py
--   Purpose:    Per-user stats card on the Profile view (Played Games,
--               Owned Games, Wins, Favorite Game). owned_games excludes
--               expansions; owned_expansions is the secondary counter.

-- bgb_user_stats_detail(uid UUID)
--   → JSONB { career, podium, games, nemesis, rhythm, shelf, table_size,
--             taste, comeback, coop, personal_bests }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/058_user_stats_detail.sql)
--               (shelf block replaced by 059_shelf_played_before.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/stats_routes.py
--               (GET /users/me/stats/detail)
--   Purpose:    Everything on the Stats spoke (/profile/stats) in one call —
--               the most-played podium, a per-game win/score breakdown for
--               the picker, nemesis, a 26-week play heatmap with streaks,
--               the unplayed shelf, table-size distribution, category
--               taste, comeback-from-behind wins, the co-op record and
--               personal bests. Composed as one function for the same reason
--               bgb_profile_bundle is: every block reads the same "my plays"
--               set (logged-by-me OR I'm a participant, per migration 045),
--               so they share one materialized CTE instead of twelve round
--               trips. Written as a single SQL statement rather than plpgsql
--               + temp tables so it can stay STABLE — PostgREST runs a
--               non-volatile RPC inside a READ ONLY transaction.
--               Blocks needing a per-player row (wins, scores, comebacks,
--               co-op) can only speak for plays the user actually sat in, so
--               career carries rated_plays/rated_wins as their denominator
--               alongside total_plays/win_count. nemesis, table_size.avg and
--               rhythm.busiest_weekday are null when there is nothing to
--               compute; every other key is always present.
--               shelf (as of 059) is
--               {owned, played, unplayed, marked, games[], games_truncated}:
--               'played' counts a logged play OR a collections.played_before_at
--               mark, and 'games' is every owned base game with no logged
--               plays (capped at 300) for the Stats spoke's shelf sheet to
--               list and toggle. The mark is scoped to this block alone — no
--               other function or aggregate reads played_before_at.

-- bgb_feed_plays(viewer UUID, before_played_at DATE DEFAULT NULL,
--                before_created_at TIMESTAMPTZ DEFAULT NULL, lim INT DEFAULT 20)
--   → TABLE (play_id UUID, play_user_id UUID, play_user_name TEXT,
--            play_user_avatar JSONB, game_id UUID, game_name TEXT,
--            game_image_url TEXT, game_thumbnail_url TEXT, played_at DATE,
--            created_at TIMESTAMPTZ, notes TEXT, photo_url TEXT,
--            play_mode TEXT, winner_display_name TEXT,
--            participant_count INT, participants JSONB)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/014_feed_order_by_played_at.sql)
--               (originally 012; signature changed to a composite cursor)
--   Last updated in: db/migrations/boardgamebuddy/043_feed_perf_and_bootstrap_split.sql
--               (perf only, no behavior change — verified identical rows and
--               row order across 390 viewer x limit x cursor cases. A `page`
--               CTE now applies the cursor and LIMIT first and a LATERAL
--               resolves each page row's roster; previously the winners/
--               participants CTEs group-aggregated the entire play_players
--               table on every call — Postgres can't push the join qual
--               through a GROUP BY subquery — so feed latency grew with total
--               plays across all users, not the viewer's. 105 ms -> 5 ms on a
--               30k-play fixture. Language changed sql -> plpgsql so `lim` can
--               be interpolated as a literal via RETURN QUERY EXECUTE: as a
--               bind parameter it destroyed the planner's row estimate for
--               `page` and made the rewrite 8x slower than the original.)
--               Behavior last changed in 032_feed_plays_buddy_participation.sql
--               (visibility predicate widened from "logger ∈ visible OR
--               viewer ∈ participants" to "any participant ∈ visible",
--               so plays where a buddy was tagged but the logger is not
--               a buddy of the viewer now surface in the feed.)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Visible plays for the Feed: any play where the viewer or
--               an accepted buddy participated (via boardgamebuddy_play_players),
--               plus a legacy safety branch for logger ∈ visible. Pre-joined
--               to game name/image, winner display, and a participant-aware
--               roster. Ordered by played_at DESC, created_at DESC. Cursor
--               is the last row's (played_at, created_at) for lexicographic
--               tuple comparison.

-- bgb_dormant_collection(uid UUID, days_since INT DEFAULT 60, lim INT DEFAULT 5)
--   → TABLE (game_id UUID, last_played_at DATE)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/012_rpcs_feed_and_stats.sql)
--               db/migrations/boardgamebuddy/045_participated_play_stats.sql
--                 (was joining plays on p.user_id = uid only, so a game the
--                  user played but a buddy logged read as "never played" and
--                  got nudged at them; now counts participated plays)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--   Purpose:    Owned games this user hasn't played in N days; powers the
--               "Featured from your collection" Feed card.

-- bgb_suggested_buddies(uid UUID, lim INT DEFAULT 5)
--   → TABLE (user_id UUID, mutual_count BIGINT, play_count BIGINT,
--            pending_mutual_count BIGINT, via_user_id UUID)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/012_rpcs_feed_and_stats.sql)
--               db/migrations/boardgamebuddy/057_suggested_buddies_mutuals.sql
--                 (DROP + CREATE — the return type gained play_count. Adds
--                  played-with candidates alongside friends-of-friends and
--                  ranks shared plays above graph paths; excludes candidates
--                  on ANY existing edge with the viewer — pending and blocked
--                  included, not just accepted — and candidates with no
--                  profile row; lim now defaults to 5)
--               db/migrations/boardgamebuddy/066_suggested_buddies_skip_unset_profiles.sql
--                 (CREATE OR REPLACE — body only, so the GRANT survives. Adds
--                  `pr.needs_setup IS NOT TRUE` to the profile join, so a
--                  profile that has never been through the setup modal — email
--                  local-part as its display name, default badge — is no longer
--                  suggestable here either. 063 had the filter and this did
--                  not, which was an oversight rather than a decision.)
--               db/migrations/boardgamebuddy/072_suggestions_from_sent_requests.sql
--                 (DROP + CREATE — the return type gained pending_mutual_count
--                  and via_user_id. A pending request the VIEWER sent is now a
--                  first-hop link: the second traversal hops from those targets
--                  over their accepted edges. It gets its own count rather than
--                  being folded into mutual_count, so the tile's "Mutual buddy"
--                  stays true and no existing caller's number changes meaning.
--                  via_user_id names which first-hop person explains a
--                  candidate — an accepted link preferred over a pending one —
--                  so the tile can say "Buddy of Priya". The second hop stays
--                  accepted-only, and `connected` still excludes the people the
--                  viewer has asked.)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--               (embedded Feed rail, lim 5)
--               shared-backend/routes/boardgame_buddy/buddy_routes.py
--               (GET /buddies/suggested, lim 12)
--   Purpose:    Suggestion candidates the viewer is not yet connected to:
--               people they have shared a play with (ranked first, most plays
--               first), then friends-of-friends (by mutual count), then the
--               buddies of people the viewer has sent a request to and who
--               have not answered yet (weakest, sorted last), top `lim`.
--               Shared plays are counted the same way bgb_play_partners counts
--               them, so the Feed rail and the Buddies screen's "Played with"
--               list agree. Powers the Feed's "Buddies you may know" rail and
--               the same rail on the Buddies screen, which reads it through
--               GET /buddies/suggested rather than pulling a feed page.

-- bgb_onboarding_buddy_suggestions(uid UUID, lim INT DEFAULT 12,
--                                  active_window_days INT DEFAULT 90)
--   → TABLE (user_id UUID, mutual_count BIGINT, play_count BIGINT,
--            pending_mutual_count BIGINT, via_user_id UUID, source TEXT)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/063_onboarding_buddy_suggestions.sql)
--               db/migrations/boardgamebuddy/072_suggestions_from_sent_requests.sql
--                 (DROP + CREATE — the same two columns and the same
--                  sent-request traversal as bgb_suggested_buddies above, so
--                  the two functions stay the mirror of each other they were
--                  written to be. tier_graph's floor widened to admit a
--                  candidate whose only signal is a request the viewer sent;
--                  tier_active rows carry 0 and NULL for the new columns.)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--               (GET /buddies/suggested/onboarding, lim 12)
--   Purpose:    The onboarding "Add buddies" step's candidate list. Same
--               earned-signal candidates as bgb_suggested_buddies (returned
--               first, source='graph'), then a community fallback ranked by
--               plays logged in the last `active_window_days`
--               (source='active') — because the one user who is guaranteed to
--               get NOTHING out of bgb_suggested_buddies is the brand-new
--               account this screen exists for. Additionally excludes
--               profiles still carrying needs_setup, which have neither a
--               real display name nor a chosen badge yet. `source` travels to
--               the client because an 'active' candidate has both counts at
--               zero, which the tile would otherwise mislabel "Mutual buddy".
--               Shared plays are counted exactly as bgb_suggested_buddies
--               counts them, so the two suggestion surfaces can never disagree
--               about who the viewer has already played with.

-- bgb_onboarding_suggestion_network(uid UUID, seed_ids UUID[],
--                                   per_seed INT DEFAULT 6, lim INT DEFAULT 48)
--   → TABLE (via_user_id UUID, user_id UUID, buddy_count BIGINT,
--            rank_in_seed INT)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/072_suggestions_from_sent_requests.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/feed_service.py
--               (GET /buddies/suggested/onboarding, alongside the tier list)
--   Purpose:    The second hop, shipped up front. For each of the suggestions
--               the onboarding list just returned, who that person knows —
--               accepted edges only — so the onboarding deck can promote them
--               into the grid in the same frame as the tick that earned them,
--               with no round trip. Ranked inside a seed by the candidate's own
--               accepted-buddy count, so a `per_seed` cap keeps the
--               most-connected rather than the alphabetically luckiest, and
--               interleaved by rank so a global `lim` takes every seed's best
--               before any seed's second. Excludes the seeds themselves, the
--               viewer, anyone already on an edge with the viewer, and
--               needs_setup profiles — the same three exclusions the tier
--               function applies, for the same reasons. One candidate can be
--               returned under several seeds; the client keeps the first.

-- bgb_distinct_mechanics()
--   → TABLE (mechanic TEXT)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/019_perf_indexes.sql)
--   Called by:  (nothing — GET /games/mechanics, its only caller, was removed
--               as uncalled. Kept because the mechanics filter is a plausible
--               near-term feature and the function is free to keep.)
--   Purpose:    Sorted distinct mechanic strings across the games catalog,
--               without a full table scan + Python aggregation.

-- bgb_game_detail_bundle(game_uuid UUID, viewer UUID, plays_limit INT DEFAULT 5)
--   → JSONB
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/021_profile_and_game_detail_bundles.sql)
--   Last updated in: db/migrations/boardgamebuddy/023_game_detail_bundle_viewer_status_played.sql
--               (viewer_status now falls through to 'played' when the viewer
--               has any visible play of the game with no collection row —
--               same fix Profile bundle's status_map got in migration 022)
--               db/migrations/boardgamebuddy/055_hi_res_tile_art.sql
--                 (each expansion now carries image_url as well as
--                  thumbnail_url — the reel crops its polaroids at 132x110,
--                  which upscaled BGG's ~200px thumbnail)

--   Called by:  shared-backend/routes/boardgame_buddy/game_routes.py
--               (GET /games/{game_id}/bundle)
--   Purpose:    Single round-trip Game Detail payload: game row + base game
--               (when expansion) + viewer's collection status + last N
--               plays visible to viewer + expansions list with viewer's
--               toggle state. Reads denormalized plays.game_* fields (020)
--               so most rows don't join boardgamebuddy_games.

-- bgb_profile_bundle(viewer UUID, target UUID, col_per_page INT DEFAULT 12,
--                    plays_per_page INT DEFAULT 10)
--   → JSONB
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/021_profile_and_game_detail_bundles.sql)
--   Last updated in: db/migrations/boardgamebuddy/069_prev_owned_status.sql
--               (owned_page returns the SET ('owned','prev_owned') so the
--                Collection spoke's first-frame seed holds the same rows
--                bgb_collection_shelf will; owned_total stays owned-only and
--                is joined by the new owned_parted_total. status_map carries
--                'prev_owned' unaided — it has never had a status filter.
--                expansion_counts stays owned-only. bootstrap_version NOT
--                bumped: the added key is additive and a pre-069 bundle
--                missing it reads as zero, which is the old behaviour.)
--               db/migrations/boardgamebuddy/029_profile_avatar_config.sql
--                 (buddy + buddy-request blocks now emit `other_avatar` JSONB
--                  instead of `other_avatar_url` TEXT, following the
--                  avatar_url → avatar rename on boardgamebuddy_profiles)
--               db/migrations/boardgamebuddy/045_participated_play_stats.sql
--                 (played-shelf play_count reached play_players with a
--                  LEFT JOIN then COUNT(*), so a play the user logged was
--                  counted once per participant — a 4-player play read as
--                  4 plays. Now EXISTS, matching bgb_play_stats.)
--               db/migrations/boardgamebuddy/055_hi_res_tile_art.sql
--                 (owned/wishlist pages emit a real image_url instead
--                  of NULL, via a LEFT JOIN to boardgamebuddy_games — 020
--                  denormalized name/thumbnail onto collection rows but not
--                  the full-size art)
--               db/migrations/boardgamebuddy/064_profile_bundle_buddy_blocks.sql
--                 (Profile Other became buddy-aware: new `is_buddy` flag,
--                  new buddy-only `together` + `top_games` blocks, and
--                  `recent_plays` is NULL — not [] — for a viewer who is
--                  neither the target nor an accepted buddy. The COUNT
--                  `recent_plays_total` stays visible to everyone; it is one
--                  of the four headline stats a public profile shows.)
--               db/migrations/boardgamebuddy/071_profile_bundle_ghost_claims.sql
--                 (new self-only `ghost_claims_incoming` block beside
--                  `buddy_requests_incoming`, so the Profile tab's dot and the
--                  Buddies card's count are right on first paint. Additive and
--                  self-null, so bootstrap_version is deliberately NOT bumped —
--                  064's argument, verbatim. Its body is 069's verbatim: this
--                  function is replaced wholesale, so a migration that adds a
--                  key MUST be rebased onto whichever one defined it last.)

--   Called by:  shared-backend/routes/boardgame_buddy/profile_routes.py
--               (GET /profile/bundle)
--   Purpose:    Single round-trip Profile Self / Profile Other payload.
--               Stats + owned/wishlist/played first pages + recent plays +
--               viewer's status_map + expansion_counts. Buddies + pending
--               requests are included only when viewer = target; the plays
--               log, `together` and `top_games` only when viewer = target or
--               the two are accepted buddies. Reuses bgb_user_stats for the
--               stats block.
--               `together` mirrors bgb_user_stats_detail's `nemesis` rules —
--               competitive plays only, both people actual participants —
--               but with no 3-play floor, since the pair is already chosen.

-- bgb_bootstrap(viewer UUID, owned_plays_limit INT DEFAULT 5,
--               max_game_bundles INT DEFAULT 250)
--   → JSONB { bootstrap_version, generated_at, current_user, profile_bundle,
--             game_detail_bundles (object keyed by game_id), owned_count,
--             truncated }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/033_bootstrap_bundle.sql)
--   Last updated in: db/migrations/boardgamebuddy/043_feed_perf_and_bootstrap_split.sql
--               (bootstrap_version → 2; the game-bundle block is now skipped
--               when max_game_bundles <= 0, which is how the backend calls it)
--   Called by:  shared-backend/routes/boardgame_buddy/bootstrap_routes.py
--               (GET /bootstrap, with max_game_bundles = 0)
--   Purpose:    First-paint client cache warm-up. Composes bgb_profile_bundle
--               for the viewer into one JSONB. The FE writes everything into
--               its localStorage-backed cache so the entire app navigates
--               without further round trips until cached entries go stale.
--               game_detail_bundles is left empty on the live call path —
--               see bgb_game_bundles.

-- bgb_game_bundles(viewer UUID, owned_plays_limit INT DEFAULT 5,
--                  max_bundles INT DEFAULT 250)
--   → JSONB { game_detail_bundles (object keyed by game_id), owned_count,
--             truncated }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/043_feed_perf_and_bootstrap_split.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/bootstrap_routes.py
--               (GET /bootstrap/game-bundles)
--   Purpose:    Deferred second stage of the boot warm-up — one
--               bgb_game_detail_bundle per owned base game so opening Game
--               Detail is instant. Split out of bgb_bootstrap because it is
--               an N+1 in SQL (up to max_bundles invocations, ~5 statements
--               each) and nothing on the first screen reads it; the FE pulls
--               it from an idle callback after the user has landed, and Game
--               Detail falls back to its own fetch on a miss.
--               bootstrap_version is bumped any time this payload's shape
--               changes — the FE wipes its cache on mismatch.

-- bgb_session_bundle(p_session_id UUID)
--   → JSONB shaped like models.SessionResponse { id, code, status, phase,
--     host_user_id, game_id, game, participants[], scores[], created_at,
--     expires_at, finalized_play_id } or {"error": "not_found"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/036_session_rpcs.sql)
--   Last updated in: db/migrations/boardgamebuddy/056_participant_order.sql
--               (participants sort by `position NULLS LAST, joined_at` — the
--               one and only live participant-ordering site. 054 added
--               `scores`, the live grid, [] outside phase='play')
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (_build_response — the response builder for every session
--               endpoint; also invoked internally by the three RPCs below)
--   Purpose:    Single round-trip lobby payload: session row + participant
--               roster with profile avatars + optional GameSummary + the
--               live score grid. Replaced the 3-4 sequential PostgREST
--               selects _build_response used to fan out. The scores array is
--               how a spectator who joined after Gather sees the grid at all:
--               they hold no participant row, so the table's RLS SELECT
--               policy hides it from their own client (migration 054).

-- bgb_create_session(p_host UUID, p_host_display_name TEXT,
--                    p_game UUID DEFAULT NULL)
--   → JSONB (SessionResponse bundle) or {"error": "code_allocation_failed"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/036_session_rpcs.sql)
--   Last updated in: db/migrations/boardgamebuddy/056_participant_order.sql
--               (seats the host at position 0 — with a NULL there the host
--               sorts LAST the moment bgb_add_participant gives everyone else
--               a real position). Before that, 038:
--               (code entropy from uuid_send(gen_random_uuid()) — 036's
--               gen_random_bytes failed on Supabase because pgcrypto lives
--               in the `extensions` schema, outside the function's
--               search_path = public)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (create_session — POST /sessions)
--   Purpose:    One-call lobby open: abandons the host's stale open sessions,
--               allocates a unique 5-char Crockford code (≤6 retries against
--               the partial unique index on (code) WHERE status='open'),
--               seats the host as participant #1. The code alphabet and
--               length live only here — 036/038's comments point at
--               PLAY_SESSION_CODE_ALPHABET / _LENGTH in constants.py, which
--               no longer exist.

-- bgb_get_session(p_code TEXT)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/036_session_rpcs.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (get_session — GET /sessions/{code}, the 2s lobby poll)
--   Purpose:    Open/expiry-gated session fetch. Expired sessions are marked
--               status='abandoned' (status only, matching the old
--               _fetch_open_session) and reported as expired → 410.

-- bgb_join_session(p_code TEXT, p_user UUID DEFAULT NULL,
--                  p_user_display_name TEXT DEFAULT NULL,
--                  p_guest_display_name TEXT DEFAULT NULL)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired" |
--     "guest_name_required"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/036_session_rpcs.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (join_session — POST /sessions/{code}/join)
--   Purpose:    Idempotent one-call join. During Gather, adds authed callers
--               by user_id and guests by trimmed case-insensitive
--               display_name; after Gather the roster is untouched
--               (spectator). Same semantics the Python service had, minus
--               the 3-4 extra round trips.

-- bgb_game_summary(p_game_id UUID)
--   → JSONB shaped like models.GameSummary (bgg_url / expansion_count are
--     computed/defaulted Pydantic-side), or NULL for NULL/unknown ids
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/037_joinable_sessions_rpc.sql)
--   Called by:  (SQL-internal only) bgb_session_bundle, bgb_joinable_sessions
--   Purpose:    Canonical GameSummary JSON builder so every session RPC
--               emits the same game shape. Keys mirror _helpers._GAME_SELECT.

-- bgb_joinable_sessions(p_viewer UUID)
--   → JSONB array of models.JoinableSession { id, code, host_user_id,
--     host_display_name, host_avatar, game, phase, participant_count,
--     is_participant, is_host_buddy, created_at }, newest first
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/037_joinable_sessions_rpc.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (list_joinable — GET /sessions/joinable, the Join chooser)
--   Purpose:    One-call Join chooser payload: open unexpired sessions in
--               phase gather/play/settle visible to the viewer (own hosted,
--               already-joined, or hosted by an accepted buddy). Replaced
--               the 5 sequential PostgREST selects list_joinable fanned out.

-- bgb_log_play(p_user UUID, p_payload JSONB)
--   → JSONB shaped like models.PlayResponse { id, game_id, game_name,
--     game_thumbnail, played_at, notes, players[], photo_url, expansions[],
--     created_at, play_mode, country_code, logged_by_id, logged_by_name,
--     is_own }
--     or {"error": "game_not_found"}
--     or {"duplicate": true, "id": <uuid>} when p_payload.client_key is one
--     this user already has a play for (048) — the caller re-reads that row.
--   p_payload mirrors models.PlayCreate (a PlayCreate.model_dump(mode="json")).
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/042_write_rpcs.sql)
--               db/migrations/boardgamebuddy/044_cleanup.sql
--                 (stops writing plays.game_image_url / game_play_mode, which
--                  044 drops; stops writing the boardgamebuddy_buddies roster,
--                  whose only reader — GET /plays/filter-options — was removed;
--                  stops emitting the always-null buddy_id key on each player)
--               db/migrations/boardgamebuddy/048_play_client_key.sql
--                 (honours p_payload.client_key: pre-checks for a stored key,
--                  writes the column, and catches unique_violation for the
--                  concurrent case — both return the duplicate envelope)
--               db/migrations/boardgamebuddy/065_play_country.sql
--                 (reads p_payload.country_code, upper-cases it, drops
--                  anything that isn't ^[A-Z]{2}$ to NULL rather than failing
--                  the save, writes plays.country_code and echoes the
--                  NORMALIZED value back)
--   Called by:  shared-backend/routes/boardgame_buddy/play_routes.py
--               (log_play — POST /plays) and SQL-internally by
--               bgb_finalize_session
--   Purpose:    One-call play write: resolves the game, inserts the play with
--               its surviving denormalized game_* columns (migration 020),
--               bulk-writes play_players + play_expansions, and returns the
--               hydrated response. Replaced the 6 sequential PostgREST calls
--               log_play fanned out — including a read-back of the expansion
--               rows it had just inserted. Idempotent when the payload
--               carries a client_key, which is what makes the web app's
--               offline outbox safe to retry after a lost response.

-- bgb_import_plays(p_user UUID, p_payload JSONB)
--   → JSONB { imported: INT, duplicate: INT, failed: INT,
--             results: [ { index, id|null, duplicate, error|null } ] }
--   p_payload is { "plays": [ <PlayCreate.model_dump(mode="json")>, ... ] } —
--   the same per-play shape bgb_log_play takes, in an array.
--   Defined in: db/migrations/boardgamebuddy/004_import_plays_rpc.sql
--   Called by:  shared-backend/routes/boardgame_buddy/services/play_import_service.py
--               (import_plays — POST /plays/import, the Settings play importer)
--   Purpose:    Writes one chunk of an import in a single call. Owns no insert
--               logic: it loops the payload and calls bgb_log_play per element,
--               so game resolution, the denormalized game columns, client_key
--               idempotency and the player/expansion inserts have exactly one
--               implementation. A game_not_found element reports in `results`
--               and the rest of the chunk still lands — a batch that aborted
--               wholesale would make a 300-play import unfinishable over one
--               typo.

-- bgb_finalize_session(p_host UUID, p_code TEXT, p_payload JSONB)
--   → JSONB (PlayResponse, via bgb_log_play), {"duplicate": true, "id": UUID}
--     when the payload's client_key is one bgb_log_play already stored, or
--     {"error": "not_found" | "expired" | "forbidden" | "game_not_found"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/042_write_rpcs.sql)
--               (body replaced by 052_finalize_score_matches_rounds.sql, then
--                again by 053_host_only_live_scores.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (finalize_session — POST /sessions/{code}/finalize)
--   Purpose:    One-call wrap-up: open/expiry/host gates, calls bgb_log_play,
--               marks the session finalized. Replaced a 10 round-trip Python
--               chain — the host's Save used to block on all of it. A failed
--               write (game_not_found) leaves the session open so the host can
--               retry. The duplicate envelope passes straight through (it has
--               no `error` key and its `id` is the original play's), so the
--               session still gets finalized against that play — the caller
--               reads the row back via play_routes.load_play_response.
--               It no longer touches boardgamebuddy_play_session_scores at
--               all. 042 overlaid the joiners' live per-round totals onto the
--               host's player list and 052 narrowed that to a fallback for
--               players whose payload carried no round breakdown; migration
--               053 made the host the only person who can write a score, so
--               the payload IS the grid the host was looking at
--               (play-flow-view._commitResolvedScores folds the live overlay
--               into the draft before building it, and PlayerEntry re-derives
--               score from round_scores). An overlay could now only ever
--               disagree with the payload — which is exactly the class of bug
--               052 was written to fix.

-- bgb_plays_page(p_target UUID, p_page INT DEFAULT 1, p_per_page INT DEFAULT 20,
--                p_game UUID DEFAULT NULL, p_buddy UUID DEFAULT NULL,
--                p_search TEXT DEFAULT NULL, p_own_only BOOLEAN DEFAULT false)
--   → JSONB { plays: [models.PlayResponse-shaped...], total }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/039_perf_rpcs_and_indexes.sql)
--               (body replaced by 065_play_country.sql, which adds the
--                country_code key so a play keeps its country past the
--                response to its own POST)
--   Called by:  shared-backend/routes/boardgame_buddy/play_routes.py
--               (list_plays — GET /plays). The second caller, GET
--               /games/{id}/plays, was removed as uncalled; that data now
--               rides on /games/{id}/bundle.
--   Purpose:    One-call History page. Visibility = plays the target logged
--               plus plays where they appear as a participant. Filters
--               (game / buddy participant / free-text over game_name +
--               player_display_name), sort, LIMIT/OFFSET, and player +
--               expansion aggregation all in SQL. Replaced an 8-11 round
--               trip Python path that fetched every visible play tuple.
--               Reads denormalized plays.game_* columns (020).

-- bgb_play_stats(p_viewer UUID, p_game_ids UUID[] DEFAULT NULL)
--   → JSONB [ { game_id, play_count, last_played_at } ... ]
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/039_perf_rpcs_and_indexes.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/collection_routes.py
--               (_play_stats — GET /collection AND GET /collection/grid, both
--               shelves). Also services/game_service.py (recently_played —
--               GET /games/recently-played + the /bootstrap seed).
--               This is the reference implementation of the visibility rule;
--               migration 045 aligned the last two surfaces onto it.
--   Purpose:    Per-game play_count / last_played_at via SQL GROUP BY over
--               the viewer's visible plays (own + participant). Replaced
--               _plays_visible_to_user + _index_plays, which shipped every
--               play row to Python to count — unbounded post-BGG-sync.

-- bgb_bgg_sync_status(p_user UUID)
--   → JSONB { bgg_username, has_credentials, pending_count, errored_count,
--             last_completed_at, session_started_at, session_total,
--             session_done, session_errored, session_game_names[] }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/039_perf_rpcs_and_indexes.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/bgg_link_routes.py
--               (get_sync_status — GET /bgg/sync/status, FE poll target)
--   Purpose:    One-call import-progress poll (was up to 7 round trips per
--               poll). Session roll-up per distinct bgg_id mirrors the old
--               Python precedence (pending > error > done); names are the
--               20 most recently completed. has_credentials mirrors
--               bgg_client.has_stored_credentials so auth_state derives
--               without shipping the encrypted secret.

-- bgb_bgg_push_status(p_user UUID)
--   → JSONB { bgg_username, has_credentials, pending_count, errored_count,
--             last_completed_at, session_started_at, session_total,
--             session_done, session_errored, session_game_names[],
--             session_errors[{game_name, message}] }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/073_bgg_push_queue.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/bgg_push_routes.py
--               (get_push_status — GET /bgg/push/status, FE poll target)
--   Purpose:    The outbound twin of bgb_bgg_sync_status. Simpler: the queue
--               is UNIQUE(user_id, bgg_id), so one row per game and no
--               per-id roll-up or games join. session_errors has no import
--               counterpart and is the reason this is not a copy — a
--               half-failed import can be re-run and idempotency cleans up,
--               but a half-failed push has left flags on a third-party
--               account in an unknown state, so the user has to be told
--               which games. has_credentials uses the same expression as
--               bgb_bgg_sync_status so auth_state derives identically.

-- boardgamebuddy_search_games(p_viewer UUID, p_query TEXT, p_limit INT DEFAULT 20,
--                             p_include_expansions BOOLEAN DEFAULT false)
--   → TABLE (id UUID, bgg_id INT, name TEXT, year_published INT, min_players INT,
--            max_players INT, playing_time INT, thumbnail_url TEXT, image_url TEXT,
--            theme_color TEXT, is_expansion BOOLEAN, base_game_bgg_id INT,
--            expansion_color TEXT, rulebook_url TEXT, play_mode TEXT,
--            collection_status TEXT, in_collection BOOLEAN)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/040_search_rpc.sql)
--               db/migrations/boardgamebuddy/041_search_exclude_expansions.sql
--                 (adds p_include_expansions; drops + recreates the 3-arg form)
--   Called by:  shared-backend/routes/boardgame_buddy/services/search_service.py
--               (_rpc_hits — GET /search, the per-keystroke GameFinder)
--   Purpose:    One index-backed query for the unified game picker. Catalog
--               ILIKE '%q%' served by the pg_trgm GIN index (idx_bgb_games_name_trgm,
--               migration 039); LEFT JOIN onto the viewer's collection marks
--               in_collection + collection_status; collection-first ordering
--               (in_collection DESC, name) in SQL. Columns mirror _helpers._GAME_SELECT
--               plus the two collection extras. Replaced the two-query PostgREST
--               path whose collection match filtered an embedded !inner-joined
--               games.name column that the trigram index couldn't reliably serve.
--               search_service falls back to that path if this RPC is absent.
--               p_include_expansions defaults to false: expansions aren't
--               pickable as a session's main game and live in the base game's
--               expansion section instead.

-- bgb_session_gate(p_code TEXT, p_host UUID, p_require_gather BOOLEAN DEFAULT FALSE)
--   → JSONB {'session_id', 'host_user_id', 'game_id', 'phase'} or
--     {"error": "not_found" | "expired" | "host_only" | "roster_locked"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/046_session_write_rpcs.sql)
--   Called by:  (SQL-internal only) the five host-write RPCs below
--   Purpose:    Shared open/expiry/host/phase gate, a one-for-one port of
--               session_service._fetch_open_session plus each write's own
--               checks. The expiry path sets `status` only, not `phase`,
--               matching that helper and bgb_get_session. Deliberately NOT
--               retrofitted onto bgb_get_session / bgb_join_session: those sit
--               on the 2s poll path and 046 carries no behavior change there.

-- bgb_add_participant(p_host UUID, p_code TEXT, p_user UUID, p_display_name TEXT)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired" |
--     "host_only" | "roster_locked" | "display_name_required"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/046_session_write_rpcs.sql)
--   Last updated in: db/migrations/boardgamebuddy/056_participant_order.sql
--               (seats at position = max+1 so a host-added player lands at the
--               end of one ordering rather than in a second, NULL one)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (add_participant — POST /sessions/{code}/participants)
--   Purpose:    Host-seats a buddy (p_user set) or ghost (p_user NULL) in one
--               call where the service took four. Dedup mirrors
--               bgb_join_session — by user_id, or case-insensitively by
--               trimmed display_name — riding the two partial unique indexes,
--               with unique_violation swallowed so a double-tap is an
--               idempotent success rather than a 500.

-- bgb_reorder_participants(p_host UUID, p_code TEXT, p_order UUID[])
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired" |
--     "host_only" | "roster_locked"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/056_participant_order.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (reorder_participants — PUT /sessions/{code}/participants/order)
--   Purpose:    Host sets the roster's column order by handing over the full
--               ordered id array. The participants array's order IS the
--               scoring grid's column order on every surface, so this is what
--               carries a row the host dragged in Gather to the spectators'
--               mirror. Gather-only, on bgb_session_gate's require_gather arm,
--               same as add/remove. Ids from another session are ignored, and
--               participants the array omits — a joiner who arrived between
--               the drag and the write — are appended in joined_at order
--               rather than dropped, so a race can't drop someone off the
--               end of the grid.

-- bgb_remove_participant(p_host UUID, p_code TEXT, p_participant UUID)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired" |
--     "host_only" | "roster_locked" | "participant_not_found" |
--     "cannot_remove_host"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/046_session_write_rpcs.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (remove_participant — DELETE /sessions/{code}/participants/{id})
--   Purpose:    Gather-only roster removal, 4 round trips → 1. The host can't
--               be removed this way; abandoning ends a session.

-- bgb_update_session_game(p_host UUID, p_code TEXT, p_game UUID)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired" |
--     "host_only"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/046_session_write_rpcs.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (update_session_game — PATCH /sessions/{code})
--   Purpose:    Change or clear the lobby's game so joiners see the pick on
--               their next poll. Idempotent (skips the write when unchanged)
--               and allowed in any open phase, not just Gather — the host
--               flow's picker relies on that. p_game NULL clears the pick.

-- bgb_advance_phase(p_host UUID, p_code TEXT, p_phase TEXT, p_transitions JSONB)
--   → JSONB (SessionResponse bundle) or {"error": "not_found" | "expired" |
--     "host_only"} or {"error": "invalid_transition", "from": …, "to": …}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/046_session_write_rpcs.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (update_phase — PATCH /sessions/{code}/phase)
--   Purpose:    Move the Gather → Play → Settle cursor. p_transitions is
--               ALLOWED_PHASE_TRANSITIONS serialized by the service rather
--               than a copy of the table in SQL, so constants.py stays the
--               single source of truth; the service composes the dynamic 400
--               from the from/to keys. Re-asserting the current phase is a
--               no-op; 'abandoned' also flips `status`.

-- bgb_abandon_session(p_host UUID, p_code TEXT)
--   → JSONB {"ok": true} or {"error": "not_found" | "expired" | "host_only"}
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/046_session_write_rpcs.sql)
--   Called by:  shared-backend/routes/boardgame_buddy/services/session_service.py
--               (abandon_session — DELETE /sessions/{code})
--   Purpose:    Close an open lobby. Retiring this last Python-side gate let
--               session_service drop _fetch_open_session and _build_response
--               entirely — every path through that module is now one RPC.

-- bgb_play_partners(p_viewer UUID)
--   → JSONB { "accounts": [BuddyEdgeResponse…], "ghosts": [GhostPlayer…],
--             "recent": [PlayedWithUser…] }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/047_play_partners_rpc.sql)
--   Last updated in: db/migrations/boardgamebuddy/061_play_partners_pending_request_id.sql
--               (`recent` rows gained pending_request_id — the pending edge's
--                own id, so the Buddies screen's played-with row can cancel an
--                outgoing request or accept an incoming one without a second
--                /buddies/requests round trip to look the id up by user)
--   Called by:  shared-backend/routes/boardgame_buddy/services/played_with_service.py
--               (fetch_play_partners — GET /play-partners; fetch_played_with
--                and fetch_ghost_players slice their list off the same call),
--               plus bootstrap_routes.get_bootstrap's play_partners block.
--               GET /buddies keeps buddy_service.list_accepted_buddies: the
--               Buddies screen would otherwise compute ghosts and played-with
--               counts it never renders.
--   Purpose:    The Gather player picker in one call. Replaced twelve round
--               trips across three endpoints — including a pass that pulled
--               every play id the viewer touches into Python to count them in
--               a dict (unbounded after a BGG sync). Two asymmetries are
--               deliberate ports, not oversights: `recent` spans plays the
--               viewer logged OR appears in, while `ghosts` covers only plays
--               they logged; and ghost grouping is case-sensitive on the
--               trimmed name, matching the Python dict key.

-- bgb_collection_shelf(viewer UUID, target UUID, p_status TEXT DEFAULT 'owned',
--                      p_exclude_expansions BOOLEAN DEFAULT true,
--                      p_limit INT DEFAULT 1000)
--   → JSONB { "items": [CollectionItem…], "total": BIGINT,
--              "parted_total": BIGINT, "truncated": BOOLEAN }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/049_collection_shelf.sql)
--   Last updated in: db/migrations/boardgamebuddy/069_prev_owned_status.sql
--               (p_status='owned' now matches the SET ('owned','prev_owned') —
--                a game you sold is still on your Owned shelf, just dimmed —
--                and the new `parted_total` counts how many of the returned
--                rows are prev_owned so the client can subtract them from the
--                shelf's displayed count. `total` deliberately counts BOTH,
--                because `truncated` is about the rows on offer. Zero on the
--                wishlist and played branches.)
--               db/migrations/boardgamebuddy/055_hi_res_tile_art.sql
--                 (owned/wishlist items emit a real image_url instead of NULL,
--                  via a LEFT JOIN to boardgamebuddy_games for that one column;
--                  collection tiles crop square and were upscaling the ~200px
--                  thumbnail. The 'played' branch already had `g` in scope.)
--   Called by:  shared-backend/routes/boardgame_buddy/collection_routes.py
--               (GET /collection/shelf), which the web Collection and Wishlist
--               spokes call once per shelf via domain/collection.js.
--   Purpose:    A whole shelf in ONE round trip so the client can paginate,
--               filter and search locally. /collection/grid materialized the
--               entire shelf on every request and sliced it in Python, so page
--               9 cost what page 1 cost — ~1s per page turn. Three round trips
--               collapse to one here: the shelf reads the denormalized
--               c.game_* columns (020) rather than embedding the games row
--               (image_url is the one exception — see 055),
--               play stats fold in as a LATERAL (same visibility rule as
--               bgb_play_stats — logged-by OR participated-in), and
--               expansion_count is computed in SQL rather than a follow-up
--               IN-query, so the badge is right on the first cached paint.
--               Ordering matches /collection/grid's default so the client can
--               slice without re-sorting: owned/played by last_played_at DESC
--               NULLS LAST then added_at DESC, wishlist by added_at DESC.
--               `truncated` marks a shelf larger than p_limit; the client then
--               falls back to /collection/grid for search/filter rather than
--               narrowing an incomplete list. Wishlist is self-only, matching
--               bgb_profile_bundle. The 'played' branch DOES join
--               boardgamebuddy_games — those games have no collection row by
--               definition, so no denormalized columns exist for them, and by
--               the same token a prev_owned game stays OFF the played shelf:
--               it still has a collection row.
--   NOTE:       /collection/grid is deliberately still live — the native app
--               (app/src/api/client.js) and the web game explorer page against it.

-- bgb_link_ghost(p_viewer UUID, p_display_name TEXT, p_target UUID)
--   → JSONB { "updated": INT } | { "error": "not_found" }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/050_ghost_rpcs_and_status_map.sql)
--   Last updated in: 070_ghost_claims.sql — now a thin wrapper over
--               bgb_link_ghost_rows, and matches on lower(btrim(...)) rather
--               than ILIKE, so ' Davo ' is caught too. The widening is what
--               makes this and the claim key agree on one set of rows.
--   Called by:  services/played_with_service.link_ghost (POST /ghost-players/link)
--   Purpose:    Stamp a real account onto every ghost row matching a name in
--               the viewer's own plays. Replaces a SELECT of EVERY play id the
--               viewer owns, pulled into Python and handed back as a PostgREST
--               `in_` filter — which rides in the query string, so a few
--               hundred plays made a multi-KB URL and a few thousand failed
--               outright (414). Same "pull every play id into Python" pass 047
--               removed from /play-partners. PostgREST cannot put a subquery in
--               an UPDATE's WHERE, hence SQL. 3 round trips → 1.

-- bgb_merge_ghosts(p_viewer UUID, p_source TEXT, p_target TEXT)
--   → JSONB { "updated": INT }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/050_ghost_rpcs_and_status_map.sql)
--   Called by:  services/played_with_service.merge_ghosts (POST /ghost-players/merge)
--   Purpose:    Collapse two spellings of one ghost. Same query-string cliff as
--               bgb_link_ghost. 2 round trips → 1. Name validation (blank,
--               identical) stays in Python and still short-circuits with no DB
--               call at all.

-- bgb_collection_status_map(p_viewer UUID)
--   → JSONB { "status_map": {game_id: status}, "expansion_counts": {base_bgg_id: n} }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/050_ghost_rpcs_and_status_map.sql)
--   Last updated in: db/migrations/boardgamebuddy/069_prev_owned_status.sql
--               (status_map now carries 'prev_owned'. expansion_counts stays
--                owned-only on purpose — an expansion you sold is no longer
--                clutter on the base game's shelf.)
--   Called by:  collection_routes.collection_status_map (GET /collection/status-map),
--               which web/domain/collection.js reads for status pills and
--               expansion badges.
--   Purpose:    The two dicts the web client actually needs. It used to derive
--               them from GET /collection: three UNBOUNDED round trips (whole
--               collection + games join; bgb_play_stats over the viewer's
--               entire visible play history; an IN-query to hydrate
--               played-not-owned games) of which everything but these two dicts
--               was discarded — including the play stats that were round trip
--               2's only purpose. At a 60s fresh window it re-fired about once
--               a minute of active navigation. Round trip 2 grew with the
--               viewer's TOTAL VISIBLE plays, i.e. with their buddies' logging
--               too. Reads the denormalized game_* columns (020), so no games
--               join; the played branch uses the participated-in visibility
--               rule shared with bgb_play_stats (039/045).
--   NOTE:       GET /collection is deliberately unchanged — the native app
--               consumes its row shape (app/src/store/AppContext.js:262).

-- bgb_sync_achievements(uid UUID)
--   → JSONB { total, earned_count, metrics, groups[], achievements[] }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/062_achievements.sql)
--               (body replaced by 068_location_achievements.sql, which carries
--                plays.country_code through the my_plays CTE and adds the
--                countries / continents metrics)
--   Called by:  shared-backend/routes/boardgame_buddy/achievement_routes.py
--               (GET /achievements, POST /achievements/installed)
--   Purpose:    Everything on the Achievements spoke (/profile/achievements) in
--               one call. Computes all twelve metrics behind the nineteen
--               badges (plays logged, wins, biggest table, two-player-only
--               games played, buddies, guide chapters, chapters of yours
--               another player kept, plays you wrote notes on, whether BGG is
--               linked, whether the PWA is installed, distinct countries and
--               distinct continents played in),
--               inserts a boardgamebuddy_user_achievements row for anything
--               newly earned, then joins the catalog to those rows and returns
--               name / tagline / requirement / icon / threshold / progress /
--               earned / unlocked_at per badge.
--   NOTE:       VOLATILE — it writes the unlock rows. Deliberately one function
--               rather than a read plus a write: every caller wants both, and
--               the metrics pass is the expensive half. `earned` is read off
--               the unlock row rather than the live metric, which is what makes
--               a badge permanent once a play behind it is deleted. Plays use
--               the "logged it OR appeared on it" visibility rule shared with
--               bgb_play_stats (045) and bgb_user_stats_detail (058); wins are
--               necessarily narrower, since a win needs a player row.
--               two_player_games is the one metric that reaches the games
--               table — 020 denormalized name and thumbnail onto plays, never
--               the player counts. `continents` joins
--               boardgamebuddy_countries (068) with an INNER join on purpose:
--               bgb_log_play accepts any well-formed ^[A-Z]{2}$, so an
--               unmapped code counts toward `countries` and contributes no
--               continent rather than failing the whole screen.

-- ─────────────────────────────────────────────────────────────────────────────
-- Ghost account claims (migration 070)
--
-- A ghost is a play_players row with player_user_id NULL, owned implicitly by
-- whoever logged the play. bgb_link_ghost runs owner → ghost; these run the
-- other way: the claimant asks, the owner approves, and approving performs
-- that same merge.
-- ─────────────────────────────────────────────────────────────────────────────

-- bgb_link_ghost_rows(p_owner UUID, p_name_key TEXT, p_target UUID)
--   → INT (rows moved)
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  bgb_link_ghost, bgb_accept_ghost_claim (SQL only — no route)
--   Purpose:    THE ghost→account merge, extracted so the owner-initiated link
--               and the claimant-initiated claim move exactly the same rows.
--               Two copies is how a claim comes to describe 12 plays and merge
--               9. Scoped to the owner's own plays.

-- bgb_ghost_summary(p_viewer UUID, p_owner UUID, p_name_key TEXT)
--   → JSONB { exists, play_count, last_played_at, last_game_name,
--             ghost_display_name, collides, visible }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  bgb_ghost_claim_detail, bgb_create_ghost_claim,
--               bgb_accept_ghost_claim, bgb_dismiss_ghost_claim (SQL only)
--   Purpose:    The four facts every single-ghost path needs, computed once so
--               they cannot disagree. `visible` mirrors the FEED's rule (043);
--               `collides` is the double-seat guard — there is no unique
--               constraint on (play_id, player_user_id), so this check is the
--               only thing stopping one person appearing twice in one game.

-- bgb_ghost_claim_suggestions(p_viewer UUID, p_limit INT DEFAULT 10,
--                             p_threshold REAL DEFAULT 0.35)
--   → JSONB [ {owner_user_id, owner_display_name, owner_username, owner_avatar,
--              ghost_display_name, ghost_name_key, play_count, last_played_at,
--              last_game_name, match_score, claim_status, claim_id} ]
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  services/ghost_claim_service.fetch_suggestions
--               (GET /ghost-claims/suggestions)
--   Purpose:    The Buddies screen's "Is this you?" list. Scans ACCEPTED
--               BUDDIES' rosters only — a proactive suggestion volunteers
--               someone else's nickname, so it stays conservative (the tap
--               path, bgb_ghost_claim_detail, is deliberately wider).
--               Trigram similarity plus a prefix/first-name branch, because
--               the load-bearing case is a nickname: "davo" vs "Davo Smith"
--               scores ~0.31 on trigrams alone and would miss.
--               NOTE: idx_bgb_play_players_display_name_trgm cannot serve this
--               — GIN trigram indexes need %/<%/<->, which need set_limit(),
--               which is VOLATILE and illegal in a STABLE function. The
--               candidate set is narrowed to buddies' rosters first instead.

-- bgb_ghost_claim_detail(p_viewer UUID, p_play_id UUID, p_display_name TEXT)
--   → JSONB { …suggestion fields…, can_claim, blocked_reason }
--            | { "error": "not_visible" | "ghost_gone" | ... }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  services/ghost_claim_service.fetch_detail (GET /ghost-claims/lookup)
--   Purpose:    Backs the claim sheet opened from a polaroid back or the
--               play-detail players list. Takes the PLAY id because that is
--               what a tapped scoreboard row has. No similarity filter — the
--               user tapped a specific row and the matcher does not get a
--               veto; blocked_reason lets the sheet paint a truthful disabled
--               state instead of a button that 409s.

-- bgb_ghost_claims(p_viewer UUID)
--   → JSONB { incoming: [...], outgoing: [...] }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  services/ghost_claim_service.list_claims (GET /ghost-claims)
--   Purpose:    Both sides of the request list, mirroring GET /buddies/requests.
--               An RPC because every row needs a live play_count /
--               last_played_at, and doing that per claim in Python is the same
--               N+1 that 047 and 050 exist to remove.

-- bgb_create_ghost_claim(p_claimant UUID, p_owner UUID, p_display_name TEXT)
--   → JSONB (the outgoing claim) | { "error": "own_roster" | "ghost_gone" |
--     "not_visible" | "already_seated" | "already_linked" | "declined_twice" }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  services/ghost_claim_service.create_claim (POST /ghost-claims)
--   Purpose:    Send a claim. Validation and upsert in one call so there is no
--               window between "the ghost exists, is visible, does not collide"
--               and the row asserting it. Idempotent while pending (matching
--               buddy_service.send_request); re-ask allowed after one decline,
--               refused after two.

-- bgb_accept_ghost_claim(p_owner UUID, p_claim_id UUID)
--   → JSONB { updated: INT, claim: {...} } | { "error": "claim_not_found" |
--     "not_pending" | "already_seated" | "ghost_gone" }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  services/ghost_claim_service.accept_claim
--               (POST /ghost-claims/{id}/accept)
--   Purpose:    Approve and merge, in one transaction. Re-checks the double-seat
--               collision (state moves between request and accept), retires the
--               claim as 'superseded' if the ghost was renamed away, and
--               supersedes any other claimant still pending on the same ghost —
--               their rows no longer exist, so leaving them pending would offer
--               the owner an Accept that can only fail. 404 rather than 403 for
--               a non-owner: do not confirm the claim exists.

-- bgb_reject_ghost_claim(p_owner UUID, p_claim_id UUID)
--   → JSONB { "rejected": true } | { "error": "claim_not_found" | "not_pending" }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  services/ghost_claim_service.reject_claim
--               (POST /ghost-claims/{id}/reject)
--   Purpose:    Owner declines, and reject_count is incremented — an RPC
--               precisely because PostgREST cannot express `col = col + 1`.
--               Contrast cancel (the claimant withdrawing), a plain
--               ownership-checked DELETE that stays in Python: withdrawing your
--               own ask is not a decline and must not burn a strike.

-- bgb_dismiss_ghost_claim(p_claimant UUID, p_owner UUID, p_display_name TEXT)
--   → JSONB { "dismissed": true } | { "error": "own_roster" | ... }
--   Defined in: db/migrations/boardgamebuddy/003_rpcs.sql
--               (collapsed from archive/070_ghost_claims.sql)
--   Called by:  services/ghost_claim_service.dismiss_suggestion
--               (POST /ghost-claims/dismiss)
--   Purpose:    The claimant's "Not me". Writes the same row a real claim would,
--               so a later change of mind flips it back to pending rather than
--               opening a second row. Never overwrites an 'accepted' row.
