-- ─────────────────────────────────────────────────────────────────────────────
-- Travel Scrapbook — RPC function inventory
-- Last updated: 2026-07-17 (020 checkpoint unification: role-aware RPCs)
-- FOR REFERENCE ONLY — apply changes via db/migrations/
-- ─────────────────────────────────────────────────────────────────────────────

-- travelscrapbook__scrap_place_json(p_place_id UUID)
--   → JSONB {place_name, place_city, place_region, place_country, category,
--            lat, lng, geocode_confidence, geocode_display_name, maps_url,
--            og_image_url, sources[]}
--   Defined in: db/migrations/travelscrapbook/015_perf_rpcs.sql
--   Called by:  (internal helper — composed by the bundle RPCs below)
--   Purpose:    Flattened place fields + source chips for one scrap, exactly
--               mirroring services/hydrate.py's per-scrap place block.

-- travelscrapbook__membership_vibes_json(p_membership_id UUID)
--   → JSONB [{user_id, display_name, level}]
--   Defined in: db/migrations/travelscrapbook/015_perf_rpcs.sql
--   Called by:  (internal helper — composed by the bundle RPCs below)
--   Purpose:    One membership's raw vibe rows with traveler display names;
--               the consensus roll-up stays in Python (hydrate.attach_consensus).

-- travelscrapbook_trip_bundle(p_trip_id UUID, p_viewer UUID)
--   → JSONB {trip, role, owner_display_name, anchors[], scraps[], members[],
--            candidates[]} | NULL when the viewer has no access
--   NOTE: the RPC's `anchors[]` JSON key is FROZEN; the
--   backend (trip_routes.build) surfaces it to API clients as `checkpoints[]`
--   (TripResponse.checkpoints). Likewise the synthesized rows' `anchor_date`/
--   `anchor_time` are exposed as `checkpoint_date`/`checkpoint_time`.
--   Defined in: db/migrations/travelscrapbook/026_endpoint_unification.sql
--               (latest; first in 015, also redefined in 018 and 020)
--   Notes:      scraps = plan memberships only; anchors[] is SYNTHESIZED from
--               role-bearing memberships in the legacy anchor shape, ordered
--               by membership created_at, stay/travel only; arrival/departure
--               are role-NULL plans in scraps[], each scrap carrying
--               is_arrival/is_departure + plan_end_date. candidates exclude
--               dismissed pairs and checkpoint-category places.
--   Called by:  shared-backend/routes/travel_scrapbook/trip_routes.py (get_trip)
--   Purpose:    The whole trip screen in ONE round trip. Access (owner or accepted
--               member) is enforced inside since service role bypasses RLS.
--               The Python twin of the anchor synthesis lives in
--               services/checkpoints.synthesize_anchor — keep them in step.

-- travelscrapbook_trips_list(p_viewer UUID)
--   → JSONB [trip row + owner_user_id, owner_display_name, role, scrap_count]
--   Defined in: db/migrations/travelscrapbook/015_perf_rpcs.sql
--   Called by:  shared-backend/routes/travel_scrapbook/trip_routes.py (list_trips)
--   Purpose:    Owned + accepted-shared trips, newest first, with counts and
--               roles — the trips landing screen in one round trip.

-- travelscrapbook_scrap_card(p_scrap_id UUID, p_trip_id UUID)
--   → JSONB one hydrated membership-scoped scrap | NULL when not on that trip
--   Defined in: db/migrations/travelscrapbook/026_endpoint_unification.sql
--               (latest; first in 015, also redefined in 020)
--   Notes:      Resolves the PLAN membership only — a scrap can also hold
--               checkpoint memberships on the same trip — and passes
--               role/plan_end_date through; echoes is_arrival/is_departure
--               for the endpoint bookend reconcile.
--   Called by:  shared-backend/routes/travel_scrapbook/scrap_routes.py
--               (_hydrated_membership — the echo for assign/approve/schedule/
--               vibe endpoints)
--   Purpose:    Cheap single-scrap echo after membership mutations. Callers check trip access
--               BEFORE the mutation.

-- travelscrapbook_inbox_bundle(p_viewer UUID, p_region TEXT, p_country TEXT,
--                              p_city TEXT, p_limit INT, p_offset INT)
--   → JSONB {scraps[] (+trip_ids), checkpoint_scraps[], total,
--            checkpoint_total, unvisited_count, facets,
--            processing_sources[], failed_sources[], geocoded_trips[]}
--   Defined in: db/migrations/travelscrapbook/025_trip_suggestions_union.sql
--               (latest; first in 015, also redefined in 020)
--   Notes:      Checkpoint-category scraps sit in their own capped array; the
--               paginated scraps / total / nav badge count non-checkpoint
--               places; trip_ids counts plan memberships only; facets stay
--               over the full base. geocoded_trips carry member_countries/
--               member_regions for the additive-union scope in
--               services/places.suggest_trips.
--   Called by:  shared-backend/routes/travel_scrapbook/source_routes.py (get_inbox)
--   Purpose:    The Wander List screen in one round trip: SQL-side filter/
--               facets/pagination plus the geocoded trips that feed
--               Python-side suggestions.

-- travelscrapbook_visited_page(p_viewer UUID, p_region TEXT, p_country TEXT,
--                              p_city TEXT, p_limit INT, p_offset INT)
--   → JSONB {scraps[], visited_checkpoints[], total, checkpoint_total, facets}
--   Defined in: db/migrations/travelscrapbook/020_unify_checkpoints.sql
--               (latest; first in 015)
--   Notes:      Same checkpoint split as the inbox bundle.
--   Called by:  shared-backend/routes/travel_scrapbook/scrap_routes.py (list_visited)
--   Purpose:    One filtered page of visited places with facets, paginated in
--               SQL, plus the visited checkpoint places as their own section.

-- travelscrapbook_community_places(p_q TEXT, p_region TEXT, p_country TEXT,
--                                  p_city TEXT, p_category TEXT,
--                                  p_limit INT, p_offset INT,
--                                  p_checkpoints BOOLEAN DEFAULT false)
--   → JSONB {places[], total, facets}
--   Defined in: db/migrations/travelscrapbook/020_unify_checkpoints.sql
--               (latest; first in 015)
--   Notes:      p_checkpoints partitions the pool: false = ordinary places,
--               true = the Stays & transport tab.
--   Called by:  shared-backend/routes/travel_scrapbook/community_routes.py
--               (list_community_places)
--   Purpose:    The community catalog page in one round trip: group by OSM
--               identity (else normalized name + country), pick the most
--               complete representative, count distinct savers, filter/facet/
--               paginate, attach deduped source chips for the page only.

-- travelscrapbook_trip_suggestions(p_trip_id UUID, p_viewer UUID,
--                                  p_category TEXT DEFAULT NULL,
--                                  p_checkpoints BOOLEAN DEFAULT false,
--                                  p_q TEXT DEFAULT NULL,
--                                  p_limit INT DEFAULT 6, p_offset INT DEFAULT 0)
--   → JSONB {items[], total, categories[]}
--   Defined in: db/migrations/travelscrapbook/025_trip_suggestions_union.sql
--               (latest; first in 024)
--   Called by:  shared-backend/routes/travel_scrapbook/plan_routes.py
--               (list_trip_suggestions)
--   Purpose:    The unified "add to trip" picker feed in one round trip. Merges
--               the viewer's wander list (higher priority) with the community
--               pool, filters to the trip's geo scope, splits by the checkpoint
--               partition (false = plans, true = stays & transport), ranks
--               wander-first then nearest to the trip's placed plans (centroid,
--               falling back to the destination centroid; haversine mirrors
--               services/optimizer.py). Category is applied post-merge so the
--               returned `categories` facet always reflects the whole scoped
--               pool. Geo scope is the UNION of the trip's destination with the
--               countries/regions of its approved members (mirrors the additive
--               union in services/places.place_matches_trip_scope); candidates
--               without a pin are kept (lat only gates the radius sub-branch).

-- travelscrapbook_add_plan_memberships(p_rows JSONB,
--                                      p_status TEXT DEFAULT 'approved')
--   → VOID   (p_rows: [{"scrap_id": "...", "trip_id": "..."}, ...])
--   Defined in: db/migrations/travelscrapbook/020_unify_checkpoints.sql
--   Called by:  shared-backend/routes/travel_scrapbook/plan_routes.py
--               (_add_plan_memberships → assign/assign-many/set_scrap_trips),
--               source_routes.py (capture trip-hint), community_routes.py
--               (save_community_place)
--   Purpose:    Insert PLAN memberships idempotently, one round trip for any
--               (scrap, trip) fan-out shape. Needed because the plan uniqueness
--               is a PARTIAL index (scrap_id, trip_id WHERE role IS
--               NULL), which PostgREST's on_conflict cannot arbitrate — the
--               RPC emits the index-predicate ON CONFLICT form.

-- travelscrapbook__normalize_name(t TEXT)
--   → TEXT
--   Defined in: db/migrations/travelscrapbook/020_unify_checkpoints.sql
--   Called by:  (migration-internal — the 020 anchor backfill's place dedupe)
--   Purpose:    Extension-free approximation of Python's normalize_place_name
--               (accent fold via translate(), lowercase, non-alnum → space,
--               strip leading "the "). Kept for re-runs of the backfill.
