// Shared stylesheet for the SauceBuilder wizard. Centralizing it here lets
// each step component import the same tokens without prop-drilling or
// duplicating definitions.

import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS } from '../../theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.background },
  header: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
  },
  closeBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollBody: {
    padding: 16,
    paddingBottom: 60,
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    ...SHADOWS.sm,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.text,
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 0.3,
    marginTop: 8,
    marginBottom: 4,
  },
  // Heavier section header for the Info + Pairing steps so field groups
  // (Name, Description, Cuisine, Color, Type, Dish) read as proper headings
  // rather than the small uppercase labels used inside step cards.
  fieldHeader: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.text,
    marginTop: 18,
    marginBottom: 6,
  },
  input: {
    backgroundColor: COLORS.background,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: COLORS.text,
  },
  multiline: {
    minHeight: 60,
    textAlignVertical: 'top',
  },
  titleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  titleCol: {
    flex: 1,
  },
  timeCol: {
    width: 84,
  },
  timeWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    paddingRight: 10,
  },
  timeInput: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: COLORS.text,
    textAlign: 'right',
  },
  timeSuffix: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.card,
  },
  pillActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  pillLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  pillLabelActive: {
    color: '#fff',
  },
  swatchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  swatch: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  swatchActive: {
    borderColor: COLORS.text,
  },
  importRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  smallBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallBtnLabel: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 13,
  },
  smallBtnSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 6,
  },
  smallBtnSecondaryLabel: {
    color: COLORS.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  importFileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  btnDisabled: {
    opacity: 0.45,
  },
  // Mirrors the web's ✍️ "Manual Entry" source-card. Positioned directly
  // after the file-import row so the three working options (URL, file,
  // manual) sit together.
  manualEntryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.highlightTint,
  },
  manualEntryBody: {
    flex: 1,
  },
  manualEntryTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.primaryDark,
  },
  manualEntryDesc: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  help: {
    fontSize: 11,
    color: COLORS.textMuted,
    marginTop: 6,
    lineHeight: 14,
  },
  stepBox: {
    backgroundColor: COLORS.background,
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  // Step-number badge sized as a peer of the ingredient chips below — same
  // border + radius, warm cream fill. Matches the web 7fd5f75 silhouette.
  stepNumber: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
    color: COLORS.primaryDark,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    overflow: 'hidden',
  },
  removeStep: {
    padding: 4,
  },
  ingChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 6,
    gap: 8,
  },
  ingChipIncomplete: {
    borderColor: COLORS.warningText,
    backgroundColor: COLORS.warning,
  },
  ingChipBody: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  ingChipName: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.text,
    flexShrink: 1,
  },
  ingChipQty: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  ingChipActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ingChipRemove: {
    padding: 2,
  },
  ingEmpty: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontStyle: 'italic',
    marginTop: 6,
    textAlign: 'center',
  },
  stepActionPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
  },
  addIngPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: COLORS.primary,
    backgroundColor: 'transparent',
  },
  addIngPillLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.primary,
    marginLeft: 6,
  },
  combineChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.highlightTint,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginTop: 6,
  },
  combineChipLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.primaryDark,
  },
  combineChipBtn: {
    padding: 4,
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  addBtnLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.primary,
    marginLeft: 6,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.highlightTint,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginTop: 4,
    marginBottom: 4,
  },
  refBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.primaryDark,
    marginLeft: 4,
    flex: 1,
  },
  unassignedCard: {
    backgroundColor: COLORS.background,
    borderRadius: 10,
    padding: 10,
    marginTop: 8,
  },
  unassignedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  unassignedName: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.text,
  },
  unassignedQty: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginRight: 8,
  },
  unassignedDelete: {
    padding: 4,
  },
  unassignedTargets: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
  },
  targetPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.card,
  },
  targetPillLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
  },
  errorBlock: {
    backgroundColor: COLORS.danger,
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  errorTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.dangerText,
    marginBottom: 4,
  },
  errorBullet: {
    fontSize: 12,
    color: COLORS.dangerText,
    marginVertical: 1,
  },
  error: {
    color: COLORS.dangerText,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
  },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 14,
    marginTop: 4,
  },
  saveBtnLabel: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
    marginLeft: 6,
  },
  backLink: {
    marginTop: 10,
    alignSelf: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  backLinkLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.primary,
  },
  reviewSourceBubble: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  reviewSourceLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.text,
  },
  reviewSourceUrl: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  reviewField: {
    fontSize: 13,
    color: COLORS.text,
    paddingVertical: 4,
  },
  backToEditBtn: {
    marginTop: 10,
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  backToEditLabel: {
    color: COLORS.textSecondary,
    fontWeight: '700',
    fontSize: 13,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  reviewSwatch: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
  },
  reviewName: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.text,
  },
  reviewMeta: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  reviewDescription: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 18,
    marginTop: 4,
  },
  reviewMetaRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewMetaLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.primary,
    letterSpacing: 0.4,
  },
  reviewStepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  reviewStepNumber: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.primary,
    letterSpacing: 0.6,
  },
  reviewStepTime: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  reviewStepTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 4,
  },
  reviewStepInstructions: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 18,
    marginVertical: 4,
  },
  reviewIngList: {
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: COLORS.surfaceSubtle,
  },
  reviewIngRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  reviewIngName: {
    flex: 1,
    fontSize: 13,
    color: COLORS.text,
    marginRight: 8,
  },
  reviewIngQty: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  reviewSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  editPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.card,
  },
  editPillLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
  },
  standaloneHint: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.primaryDark,
    textAlign: 'center',
  },
});
