// config.js — PlantPlanner API config
// In production, this file is regenerated by build.sh from VIBELAB_SUPABASE_URL /
// VIBELAB_SUPABASE_ANON_KEY GitHub secrets. For local dev, fill the supabase fields
// from the shared Supabase project before running.
window.APP_CONFIG = {
  apiBase: "https://vibelab-production-2119.up.railway.app",
  project: "plant-planner",
  supabaseUrl: "",
  supabaseAnonKey: ""
};
